Repository kunjgit/GameZone, pull requests merged in 2023-06, with the labels that each got.

#644 Stick Hero game (#71)
  Games/Stick_Hero_Game/README.md
  Games/Stick_Hero_Game/assets/Image.jpeg
  Games/Stick_Hero_Game/assets/Stick_hero.gif
  Games/Stick_Hero_Game/index.html
  Games/Stick_Hero_Game/script.js
  Games/Stick_Hero_Game/style.css
  README.md
Labels: GSSoC23, level3

#650 frontend changes in memory game
  Games/Memory_Game/style.css
Labels: GSSoC23, level2

#636 starwars game added
  Games/Starwars_Character_Game/README.md
  Games/Starwars_Character_Game/images/din_djarin.png
  Games/Starwars_Character_Game/images/disney_plus.png
  Games/Starwars_Character_Game/images/favicon.ico
  Games/Starwars_Character_Game/images/han_solo.png
  Games/Starwars_Character_Game/images/lucasfilm.png
  Games/Starwars_Character_Game/images/luke_skywalker.png
  Games/Starwars_Character_Game/images/rey.png
  Games/Starwars_Character_Game/index.html
  Games/Starwars_Character_Game/index.js
  Games/Starwars_Character_Game/styles.css
  README.md
  assets/images/starwars.png
Labels: GSSoC23, level3

#633 Enhance button click event handling for better accessibility
  Games/Guess_The_Number/main.js
Labels: GSSoC23, level2

#630 Traffic run
  Games/Traffic_Run/README.md
  Games/Traffic_Run/assests/images/Traffic_Run.PNG
  Games/Traffic_Run/index.html
  Games/Traffic_Run/script.js
  Games/Traffic_Run/style.css
  README.md
  assets/images/Traffic_Run.PNG
Labels: GSSoC23, level3

#358 Tower defense
  Games/Tower_Defense/README.md
  Games/Tower_Defense/index.html
  Games/Tower_Defense/script.js
  Games/Tower_Defense/style.css
  README.md
  assets/images/tower_defense.png
Labels: GSSoC23, level3

#364 #348 Bird_game
  Games/Bird_game/README.md
  Games/Bird_game/index.css
  Games/Bird_game/index.html
  README.md
  assets/images/Bird_game.png
Labels: GSSoC23, level3

#394 [New Game] : Added Bubble_Blast_Game
  Games/Bubble_Blast_Game/assets/Bubble_Blast_Game.png
  Games/Bubble_Blast_Game/assets/bubble-sprites.png
  Games/Bubble_Blast_Game/assets/bubble1.png
  Games/Bubble_Blast_Game/assets/bubble2.png
  Games/Bubble_Blast_Game/index.html
  Games/Bubble_Blast_Game/script.js
  Games/Bubble_Blast_Game/start.html
  Games/Bubble_Blast_Game/style.css
  README.md
  assets/images/Bubble_Blast_Game.png
Labels: GSSoC23, level3

#398 Completed making Emoji Charades game
  Games/Emoji_Charades/README.md
  Games/Emoji_Charades/index.html
  Games/Emoji_Charades/script.js
  Games/Emoji_Charades/sounds/correct.mp3
  Games/Emoji_Charades/sounds/wrong.mp3
  Games/Emoji_Charades/style.css
  README.md
  assets/images/Emoji_Charades.jpg
Labels: Pending, changes requested

#466 Adding new Game "Drum_And_Kit"
  Games/Drum_Kit_Game/README.md
  Games/Drum_Kit_Game/assets/images/Drum_And_Kit.PNG
  Games/Drum_Kit_Game/images/crash.png
  Games/Drum_Kit_Game/images/kick.png
  Games/Drum_Kit_Game/images/snare.png
  Games/Drum_Kit_Game/images/tom1.png
  Games/Drum_Kit_Game/images/tom2.png
  Games/Drum_Kit_Game/images/tom3.png
  Games/Drum_Kit_Game/images/tom4.png
  Games/Drum_Kit_Game/index.html
  Games/Drum_Kit_Game/script.js
  Games/Drum_Kit_Game/sounds/crash.mp3
  Games/Drum_Kit_Game/sounds/kick-bass.mp3
  Games/Drum_Kit_Game/sounds/snare.mp3
  Games/Drum_Kit_Game/sounds/tom-1.mp3
  Games/Drum_Kit_Game/sounds/tom-2.mp3
  Games/Drum_Kit_Game/sounds/tom-3.mp3
  Games/Drum_Kit_Game/sounds/tom-4.mp3
  Games/Drum_Kit_Game/styles.css
  README.md
  assets/images/Drum_And_Kit.PNG
Labels: Pending, changes requested

#471 Added Rock Paper Scissors
  Games/Rock_Paper_Scissors/README.md
  Games/Rock_Paper_Scissors/assets/KaushanScript-Regular.ttf
  Games/Rock_Paper_Scissors/index.html
  Games/Rock_Paper_Scissors/script.js
  Games/Rock_Paper_Scissors/style.css
  README.md
  assets/images/Rock_Paper_Scissors.png
Labels: GSSoC23, level3

#498 Timer added to Master Typing
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
Labels: GSSoC23, level2

#528 #163 Frogger
  Games/Frogger/README.md
  Games/Frogger/assets/collision.wav
  Games/Frogger/assets/move.wav
  Games/Frogger/assets/winner.wav
  Games/Frogger/index.html
  Games/Frogger/script.js
  Games/Frogger/style.css
  README.md
  assets/images/Frogger.png
Labels: Ready to merge

#551 [New Game]: Not_morethan5 #550
  Games/Not_morethan5/README.md
  Games/Not_morethan5/css/style.css
  Games/Not_morethan5/index.html
  Games/Not_morethan5/js/app.js
  Games/Not_morethan5/js/plugins.js
  README.md
  assets/images/!morethan5.png
Labels: GSSoC23, level3

#606 ADD GAME: UNRULY TOWER 🕹️
  Games/Unruly_Tower/README.md
  Games/Unruly_Tower/index.html
  Games/Unruly_Tower/script.js
  Games/Unruly_Tower/style.css
  README.md
  assets/images/Unruly_Tower.png
Labels: Pending, changes requested

#621 Maze Game #46
  Games/MazeGame/README.md
  Games/MazeGame/home.png
  Games/MazeGame/index.html
  Games/MazeGame/key.png
  Games/MazeGame/script.js
  Games/MazeGame/style.css
  README.md
  assets/images/MazeGame.png
Labels: GSSoC23, level3

#657 2048_game [gssoc'23]
  Games/2048/README.md
  Games/2048/index.html
  Games/2048/script.js
  Games/2048/style.css
  README.md
  assets/images/2048.png
Labels: GSSoC23, level3

#668 solved issue #436
  Games/Spin_the_wheel/README.md
  Games/Spin_the_wheel/images/arrow.png
  Games/Spin_the_wheel/index.html
  Games/Spin_the_wheel/script.js
  Games/Spin_the_wheel/style.css
  README.md
  assets/images/Spin_the_wheel.png
Labels: GSSoC23, level3

#680 [New Game]: Tower blocks
  Games/Tower_Blocks/README.md
  Games/Tower_Blocks/index.html
  Games/Tower_Blocks/script.js
  Games/Tower_Blocks/style.css
  README.md
  assets/images/Tower_Blocks.png
Labels: GSSoC23, level3

#682 Added the Platform_Game
  Games/Platform_Game/README.md
  Games/Platform_Game/index.html
  Games/Platform_Game/script.js
  Games/Platform_Game/style.css
  README.md
  assets/images/Platform_Game.png
Labels: GSSoC23, level3

#697 [Enhancement] : Adding Search Bar functionality
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: GSSoC23, level2

#704 added flip card game
  Games/Flip_Card_Game/README.md
  Games/Flip_Card_Game/index.html
  Games/Flip_Card_Game/script.js
  Games/Flip_Card_Game/style.css
  README.md
  assets/images/Flip_Card_Game.png
Labels: GSSoC23, level3

#714 Update README.md
  README.md
Labels: GSSoC23, level1

#721 Fifteen Puzzle Game added
  Games/Fifteen_Puzzle_Game/README.md
  Games/Fifteen_Puzzle_Game/_config.yml
  Games/Fifteen_Puzzle_Game/art.jpg
  Games/Fifteen_Puzzle_Game/example.html
  Games/Fifteen_Puzzle_Game/fifteen_puzzle.js
  Games/Fifteen_Puzzle_Game/icon.jpg
  Games/Fifteen_Puzzle_Game/index.html
  README.md
  assets/images/fifteen_puzzle.png
Labels: GSSoC23, level3

#723 Added New game : Stack_Game
  Games/Stack_Game/README.md
  Games/Stack_Game/index.html
  Games/Stack_Game/styles.css
  README.md
  assets/images/Stack_Game.png
Labels: GSSoC23, level3

#791 block.io game added
  Games/Block.io/README.md
  Games/Block.io/game.css
  Games/Block.io/game.html
  Games/Block.io/game.js
  README.md
  assets/images/block.io.png
Labels: gssoc23, level3

#794 country guesser game added
  Games/Country_Guesser_Game/README.md
  Games/Country_Guesser_Game/index.html
  Games/Country_Guesser_Game/main.js
  README.md
  assets/images/country_guesser.png
Labels: gssoc23, level3

#796 Touch the ball added
  Games/Touch_The_Ball/README.md
  Games/Touch_The_Ball/click.wav
  Games/Touch_The_Ball/index.html
  Games/Touch_The_Ball/script.js
  Games/Touch_The_Ball/style.css
  README.md
  assets/images/touch_the_ball.png
Labels: gssoc23, level3

#847 dont die to ghosts added
  Games/Dont_Die_To_Ghosts/README.md
  Games/Dont_Die_To_Ghosts/img/160x160.png
  Games/Dont_Die_To_Ghosts/img/400x250.png
  Games/Dont_Die_To_Ghosts/img/assets.png
  Games/Dont_Die_To_Ghosts/index.html
  Games/Dont_Die_To_Ghosts/src/game.js
  Games/Dont_Die_To_Ghosts/src/index.html
  Games/Dont_Die_To_Ghosts/src/style.css
  README.md
  assets/images/dont_die_to_ghosts.png
Labels: gssoc23, level3

#852 packabunchas added
  Games/Packabunchas/README.md
  Games/Packabunchas/game.js
  Games/Packabunchas/index.html
  README.md
  assets/images/packabunchas.png
Labels: gssoc23, level3

#866 I had improved name input system and the game was continuing even it got finish, so I corrected that. And also improved its responsiveness.
  Games/Roll_Race/index.html
  Games/Roll_Race/index.js
  Games/Roll_Race/style.css
Labels: gssoc23, level1

#893 [ADD]: TRACK NOT FOUND GAME 👾
  Games/Track_Not_Found/1f441.svg
  Games/Track_Not_Found/1f4a5.svg
  Games/Track_Not_Found/1f4f7.svg
  Games/Track_Not_Found/1f682.svg
  Games/Track_Not_Found/1f9e8.svg
  Games/Track_Not_Found/README.md
  Games/Track_Not_Found/fs.svg
  Games/Track_Not_Found/index.html
  README.md
  assets/animations/Track_Not_Found.mp4
  assets/images/Track_Not_Found.jpg
Labels: gssoc23, level3

#729 Corona fighter added
  Games/Corona_Fighter/README.md
  Games/Corona_Fighter/assets/.gitignore
  Games/Corona_Fighter/assets/bg.jpg
  Games/Corona_Fighter/assets/doctor.png
  Games/Corona_Fighter/assets/hand-soap.png
  Games/Corona_Fighter/assets/india.png
  Games/Corona_Fighter/assets/virus.png
  Games/Corona_Fighter/assets/virus.svg
  Games/Corona_Fighter/index.html
  Games/Corona_Fighter/script.js
  README.md
  assets/images/corona_fighter.png
Labels: gssoc23, level3

#735 Planet game added
  Games/Planet_Game/README.md
  Games/Planet_Game/index.html
  Games/Planet_Game/script.js
  Games/Planet_Game/style.css
  README.md
  assets/images/planet_game.png
Labels: gssoc23, level3

#760 [ADD]: PACIFIC AIR BATTLE GAME (3D)
  Games/Pacific_Air_Battle/Framework.js
  Games/Pacific_Air_Battle/M4.js
  Games/Pacific_Air_Battle/README.md
  Games/Pacific_Air_Battle/WebGLUtils.js
  Games/Pacific_Air_Battle/ZzFXMicro.js
  Games/Pacific_Air_Battle/index.html
  Games/Pacific_Air_Battle/main.js
  Games/Pacific_Air_Battle/perlin.js
  README.md
  assets/images/Pacific_Air_Battle.jpg
Labels: gssoc23, level3

#762 [NEW GAME]: "DANTE" ADDED 💡
  Games/Dante/README.md
  Games/Dante/index.html
  README.md
  assets/images/Dante.jpg
Labels: gssoc23, level3

#768 [NEW GAME]: "WORLD OF EMOJIS" ADDED 💡
  Games/World_Of_Emojis/README.md
  Games/World_Of_Emojis/index.html
  Games/World_Of_Emojis/min.js
  README.md
  assets/images/World_Of_Emojis.jpg
Labels: gssoc23, level3

#788 pinball added
  Games/Pinball/README.md
  Games/Pinball/images/sprites-min.png
  Games/Pinball/images/sprites.png
  Games/Pinball/images/sprites.xcf
  Games/Pinball/index.html
  Games/Pinball/js/controls.js
  Games/Pinball/js/game.js
  Games/Pinball/js/main.js
  Games/Pinball/js/renderer.js
  Games/Pinball/js/soundManager.js
  Games/Pinball/js/world.js
  Games/Pinball/tools/pinballEditor.html
  README.md
  assets/images/pinball.png
Labels: gssoc23, level3

#822 [GSSoC'23]: [NEW GAME] - Color Matcher (PR for issue #363)
  Games/Color_Matcher/README.md
  Games/Color_Matcher/ScreenShots/Color_Matcher.png
  Games/Color_Matcher/ScreenShots/game_over.png
  Games/Color_Matcher/ScreenShots/you_win.png
  Games/Color_Matcher/css/game.css
  Games/Color_Matcher/css/main.css
  Games/Color_Matcher/index.html
  Games/Color_Matcher/js/colorHelper.js
  Games/Color_Matcher/js/script.js
  README.md
  assets/images/Color_Matcher.png
Labels: gssoc23, level3

#826 added catch me game
  Games/Catch_me_game/Readme.md
  Games/Catch_me_game/index.html
  Games/Catch_me_game/script.js
  Games/Catch_me_game/style.css
  README.md
  assets/images/Catch_me_game.png
Labels: gssoc23, level3

#872 Added Falling Blocks Game
  Games/Falling_Blocks/README.md
  Games/Falling_Blocks/index.html
  Games/Falling_Blocks/script.js
  Games/Falling_Blocks/style.css
  README.md
  assets/images/Falling_Blocks.png
Labels: gssoc23, level3

#876 Movie Guessing Game
  Games/Movie_Guessing_Game/README.md
  Games/Movie_Guessing_Game/index.html
  Games/Movie_Guessing_Game/script.js
  Games/Movie_Guessing_Game/style.css
  README.md
  assets/images/Movie_Guessing_Game.png
Labels: gssoc23, level3

#896 Added Wildcard_Bonanza
  Games/Wildcard_Bonanza/LICENSE
  Games/Wildcard_Bonanza/README.md
  Games/Wildcard_Bonanza/fonts/farray-webfont.woff
  Games/Wildcard_Bonanza/fonts/farray-webfont.woff2
  Games/Wildcard_Bonanza/fonts/montserrat-light-webfont.woff
  Games/Wildcard_Bonanza/fonts/montserrat-light-webfont.woff2
  Games/Wildcard_Bonanza/fonts/montserrat-regular-webfont.woff
  Games/Wildcard_Bonanza/fonts/montserrat-regular-webfont.woff2
  Games/Wildcard_Bonanza/images/01.png
  Games/Wildcard_Bonanza/images/02.png
  Games/Wildcard_Bonanza/images/computerFace1.png
  Games/Wildcard_Bonanza/images/computerFace2.png
  Games/Wildcard_Bonanza/images/computerFace3.png
  Games/Wildcard_Bonanza/images/computerFace4.png
  Games/Wildcard_Bonanza/images/computerWins.png
  Games/Wildcard_Bonanza/images/gameMap.png
  Games/Wildcard_Bonanza/images/gameTips.png
  Games/Wildcard_Bonanza/images/playerFace1.png
  Games/Wildcard_Bonanza/images/playerFace2.png
  Games/Wildcard_Bonanza/images/playerFace3.png
  Games/Wildcard_Bonanza/images/playerFace4.png
  Games/Wildcard_Bonanza/images/playerWins.png
  Games/Wildcard_Bonanza/images/thumbnail.png
  Games/Wildcard_Bonanza/index.html
  Games/Wildcard_Bonanza/juno.js
  Games/Wildcard_Bonanza/style.css
  README.md
  assets/images/Wildcard_Bonanza.png
Labels: gssoc23, level3

#899 [ADD]: THE LAST SPARTAN GAME 👾
  Games/The_Last_Spartan/README.md
  Games/The_Last_Spartan/index.html
  README.md
  assets/images/The_Last_Spartan.jpg
Labels: gssoc23, level3

#870 Add Bow Arrow Game
  Games/Bow_Arrow/README.md
  Games/Bow_Arrow/assets/images/Bow_Arrow.PNG
  Games/Bow_Arrow/game.html
  Games/Bow_Arrow/images/Screenshot1.PNG
  Games/Bow_Arrow/images/Screenshot2.PNG
  Games/Bow_Arrow/images/arrowl.png
  Games/Bow_Arrow/images/arrowr.png
  Games/Bow_Arrow/images/background.jpg
  Games/Bow_Arrow/images/bg2.gif
  Games/Bow_Arrow/images/birds.png
  Games/Bow_Arrow/images/birds2.png
  Games/Bow_Arrow/images/boom.png
  Games/Bow_Arrow/images/monsterl.png
  Games/Bow_Arrow/images/monsterr.png
  Games/Bow_Arrow/images/rulesimg.jpg
  Games/Bow_Arrow/images/rulesimginitial.jpg
  Games/Bow_Arrow/images/shooterl.png
  Games/Bow_Arrow/images/shooterla.png
  Games/Bow_Arrow/images/shooterr.png
  Games/Bow_Arrow/images/shooterra.png
  Games/Bow_Arrow/index.html
  Games/Bow_Arrow/myscript.js
  Games/Bow_Arrow/mystyle.css
  Games/Bow_Arrow/sounds/bird.wav
  Games/Bow_Arrow/sounds/main-theme.mp3
  Games/Bow_Arrow/sounds/smb_kick.wav
  Games/Bow_Arrow/sounds/smb_stomp.wav
  README.md
  assets/images/Bow_Arrow.PNG
  assets/images/piano.png
Labels: gssoc23, level3

#903 [ADD]: GAME NAMED "I WANT TO GOOGLE THE GAME" 👾
  Games/I_Want_To_Google_The_Game/README.md
  Games/I_Want_To_Google_The_Game/app.css
  Games/I_Want_To_Google_The_Game/app.js
  Games/I_Want_To_Google_The_Game/index.html
  Games/I_Want_To_Google_The_Game/manifest.json
  README.md
  assets/images/I_Want_To_Google_The_Game.jpg
Labels: gssoc23, level3

#907 space gun added
  Games/Space_Gun/README.md
  Games/Space_Gun/bigImage.jpeg
  Games/Space_Gun/css/style.css
  Games/Space_Gun/index.html
  Games/Space_Gun/js/bg.js
  Games/Space_Gun/js/collision.js
  Games/Space_Gun/js/game.js
  Games/Space_Gun/js/interface.js
  Games/Space_Gun/js/meteor.js
  Games/Space_Gun/js/music.js
  Games/Space_Gun/js/spaceship.js
  Games/Space_Gun/js/spaceship_favicon.js
  Games/Space_Gun/js/spaceship_fig.js
  Games/Space_Gun/js/weapon.js
  Games/Space_Gun/smallImage.png
  README.md
  assets/images/space_gun.png
Labels: under review

#909 space huggers added
  Games/Space_Huggers/README.md
  Games/Space_Huggers/app.js
  Games/Space_Huggers/appCharacters.js
  Games/Space_Huggers/appEffects.js
  Games/Space_Huggers/appLevel.js
  Games/Space_Huggers/appObjects.js
  Games/Space_Huggers/engine/build/build.bat
  Games/Space_Huggers/engine/build/build.html
  Games/Space_Huggers/engine/build/engineBuild.js
  Games/Space_Huggers/engine/build/index.html
  Games/Space_Huggers/engine/build/setupBuild.bat
  Games/Space_Huggers/engine/engine.js
  Games/Space_Huggers/engine/engineAudio.js
  Games/Space_Huggers/engine/engineDebug.js
  Games/Space_Huggers/engine/engineDraw.js
  Games/Space_Huggers/engine/engineInput.js
  Games/Space_Huggers/engine/engineObject.js
  Games/Space_Huggers/engine/engineParticle.js
  Games/Space_Huggers/engine/engineTileLayer.js
  Games/Space_Huggers/engine/engineUtil.js
  Games/Space_Huggers/engine/engineWebGL.js
  Games/Space_Huggers/favicon.ico
  Games/Space_Huggers/index.html
  Games/Space_Huggers/tiles.png
  README.md
  assets/images/space_huggers.png
Labels: gssoc23, level3

#911 spaceship escort added
  Games/Spaceship_Escort/README.md
  Games/Spaceship_Escort/img/SPRTexplosions.png
  Games/Spaceship_Escort/img/SPRTships.png
  Games/Spaceship_Escort/img/SPRTweapons.png
  Games/Spaceship_Escort/index.html
  README.md
  assets/images/spaceship_escort.png
Labels: gssoc23, level3

#913 [ADD]: SPACE DEFENCE GAME 👾
  Games/Space_Defence/README.md
  Games/Space_Defence/index.html
  README.md
  assets/images/Space_Defence.jpg
Labels: gssoc23, level3

#915 [ADD]: GLITCH BUSTER GAME 👾
  Games/Glitch_Buster/README.md
  Games/Glitch_Buster/index.html
  README.md
  assets/images/Glitch_Buster.jpg
Labels: gssoc23, level3

#920 Issue #423 3D-Box Game
  Games/3d_Box Game/README.md
  Games/3d_Box Game/apple-touch-icon.png
  Games/3d_Box Game/favicon-16x16.png
  Games/3d_Box Game/favicon-32x32.png
  Games/3d_Box Game/favicon.ico
  Games/3d_Box Game/index.html
  Games/3d_Box Game/screenshots/3d_Box.png
  Games/3d_Box Game/screenshots/ss2.JPG
  Games/3d_Box Game/screenshots/ss3.JPG
  Games/3d_Box Game/site.webmanifest
  Games/3d_Box Game/styles.css
  README.md
  assets/images/3d_Box.png
Labels: gssoc23, level3

#921 [ADD]: ESCAPE GAME 👾
  Games/Escape/README.md
  Games/Escape/index.html
  README.md
  assets/images/Escape.jpg
Labels: gssoc23, level3

#924 Add Retro_Dungeon_Puzzle game
  Games/Retro_Dungeon_Puzzle/README.md
  Games/Retro_Dungeon_Puzzle/assets/0.png
  Games/Retro_Dungeon_Puzzle/assets/1.png
  Games/Retro_Dungeon_Puzzle/assets/Screenshot from 2023-06-04 22-20-06.png
  Games/Retro_Dungeon_Puzzle/assets/Screenshot from 2023-06-04 22-20-09.png
  Games/Retro_Dungeon_Puzzle/index.html
  Games/Retro_Dungeon_Puzzle/style.css
  README.md
  assets/images/Retro_Dungeon_Puzzle.png
Labels: gssoc23, level3

#932 [ADD]: IMMUNITY COLLAPSE GAME 👾
  Games/Immunity_Collapse/README.md
  Games/Immunity_Collapse/index.html
  README.md
  assets/images/Immunity_Collapse.jpg
Labels: gssoc23, level3

#934 Hunt your card #105
  Games/Hunt_Your_Card/README.md
  Games/Hunt_Your_Card/images/AceSpades.png
  Games/Hunt_Your_Card/images/card-AceSpades.png
  Games/Hunt_Your_Card/images/card-JackClubs.png
  Games/Hunt_Your_Card/images/card-KingHearts.png
  Games/Hunt_Your_Card/images/card-QueenDiamonds.png
  Games/Hunt_Your_Card/images/card-back-Blue.png
  Games/Hunt_Your_Card/index.html
  Games/Hunt_Your_Card/script.js
  Games/Hunt_Your_Card/style.css
  README.md
  assets/images/Hunt_Your_Card.png
Labels: gssoc23, level3

#935 [ADD]: TENACITY GAME 👾
  Games/Tenacity/README.md
  Games/Tenacity/index.html
  README.md
  assets/images/Tenacity.jpg
Labels: gssoc23, level3

#937 [GSSoC'23] Emoji Puzzle Game Completed
  Games/Emoji_Puzzle_Game/README.md
  Games/Emoji_Puzzle_Game/favicon.ico
  Games/Emoji_Puzzle_Game/index.html
  Games/Emoji_Puzzle_Game/script.js
  Games/Emoji_Puzzle_Game/sounds/rightAnswer.mp3
  Games/Emoji_Puzzle_Game/sounds/wrongAnswer.mp3
  Games/Emoji_Puzzle_Game/style.css
  README.md
  assets/images/Emoji_Puzzle_Game.png
Labels: gssoc23, level3

#939 [ADD]: BACK TO SPACE GAME 👾
  Games/Back_To_Space/README.md
  Games/Back_To_Space/index.html
  README.md
  assets/images/Back_To_Space.jpg
Labels: gssoc23, level3

#946 [ADD]: SNOOZE GAME 👾
  Games/Snooze/README.md
  Games/Snooze/index.html
  README.md
  assets/images/Snooze.jpg
Labels: gssoc23, level3

#948 [ADD]: GALAXY RIDER GAME 👾
  Games/Galaxy_Rider/README.md
  Games/Galaxy_Rider/index.html
  README.md
  assets/images/Galaxy_Rider.jpg
Labels: gssoc23, level3

#951 Squared Lines (#950)
  Games/Squared Lines/README.md
  Games/Squared Lines/Squared Lines.png
  Games/Squared Lines/favicon.ico
  Games/Squared Lines/game.js
  Games/Squared Lines/index.html
  README.md
  assets/images/Squared Lines.png
Labels: gssoc23, level3

#953 space_War added
  Games/Space_War/README.md
  Games/Space_War/index.html
  Games/Space_War/js/classes/Enemy.js
  Games/Space_War/js/classes/Particle.js
  Games/Space_War/js/classes/Player.js
  Games/Space_War/js/classes/Projectile.js
  Games/Space_War/js/eventListeners.js
  Games/Space_War/js/index.js
  README.md
  assets/images/space_war.png
Labels: gssoc23, level3

#957 Sciara of Colors
  Games/Sciarra_Of_Colors/README.md
  Games/Sciarra_Of_Colors/css/main.css
  Games/Sciarra_Of_Colors/css/main.min.css
  Games/Sciarra_Of_Colors/index.html
  Games/Sciarra_Of_Colors/js/game.js
  Games/Sciarra_Of_Colors/js/game.min.js
  README.md
  assets/images/Sciarra_Of_Colors.png
Labels: gssoc23, level3

#958 junojs added
  Games/JunoJs/README.md
  Games/JunoJs/img/160x160.png
  Games/JunoJs/img/400x250.png
  Games/JunoJs/index-uncompress.html
  Games/JunoJs/index.html
  Games/JunoJs/obj/boss.js
  Games/JunoJs/obj/boss.mtl
  Games/JunoJs/obj/boss.obj
  Games/JunoJs/obj/cube.js
  Games/JunoJs/obj/cube.mtl
  Games/JunoJs/obj/cube.obj
  Games/JunoJs/obj/logo.js
  Games/JunoJs/obj/logo.mtl
  Games/JunoJs/obj/logo.obj
  Games/JunoJs/obj/shield.js
  Games/JunoJs/obj/shield.mtl
  Games/JunoJs/obj/shield.obj
  Games/JunoJs/obj/up.js
  Games/JunoJs/obj/up.mtl
  Games/JunoJs/obj/up.obj
  Games/JunoJs/obj/wing.js
  Games/JunoJs/obj/wing.mtl
  Games/JunoJs/obj/wing.obj
  Games/JunoJs/tools/obj_to_js.php
  README.md
  assets/images/junojs.png
Labels: under review

#959 fall down added
  Games/Fall_Down/README.md
  Games/Fall_Down/img/Big(400X250).png
  Games/Fall_Down/img/Small(160X160).png
  Games/Fall_Down/img/original1.png
  Games/Fall_Down/img/original2.png
  Games/Fall_Down/index.html
  Games/Fall_Down/index.min.html
  Games/Fall_Down/sound/play.js
  Games/Fall_Down/sound/zzfx.js
  Games/Fall_Down/sound/zzfxM.js
  Games/Fall_Down/utils/basic.js
  Games/Fall_Down/utils/draw.js
  Games/Fall_Down/utils/main.js
  Games/Fall_Down/utils/ves.js
  README.md
  assets/images/falldown.png
Labels: gssoc23, level3

#969 [ADD]: CABLE MAZE GAME 👾
  Games/Cable_Maze/README.md
  Games/Cable_Maze/index.html
  Games/Cable_Maze/main.js
  README.md
  assets/images/Cable_Maze.jpg
Labels: gssoc23, level3

#971 [ADD]: SPACEDUCTS GAME 👾
  Games/Spaceducts/README.md
  Games/Spaceducts/aframe.min.js
  Games/Spaceducts/index.html
  README.md
  assets/images/Spaceducts.jpg
Labels: gssoc23, level3

#973 [ADD]: ZURBO GAME 👾
  Games/Zurbo/README.md
  Games/Zurbo/index.html
  README.md
  assets/images/Zurbo.jpg
Labels: gssoc23, level3

#917 [ADD]: FREE BIRD GAME 👾
  Games/Free_Bird/README.md
  Games/Free_Bird/b.png
  Games/Free_Bird/favicon.ico
  Games/Free_Bird/index.html
  Games/Free_Bird/main.js
  Games/Free_Bird/manifest.appcache
  Games/Free_Bird/t.png
  README.md
  assets/images/Free_Bird.jpg
Labels: gssoc23, level3

#1090 Maximise Boxes
  Games/MaximiseBoxes/README.md
  Games/MaximiseBoxes/assets/MaximiseBoxes.mp4
  Games/MaximiseBoxes/assets/MaximiseBoxes.png
  Games/MaximiseBoxes/index.html
  Games/MaximiseBoxes/js/board.js
  Games/MaximiseBoxes/js/box.js
  Games/MaximiseBoxes/js/edge.js
  Games/MaximiseBoxes/js/game.js
  Games/MaximiseBoxes/style.css
  README.md
  assets/images/MaximiseBoxes.png
Labels: gssoc23, level3

#992 Added Slider Puzzle Game
  Games/Slide_Puzzle/README.md
  Games/Slide_Puzzle/images/1.jpg
  Games/Slide_Puzzle/images/10.jpg
  Games/Slide_Puzzle/images/2.jpg
  Games/Slide_Puzzle/images/3.jpg
  Games/Slide_Puzzle/images/4.jpg
  Games/Slide_Puzzle/images/5.jpg
  Games/Slide_Puzzle/images/6.jpg
  Games/Slide_Puzzle/images/7.jpg
  Games/Slide_Puzzle/images/8.jpg
  Games/Slide_Puzzle/images/9.jpg
  Games/Slide_Puzzle/images/background.webp
  Games/Slide_Puzzle/images/logo.png
  Games/Slide_Puzzle/index.html
  Games/Slide_Puzzle/script.js
  Games/Slide_Puzzle/style.css
  README.md
  assets/images/Slide_Puzzle.png
Labels: under review

#1001 diamond run added
  Games/Diamond_Run/README.md
  Games/Diamond_Run/images/sprites.png
  Games/Diamond_Run/images/sprites.xcf
  Games/Diamond_Run/images/sprites32-min.png
  Games/Diamond_Run/index.html
  Games/Diamond_Run/js/controls.js
  Games/Diamond_Run/js/game.js
  Games/Diamond_Run/js/levelLoader.js
  Games/Diamond_Run/js/main.js
  Games/Diamond_Run/js/menuDriver.js
  Games/Diamond_Run/js/renderer.js
  Games/Diamond_Run/js/world.js
  README.md
  assets/images/diamond_run.png
Labels: under review

#1003 [ADD]: EVERYONES SKY GAME 👾
  Games/Everyones_Sky/README.md
  Games/Everyones_Sky/index.html
  README.md
  assets/images/Everyones_Sky.jpg
Labels: under review

#1005 line of fire added
  Games/Line_Of_Fire/README.md
  Games/Line_Of_Fire/images/crate16.png
  Games/Line_Of_Fire/index.html
  Games/Line_Of_Fire/js/aiplayer.js
  Games/Line_Of_Fire/js/babylon.custom.js
  Games/Line_Of_Fire/js/controls.js
  Games/Line_Of_Fire/js/game.js
  Games/Line_Of_Fire/js/main.js
  Games/Line_Of_Fire/js/persistentData.js
  Games/Line_Of_Fire/js/renderer.js
  Games/Line_Of_Fire/js/world.js
  README.md
  assets/images/line_of_fire.png
Labels: under review

#1007 [ADD]: 1024 MOVES GAME 👾
  Games/1024_Moves/README.md
  Games/1024_Moves/crate.png
  Games/1024_Moves/index.html
  Games/1024_Moves/lost.js
  README.md
  assets/images/1024_Moves.jpg
Labels: under review

#1010 [ADD]: SAVE THE FOREST GAME 👾
  Games/Save_The_Forest/README.md
  Games/Save_The_Forest/game.css
  Games/Save_The_Forest/game.js
  Games/Save_The_Forest/index.html
  README.md
  assets/images/Save_The_Forest.jpg
Labels: under review

#1020 Added Dragon World Game (Issue: #926)(GSSOC '23)
  Games/Dragon_World_Game/README.md
  Games/Dragon_World_Game/assets/cover.png
  Games/Dragon_World_Game/assets/dragon.png
  Games/Dragon_World_Game/assets/dragon_world.png
  Games/Dragon_World_Game/assets/obstacle.png
  Games/Dragon_World_Game/index.html
  Games/Dragon_World_Game/script.js
  Games/Dragon_World_Game/style.css
  README.md
  assets/images/dragon_world.png
Labels: under review

#1024 add DuckHunt game
  Games/DuckHunt/README.md
  Games/DuckHunt/assets/Screenshot from 2023-06-04 22-46-54.png
  Games/DuckHunt/assets/Screenshot from 2023-06-04 22-47-10.png
  Games/DuckHunt/assets/Screenshot from 2023-06-04 22-47-14.png
  Games/DuckHunt/assets/Screenshot from 2023-06-04 22-47-18.png
  Games/DuckHunt/index.html
  Games/DuckHunt/style.css
  README.md
  assets/images/DuckHunt.png
Labels: under review

#1027 add Plankman game
  Games/Plankman/README.md
  Games/Plankman/assets/Screenshot from 2023-06-05 02-33-17.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-33-22.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-33-52.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-33-58.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-34-03.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-34-07.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-34-10.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-34-29.png
  Games/Plankman/assets/Screenshot from 2023-06-05 02-34-54.png
  Games/Plankman/index.html
  Games/Plankman/style.css
  README.md
  assets/images/Plankman.png
Labels: under review

#1030 hold the cloud added
  Games/Hold_The_Cloud/README.md
  Games/Hold_The_Cloud/game.js
  Games/Hold_The_Cloud/images/bg.gif
  Games/Hold_The_Cloud/images/cloud.png
  Games/Hold_The_Cloud/index.html
  Games/Hold_The_Cloud/style.css
  README.md
  assets/images/hold_the_cloud.png
Labels: under review

#1031 labyrinth added
  Games/Labyrinth/README.md
  Games/Labyrinth/assets/die.png
  Games/Labyrinth/assets/enemy0.png
  Games/Labyrinth/assets/enemy1.png
  Games/Labyrinth/assets/key.png
  Games/Labyrinth/assets/player.png
  Games/Labyrinth/assets/player0.png
  Games/Labyrinth/assets/player1.png
  Games/Labyrinth/assets/wall.png
  Games/Labyrinth/css/style.css
  Games/Labyrinth/index.html
  Games/Labyrinth/js/game.js
  README.md
  assets/images/labyrinth.png
Labels: under review

#1041 [ADD]: RIP GAME 👾
  Games/RIP/README.md
  Games/RIP/index.html
  README.md
  assets/images/RIP.jpg
Labels: under review

#1043 [ADD]: RISKY NAV GAME 👾
  Games/Risky_Nav/Char.js
  Games/Risky_Nav/Keys.js
  Games/Risky_Nav/PathFinding.js
  Games/Risky_Nav/README.md
  Games/Risky_Nav/assets/monster.ase
  Games/Risky_Nav/assets/monster.png
  Games/Risky_Nav/assets/player.ase
  Games/Risky_Nav/assets/player.png
  Games/Risky_Nav/assets/various.ase
  Games/Risky_Nav/assets/various.png
  Games/Risky_Nav/index.html
  Games/Risky_Nav/init.js
  Games/Risky_Nav/kontra.js
  README.md
  assets/images/Risky_Nav.jpg
Labels: under review

#1044 pixels from space added
  Games/Pixels_From_Space/README.md
  Games/Pixels_From_Space/app.js
  Games/Pixels_From_Space/app.min.js
  Games/Pixels_From_Space/assets/crt.png
  Games/Pixels_From_Space/assets/crt_big.png
  Games/Pixels_From_Space/index.html
  README.md
  assets/images/pixels_from_space.png
Labels: under review

#1045 poker dice added
  Games/Poker_Dice/README.md
  Games/Poker_Dice/build.xml
  Games/Poker_Dice/dist/index.html
  Games/Poker_Dice/dist/script.js
  Games/Poker_Dice/dist/style-l.css
  Games/Poker_Dice/dist/style-m.css
  Games/Poker_Dice/dist/style.css
  Games/Poker_Dice/index.html
  Games/Poker_Dice/script.js
  Games/Poker_Dice/style-l.css
  Games/Poker_Dice/style-m.css
  Games/Poker_Dice/style.css
  README.md
  assets/images/poker.png
Labels: under review

#1046 unlock the lock added
  Games/Unlock_The_Lock/README.md
  Games/Unlock_The_Lock/index.html
  Games/Unlock_The_Lock/zepto.min.js
  README.md
  assets/images/unlock_the_lock.png
Labels: under review

#1047 [ADD]: GNOMEDOM GAME 👾
  Games/Gnomedom/README.md
  Games/Gnomedom/build/index.min.js
  Games/Gnomedom/images/campfire.gif
  Games/Gnomedom/images/girl-arms-around-knees.gif
  Games/Gnomedom/images/ground.gif
  Games/Gnomedom/images/horse-run.gif
  Games/Gnomedom/images/horse.gif
  Games/Gnomedom/index.html
  Games/Gnomedom/styles/app.css
  Games/Gnomedom/styles/base.css
  Games/Gnomedom/styles/coin.css
  Games/Gnomedom/styles/horse.css
  Games/Gnomedom/styles/world.css
  README.md
  assets/images/Gnomedom.jpg
Labels: under review

#1053 [ADD]: LOST IN THE MAZE 3D GAME 👾
  Games/Lost_In_The_Maze_3D/README.md
  Games/Lost_In_The_Maze_3D/game.js
  Games/Lost_In_The_Maze_3D/gunsigth.png
  Games/Lost_In_The_Maze_3D/index.html
  README.md
  assets/images/Lost_In_The_Maze_3D.jpg
Labels: under review

#1055 Adding pong ball
  Games/Pong_Ball/README.md
  Games/Pong_Ball/index1.html
  Games/Pong_Ball/script1.js
  Games/Pong_Ball/style1.css
  README.md
  assets/images/PONG_BALL.png
  index.html
Labels: under review

#1056 added game
  Games/Projectile_Motion_Game/README.md
  Games/Projectile_Motion_Game/celebrate.html
  Games/Projectile_Motion_Game/dot.png
  Games/Projectile_Motion_Game/fail.html
  Games/Projectile_Motion_Game/index.html
  Games/Projectile_Motion_Game/play.html
  README.md
  assets/images/Projectile_Motion_Game.png
Labels: under review

#1057 swift added
  Games/Swift/README.md
  Games/Swift/index.html
  Games/Swift/swift.js
  README.md
  assets/images/swift.png
Labels: gssoc23, level3

#1059 spacepi added
  Games/Spacepi/README.md
  Games/Spacepi/index.html
  Games/Spacepi/source.html
  README.md
  assets/images/spacepi.png
Labels: gssoc23, level3

#1064 destroyer added
  Games/Destroyer/README.md
  Games/Destroyer/css/style.css
  Games/Destroyer/css/style.min.css
  Games/Destroyer/img/enemy.gif
  Games/Destroyer/img/pattern.png
  Games/Destroyer/img/ship.gif
  Games/Destroyer/index.html
  Games/Destroyer/js/game.js
  Games/Destroyer/js/game.mini.js
  README.md
  assets/images/destroyer.png
Labels: gssoc23, level3

#1072 terror seventy added
  Games/Terror_Seventy/README.md
  Games/Terror_Seventy/index.html
  Games/Terror_Seventy/package/70seconds.zip
  Games/Terror_Seventy/package/screenshot_big_400x250.png
  Games/Terror_Seventy/package/screenshot_small_160x160.png
  Games/Terror_Seventy/src/70sec.css
  Games/Terror_Seventy/src/70sec.js
  Games/Terror_Seventy/src/70sec.min.css
  Games/Terror_Seventy/src/70sec.min.js
  Games/Terror_Seventy/src/prefixfree.min.js
  Games/Terror_Seventy/svg/capsule.svg
  Games/Terror_Seventy/svg/friction.svg
  Games/Terror_Seventy/svg/keys.svg
  Games/Terror_Seventy/svg/parachute.svg
  Games/Terror_Seventy/svg/parachute_btn.svg
  Games/Terror_Seventy/svg/rockets.svg
  Games/Terror_Seventy/svg/rover.svg
  Games/Terror_Seventy/svg/separation_btn.svg
  Games/Terror_Seventy/svg/shield.svg
  Games/Terror_Seventy/svg/shield_btn.svg
  Games/Terror_Seventy/svg/skycrane_hd.svg
  Games/Terror_Seventy/svg/skycrane_sd.svg
  Games/Terror_Seventy/svg/stars.svg
  Games/Terror_Seventy/svg/surface.svg
  README.md
  assets/images/terror_seventy.png
Labels: gssoc23, level3

#1128 humming added
  Games/Humming/README.md
  Games/Humming/dist/hum.min.js
  Games/Humming/dist/index.html
  Games/Humming/grunt.js
  Games/Humming/index.html
  Games/Humming/js/app/Bird.js
  Games/Humming/js/app/Flower.js
  Games/Humming/js/app/Game.js
  Games/Humming/js/app/UI.js
  Games/Humming/js/lib/Utils.js
  Games/Humming/js/vendor/requestAnimationFrame.polyfill.js
  README.md
  assets/images/humming.png
Labels: gssoc23, level3

#1125 added new game
  Games/Word_search_puzzle/README.md
  Games/Word_search_puzzle/image.png
  Games/Word_search_puzzle/index.html
  Games/Word_search_puzzle/wordsearch.js
  README.md
  assets/images/Word_search_puzzle.png
Labels: gssoc23, level3

#1081 ballarena added
  Games/Ballarena/README.md
  Games/Ballarena/advancedRenderer.js
  Games/Ballarena/ball.js
  Games/Ballarena/brick.js
  Games/Ballarena/brickPath.js
  Games/Ballarena/collisionHandler.js
  Games/Ballarena/controls.js
  Games/Ballarena/floater.js
  Games/Ballarena/game.js
  Games/Ballarena/index.html
  Games/Ballarena/level.js
  Games/Ballarena/menuDriver.js
  Games/Ballarena/player.js
  Games/Ballarena/soundManager.js
  README.md
  assets/images/ballarena.png
Labels: gssoc23, level3

#976 [ADD]: BEYONDER GAME 👾
  Games/Beyonder/README.md
  Games/Beyonder/index.html
  README.md
  assets/images/Beyonder.jpg
Labels: gssoc23, level3

#1083 shpere added
  Games/Shpere/README.md
  Games/Shpere/index.html
  Games/Shpere/instructions.svg
  Games/Shpere/shpere.js
  Games/Shpere/shpere.min.js
  README.md
  assets/images/shpere.png
Labels: gssoc23, level3

#1091 Short Circuit (#1088)
  Games/Short Circuit/160x160.png
  Games/Short Circuit/README.md
  Games/Short Circuit/Short Circuit.png
  Games/Short Circuit/index.html
  Games/Short Circuit/shortcircuit.js
  README.md
  assets/images/Short Circuit.png
Labels: gssoc23, level3

#1092 johnny smiter added
  Games/Johnny_Smiter/README.md
  Games/Johnny_Smiter/build/all-manualmin.js
  Games/Johnny_Smiter/build/entry.zip
  Games/Johnny_Smiter/build/index.html
  Games/Johnny_Smiter/index.html
  Games/Johnny_Smiter/src/glrenderer.js
  Games/Johnny_Smiter/src/main.js
  Games/Johnny_Smiter/src/procTrack.js
  Games/Johnny_Smiter/src/textures.js
  Games/Johnny_Smiter/src/tree.js
  README.md
  assets/images/johnny_smiter.png
Labels: under review

#1093 rectangular added
  Games/Rectangular/README.md
  Games/Rectangular/index.html
  Games/Rectangular/js/Bonus.js
  Games/Rectangular/js/Mine.js
  Games/Rectangular/js/Player.js
  Games/Rectangular/js/Square.js
  Games/Rectangular/js/input.js
  Games/Rectangular/js/main.js
  README.md
  assets/images/rectangular.png
Labels: under review

#1096 canon defense added
  Games/Canon_Defense/.c9revisions/bullet.js.c9save
  Games/Canon_Defense/.c9revisions/enemy.js.c9save
  Games/Canon_Defense/.c9revisions/game.js.c9save
  Games/Canon_Defense/.c9revisions/index.html.c9save
  Games/Canon_Defense/.c9revisions/main.js.c9save
  Games/Canon_Defense/.c9revisions/main.js.c9save.h668bvvg.tmp
  Games/Canon_Defense/.c9revisions/raf.js.c9save
  Games/Canon_Defense/.c9revisions/tower.js.c9save
  Games/Canon_Defense/.c9revisions/viewfinder.js.c9save
  Games/Canon_Defense/README.md
  Games/Canon_Defense/bullet.js
  Games/Canon_Defense/enemy.js
  Games/Canon_Defense/enemy.png
  Games/Canon_Defense/game.js
  Games/Canon_Defense/index.html
  Games/Canon_Defense/main.js
  Games/Canon_Defense/raf.js
  Games/Canon_Defense/sheet_1.png
  Games/Canon_Defense/tower.js
  Games/Canon_Defense/viewfinder.js
  README.md
  assets/images/canon_defense.png
Labels: under review

#1103 trashem added
  Games/Trashem/README.md
  Games/Trashem/index.html
  Games/Trashem/script.js
  Games/Trashem/trashem-bigimage.jpg
  Games/Trashem/trashem-smallimage.jpg
  README.md
  assets/images/trashem.png
Labels: gssoc23, level3

#1097 [ADD]: GET THE PIGEON GAME 👾
  Games/Get_The_Pigeon/README.md
  Games/Get_The_Pigeon/aabb.js
  Games/Get_The_Pigeon/balloon.js
  Games/Get_The_Pigeon/boid.js
  Games/Get_The_Pigeon/cloud.js
  Games/Get_The_Pigeon/drago.js
  Games/Get_The_Pigeon/game.js
  Games/Get_The_Pigeon/helpers.js
  Games/Get_The_Pigeon/index.html
  Games/Get_The_Pigeon/plane.js
  README.md
  assets/images/Get_The_Pigeon.jpg
Labels: gssoc23, level3

#1109 uxu added
  Games/Uxu/README.md
  Games/Uxu/bomb.png
  Games/Uxu/charac.png
  Games/Uxu/charac2.png
  Games/Uxu/cloud.png
  Games/Uxu/explo0.png
  Games/Uxu/explo1.png
  Games/Uxu/explo2.png
  Games/Uxu/explo3.png
  Games/Uxu/explo4.png
  Games/Uxu/game.js
  Games/Uxu/index.html
  Games/Uxu/key.png
  Games/Uxu/montagne_1.png
  Games/Uxu/mount.png
  Games/Uxu/nuage_1.png
  Games/Uxu/tower.png
  README.md
  assets/images/uxu.png
Labels: under review

#1098 [ADD]: SOUL JUMPER GAME 👾
  Games/Soul_Jumper/README.md
  Games/Soul_Jumper/atlas.png
  Games/Soul_Jumper/game.min.js
  Games/Soul_Jumper/index.html
  README.md
  assets/images/Soul_Jumper.jpg
Labels: gssoc23, level3

#1105 [ADD]: INFERNAL THRONE GAME 👾
  Games/Infernal_Throne/README.md
  Games/Infernal_Throne/index.html
  README.md
  assets/images/Infernal_Throne.jpg
Labels: gssoc23, level3

#1110 [ADD]: DEAD AGAIN GAME 👾
  Games/Dead_Again/README.md
  Games/Dead_Again/index.html
  README.md
  assets/images/Dead_Again.jpg
Labels: gssoc23, level3

#1114 [ADD]: NORMAN THE NECROMANCER GAME 👾
  Games/Norman_The_Necromancer/README.md
  Games/Norman_The_Necromancer/index.html
  Games/Norman_The_Necromancer/sprites.png
  README.md
  assets/images/Norman_The_Necromancer.jpg
Labels: gssoc23, level3

#1116 shape blocks added
  Games/Shape_Blocks/13kgame.min.js
  Games/Shape_Blocks/README.md
  Games/Shape_Blocks/index.html
  Games/Shape_Blocks/main.css
  Games/Shape_Blocks/src/_first.js
  Games/Shape_Blocks/src/_last.js
  Games/Shape_Blocks/src/class/Draggable.js
  Games/Shape_Blocks/src/class/Shape.js
  Games/Shape_Blocks/src/class/Stage.js
  Games/Shape_Blocks/src/class/Worldgrid.js
  Games/Shape_Blocks/src/lib/Helper.js
  Games/Shape_Blocks/src/main.js
  Games/Shape_Blocks/tile.jpg
  Games/Shape_Blocks/tile2.jpg
  README.md
  assets/images/shape_block.png
Labels: gssoc23, level3

#1383 Goal_Rush Added
  Games/Goal_Rush/Goal_Rush.png
  Games/Goal_Rush/LICENSE
  Games/Goal_Rush/README.md
  Games/Goal_Rush/css/style.css
  Games/Goal_Rush/img/01.png
  Games/Goal_Rush/img/02.png
  Games/Goal_Rush/img/03.png
  Games/Goal_Rush/img/04.png
  Games/Goal_Rush/img/awayPlayer.png
  Games/Goal_Rush/img/background.png
  Games/Goal_Rush/img/help.png
  Games/Goal_Rush/img/homePlayer.png
  Games/Goal_Rush/img/pitch3.png
  Games/Goal_Rush/img/splash.png
  Games/Goal_Rush/index.html
  Games/Goal_Rush/js/SAT.js
  Games/Goal_Rush/js/awayPlayer.png
  Games/Goal_Rush/js/football.js
  Games/Goal_Rush/js/homePlayer.png
  README.md
  assets/images/Goal_Rush.png
Labels: gssoc23, level3

#1095 Chess
  Games/CHESS/Chess.css
  Games/CHESS/Chess.js
  Games/CHESS/README.md
  Games/CHESS/index.html
  README.md
  assets/images/Bbishop.png
  assets/images/Bking.png
  assets/images/Bknight.png
  assets/images/Bpawn.png
  assets/images/Bqueen.png
  assets/images/Brook.png
  assets/images/Chess.jpg
  assets/images/Wking.png
  assets/images/Wknight.png
  assets/images/Wpawn.png
  assets/images/Wqueen.png
  assets/images/Wrook.png
Labels: under review

#1099 [ADD]: CHARON JR GAME 👾
  Games/Charon_Jr/README.md
  Games/Charon_Jr/index.html
  README.md
  assets/images/Charon_Jr.jpg
Labels: gssoc23, level3, under review

#1142 Background of Snake_Game
  Games/Snake_Game/index.html
  Games/Snake_Game/index.js
  Games/Snake_Game/style.css
Labels: Ready to merge

#1183 added ohflip game
  Games/oh_flip/README.md
  Games/oh_flip/index.html
  Games/oh_flip/index_Submission.html
  Games/oh_flip/index_Website.html
  Games/oh_flip/main.js
  Games/oh_flip/main.min.js
  README.md
  assets/images/oh_flip.png
Labels: under review

#1499 LOSSST (#1368)
  Games/LOSSST/LOSSST.png
  Games/LOSSST/README.md
  Games/LOSSST/airconsole/controller.html
  Games/LOSSST/airconsole/controller.js
  Games/LOSSST/airconsole/game.html
  Games/LOSSST/airconsole/screen.html
  Games/LOSSST/airconsole/screen.js
  Games/LOSSST/credits.html
  Games/LOSSST/dump all html.html
  Games/LOSSST/index.html
  Games/LOSSST/lossstlevels.html
  Games/LOSSST/min.html
  Games/LOSSST/min/index.html
  Games/LOSSST/old_editor/editor.html
  Games/LOSSST/old_editor/gameplay.js
  Games/LOSSST/old_editor/init.js
  Games/LOSSST/old_editor/snake.css
  Games/LOSSST/zic.html
  Games/LOSSST/zic2.html
  README.md
  assets/images/LOSSST.png
Labels: under review

#1502 HangMan!!
  Games/HangMan/README.md
  Games/HangMan/index.html
  Games/HangMan/script.js
  Games/HangMan/styles.css
  README.md
  assets/images/HangMan.png
Labels: under review

#1160 bad luck brian added
  Games/Bad_Luck_Brian/README.md
  Games/Bad_Luck_Brian/css/desktop.css
  Games/Bad_Luck_Brian/css/style.css
  Games/Bad_Luck_Brian/index.html
  Games/Bad_Luck_Brian/js/blb.js
  Games/Bad_Luck_Brian/js/blb.min.js
  README.md
  assets/images/bad_luck_brian.png
Labels: gssoc23, level3

#1158 bad depot added
  Games/Bad_Depot/README.md
  Games/Bad_Depot/baddepot.js
  Games/Bad_Depot/baddepot.min.js
  Games/Bad_Depot/index.html
  Games/Bad_Depot/style.css
  README.md
  assets/images/bad_Depot.png
Labels: gssoc23, level3

#1156 Angry_Boars added
  Games/Angry_Boars/README.md
  Games/Angry_Boars/cat.mp3
  Games/Angry_Boars/game.html
  Games/Angry_Boars/index.html
  Games/Angry_Boars/script.js
  Games/Angry_Boars/sprite.png
  README.md
  assets/images/Angry_boars.png
Labels: gssoc23, level3

#1153 Achluophobia added
  Games/Achluophobia/README.md
  Games/Achluophobia/breath.ogg
  Games/Achluophobia/index.html
  Games/Achluophobia/js/breathing.js
  Games/Achluophobia/js/full.game.js
  Games/Achluophobia/js/full.game.min.js
  Games/Achluophobia/js/game.js
  Games/Achluophobia/js/house.js
  Games/Achluophobia/js/key.js
  Games/Achluophobia/js/math_helper.js
  Games/Achluophobia/js/player.js
  Games/Achluophobia/js/shadow_renderer.js
  README.md
  assets/images/Achluophobia.png
Labels: gssoc23, level3

#1130 timber terry
  Games/Timber_Terry/160x160.jpg
  Games/Timber_Terry/400x250.jpg
  Games/Timber_Terry/README.md
  Games/Timber_Terry/game.js
  Games/Timber_Terry/index.html
  Games/Timber_Terry/min/index.html
  Games/Timber_Terry/min/prefixfree.js
  Games/Timber_Terry/prefixfree.js
  README.md
  assets/images/timber_terry.png
Labels: gssoc23, level3

#1127 earth destroyer added
  Games/Earth_Destroyer/README.md
  Games/Earth_Destroyer/ed.min.js
  Games/Earth_Destroyer/images/gameover.png
  Games/Earth_Destroyer/images/loader.gif
  Games/Earth_Destroyer/images/sprite.png
  Games/Earth_Destroyer/index.html
  README.md
  assets/images/earth_destroyer.png
Labels: gssoc23, level3, under review

#1122 [ADD]: LONELY PHANTOM GAME 👾
  Games/Lonely_Phantom/README.md
  Games/Lonely_Phantom/index.html
  README.md
  assets/images/Lonely_Phantom.jpg
Labels: gssoc23, level3

#1102 [ADD]: GHOST SURF GAME 👾
  Games/Ghost_Surf/README.md
  Games/Ghost_Surf/index.html
  README.md
  assets/images/Ghost_Surf.jpg
Labels: gssoc23, level3, under review

#1104 sucker added
  Games/Sucker/README.md
  Games/Sucker/index.html
  Games/Sucker/sucker.js
  README.md
  assets/images/sucker.png
Labels: gssoc23, level3, under review

#1112 sorades added
  Games/Sorades/README.md
  Games/Sorades/index.html
  Games/Sorades/jsfxr.js
  Games/Sorades/jsfxr.min.js
  Games/Sorades/sorades-13k.js
  Games/Sorades/starship-sorades.jpg
  README.md
  assets/images/sorades.png
Labels: under review

#1117 [ADD]: GAME NAMED "THIRTEEN" 👾
  Games/Thirteen/README.md
  Games/Thirteen/c.js
  Games/Thirteen/index.html
  Games/Thirteen/s.js
  README.md
  assets/images/Thirteen.jpg
Labels: under review

#1118 [ADD]: THE RAISING FIGHTING SPIRITS GAME 👾
  Games/The_Raising_Fighting_Spirits/README.md
  Games/The_Raising_Fighting_Spirits/index.html
  Games/The_Raising_Fighting_Spirits/main.js
  README.md
  assets/images/The_Raising_Fighting_Spirits.jpg
Labels: gssoc23, level3

#1283 Enhanced scoring section Chrome_Dinosaur_Game
  Games/Chrome_Dinosaur_Game/script.js
  assets/images/Chrome_dinosaur_runner.png
Labels: gssoc23, level2

#1513 [GSSoC'23] Music Guess Game Completed
  Games/Music_Guess_Game/README.md
  Games/Music_Guess_Game/images/Music_Guess_Game.png
  Games/Music_Guess_Game/images/Music_Guess_Game1.png
  Games/Music_Guess_Game/images/PlayingCaste.gif
  Games/Music_Guess_Game/index.html
  Games/Music_Guess_Game/script.js
  Games/Music_Guess_Game/songs/Aafat - Liger.mp3
  Games/Music_Guess_Game/songs/Aapke Pyaar Mein Hum.mp3
  Games/Music_Guess_Game/songs/Apna Bna Le.mp3
  Games/Music_Guess_Game/songs/Apni Toh Jaise Taise.mp3
  Games/Music_Guess_Game/songs/Ban Meri Rani.mp3
  Games/Music_Guess_Game/songs/Bholi Si Surat.mp3
  Games/Music_Guess_Game/songs/Chand Chuppa.mp3
  Games/Music_Guess_Game/songs/Chorbazari.mp3
  Games/Music_Guess_Game/songs/Chupke Chupke.mp3
  Games/Music_Guess_Game/songs/Current Laga Re.mp3
  Games/Music_Guess_Game/songs/Daru Badnam.mp3
  Games/Music_Guess_Game/songs/Girl I Need You.mp3
  Games/Music_Guess_Game/songs/Jeda Nasha Nasha.mp3
  Games/Music_Guess_Game/songs/Jhoome Jo Pathan.mp3
  Games/Music_Guess_Game/songs/Kaun Tujhe.mp3
  Games/Music_Guess_Game/songs/Kitna Haseen Chehra.mp3
  Games/Music_Guess_Game/songs/Maarkhayega.mp3
  Games/Music_Guess_Game/songs/Mast Nazron Se Allah Bachaye.mp3
  Games/Music_Guess_Game/songs/Nacho Nacho.mp3
  Games/Music_Guess_Game/songs/Neele Neele Amber.mp3
  Games/Music_Guess_Game/songs/O Saki Saki.mp3
  Games/Music_Guess_Game/songs/Om Deva Deva.mp3
  Games/Music_Guess_Game/songs/Ramaiya Vastavaiya.mp3
  Games/Music_Guess_Game/songs/Thumkeswari.mp3
  Games/Music_Guess_Game/songs/Tujh Me Rab Dikhta.mp3
  Games/Music_Guess_Game/songs/Zara Tasveer Se Tu.mp3
  Games/Music_Guess_Game/sounds/gameOver.mp3
  Games/Music_Guess_Game/sounds/playAgain.mp3
  Games/Music_Guess_Game/sounds/rightAnswer.mp3
  Games/Music_Guess_Game/sounds/wrongAnswer.mp3
  Games/Music_Guess_Game/style.css
  README.md
  assets/images/Music_Guess_Game.png
Labels: Pending, changes requested

#1525 Updated UI of master typing
  Games/Master_Typing/index.html
  Games/Master_Typing/style.css
  assets/images/Master_Typing.png
Labels: gssoc23, level2

#1530 Mastermind_Mania Game Added
  Games/Mastermind_Mania/Mastermind_Mania.png
  Games/Mastermind_Mania/README.md
  Games/Mastermind_Mania/css/style.css
  Games/Mastermind_Mania/images/01.png
  Games/Mastermind_Mania/images/02.png
  Games/Mastermind_Mania/index.html
  Games/Mastermind_Mania/js/script.js
  README.md
  assets/images/Mastermind_Mania.png
Labels: gssoc23, level3

#1545 Ludo_4_Player
  Games/Ludo_4_Player/README.md
  Games/Ludo_4_Player/assets/images/crown1.png
  Games/Ludo_4_Player/assets/images/crown2.png
  Games/Ludo_4_Player/assets/images/crown3.png
  Games/Ludo_4_Player/assets/images/dice_1.png
  Games/Ludo_4_Player/assets/sounds/dice.mp3
  Games/Ludo_4_Player/assets/sounds/inout.mp3
  Games/Ludo_4_Player/assets/sounds/killed.mp3
  Games/Ludo_4_Player/assets/sounds/step.mp3
  Games/Ludo_4_Player/assets/sounds/win.mp3
  Games/Ludo_4_Player/index.html
  Games/Ludo_4_Player/script.js
  Games/Ludo_4_Player/style.css
  README.md
  assets/images/Ludo_4_Player.PNG
Labels: under review

#1555 added space invaders game
  Games/Space Invaders/README.md
  Games/Space Invaders/index.html
  Games/Space Invaders/space.css
  Games/Space Invaders/space.js
  README.md
  assets/images/Space Invaders.png
  assets/images/alien-cyan.png
  assets/images/alien-magenta.png
  assets/images/alien-yellow.png
  assets/images/alien.png
  assets/images/ship.png
Labels: gssoc23, level3

#1542 Scroll to top button updated to match website theme
  assets/css/style.css
  assets/js/index.js
  assets/js/script.js
  index.html
Labels: gssoc23, level2

#1544 Update the sound feature of Master typing
  Games/Master_Typing/README.md
  Games/Master_Typing/assets/Right_Press.mp3
  Games/Master_Typing/assets/Wrong_Press.wav
  Games/Master_Typing/index.html
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
  assets/animations/rec-tab.mp4
Labels: gssoc23, level2

#1586 dependabot.yml file added
  .github/dependabot.yml
Labels: gssoc23, level1

#1592 Meta tags added
  index.html
Labels: gssoc23, level3

#1594 Monster_Maker Game Added
  Games/Monster_Maker/README.md
  Games/Monster_Maker/assets/images/Monster_Maker.png
  Games/Monster_Maker/assets/images/face-0.png
  Games/Monster_Maker/assets/images/face-1.png
  Games/Monster_Maker/assets/images/face-2.png
  Games/Monster_Maker/assets/images/face-3.png
  Games/Monster_Maker/assets/images/face-4.png
  Games/Monster_Maker/assets/images/face-5.png
  Games/Monster_Maker/index.html
  Games/Monster_Maker/inset.html
  Games/Monster_Maker/script.js
  Games/Monster_Maker/style.css
  README.md
  assets/images/Monster_Maker.png
Labels: gssoc23, level3

#1196 [ADD]: STOLEN SWORD GAME 👾
  Games/Stolen_Sword/README.md
  Games/Stolen_Sword/index.html
  README.md
  assets/images/Stolen_Sword.jpg
Labels: gssoc23, level3, under review

#1589 Mastermind
  Games/Mastemind/FredokaOne-Regular.ttf
  Games/Mastemind/Masterming.png
  Games/Mastemind/README.md
  Games/Mastemind/Screenshots/Mastermind.png
  Games/Mastemind/game.js
  Games/Mastemind/index.html
  Games/Mastemind/styles.css
  README.md
  assets/images/Mastermind.png
Labels: gssoc23, level3, under review

#1198 [ADD]: HIGHWAY 404 GAME 👾
  Games/Highway_404/README.md
  Games/Highway_404/index.html
  README.md
  assets/images/Highway_404.jpg
Labels: gssoc23, level3

#1541 Add pagination in project list
  assets/css/style.css
  assets/js/index.js
  assets/js/script.js
  index.html
Labels: gssoc23, level2

#1602 New game is added
  Games/BullseyeGame/Readme.md
  Games/BullseyeGame/index.html
  Games/BullseyeGame/script.js
  Games/BullseyeGame/style.css
  README.md
  assets/images/BullseyeGame.png
Labels: Pending, changes requested

#1616 [Fixes #1155] Enhancement of Wordle Game
  Games/Wordle/README.md
  Games/Wordle/images/decrease.png
  Games/Wordle/images/img1.png
  Games/Wordle/images/img2.png
  Games/Wordle/images/img3.png
  Games/Wordle/images/increase.png
  Games/Wordle/images/setting.png
  Games/Wordle/index.html
  Games/Wordle/script.js
  Games/Wordle/style.css
  Games/Wordle/word_files/five_letters.json
  Games/Wordle/word_files/four_letters.json
  Games/Wordle/word_files/three_letters.json
  assets/images/Wordle.png
Labels: gssoc23, level2

#1613 Guess_The_Correct_Logo game added
  Games/Guess_The_Correct_Logo/README.md
  Games/Guess_The_Correct_Logo/assests/apple1.png
  Games/Guess_The_Correct_Logo/assests/apple2.png
  Games/Guess_The_Correct_Logo/assests/bmw1.png
  Games/Guess_The_Correct_Logo/assests/bmw2.png
  Games/Guess_The_Correct_Logo/assests/burgerking1.png
  Games/Guess_The_Correct_Logo/assests/burgerking2.png
  Games/Guess_The_Correct_Logo/assests/dominos1.png
  Games/Guess_The_Correct_Logo/assests/dominos2.png
  Games/Guess_The_Correct_Logo/assests/google1.png
  Games/Guess_The_Correct_Logo/assests/google2.png
  Games/Guess_The_Correct_Logo/assests/hp1.png
  Games/Guess_The_Correct_Logo/assests/hp2.png
  Games/Guess_The_Correct_Logo/assests/ibm1.png
  Games/Guess_The_Correct_Logo/assests/ibm2.png
  Games/Guess_The_Correct_Logo/assests/instagram1.png
  Games/Guess_The_Correct_Logo/assests/instagram2.png
  Games/Guess_The_Correct_Logo/assests/microsoft1.png
  Games/Guess_The_Correct_Logo/assests/microsoft2.png
  Games/Guess_The_Correct_Logo/assests/nasa1.png
  Games/Guess_The_Correct_Logo/assests/nasa2.png
  Games/Guess_The_Correct_Logo/assests/pepsi1.png
  Games/Guess_The_Correct_Logo/assests/pepsi2.png
  Games/Guess_The_Correct_Logo/assests/rolex1.png
  Games/Guess_The_Correct_Logo/assests/rolex2.png
  Games/Guess_The_Correct_Logo/assests/starbucks1.png
  Games/Guess_The_Correct_Logo/assests/starbucks2.png
  Games/Guess_The_Correct_Logo/assests/subway1.png
  Games/Guess_The_Correct_Logo/assests/subway2.png
  Games/Guess_The_Correct_Logo/assests/twitter1.png
  Games/Guess_The_Correct_Logo/assests/twitter2.png
  Games/Guess_The_Correct_Logo/game.html
  Games/Guess_The_Correct_Logo/index.html
  Games/Guess_The_Correct_Logo/main.css
  Games/Guess_The_Correct_Logo/script.js
  Games/Guess_The_Correct_Logo/style.css
  README.md
  assets/images/Guess_The_Correct_Logo.png
Labels: gssoc23, level3

#1619 Painting_Game Added
  Games/Painting_Game/README.md
  Games/Painting_Game/index.html
  Games/Painting_Game/script.js
  Games/Painting_Game/style.css
  README.md
  assets/images/Painting_Game.png
Labels: under review
