Repository kunjgit/GameZone, pull requests merged in 2023-08, with the labels that each got.

#2669 Quizify
  Games/Quizify/README.md
  Games/Quizify/image.png
  Games/Quizify/index.html
  Games/Quizify/script.js
  Games/Quizify/styles.css
  README.md
  assets/images/Quizify.png
Labels: gssoc23, level2, Ready to merge 🥳

#2691 Word blitz
  Games/word_blitz/README.md
  Games/word_blitz/index.html
  Games/word_blitz/script.js
  Games/word_blitz/style.css
  README.md
  assets/images/word blitz.png
Labels: gssoc23, level2, Ready to merge 🥳

#2688 Game
  Games/Tenzies/.gitignore
  Games/Tenzies/README.md
  Games/Tenzies/package-lock.json
  Games/Tenzies/package.json
  Games/Tenzies/public/index.html
  Games/Tenzies/src/App.js
  Games/Tenzies/src/Die.js
  Games/Tenzies/src/index.js
  Games/Tenzies/src/style.css
  README.md
  index.html
Labels: gssoc23, level3, Ready to merge 🥳

#2634 Haunted Mansion Mystery
  Games/Mansion_Mystery/README.md
  Games/Mansion_Mystery/index.html
  Games/Mansion_Mystery/script.js
  Games/Mansion_Mystery/styles.css
  assets/images/Mansion_Mystery.png
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2624 Country-Guesser Game changed
  Games/Country_Guesser_Game/style.css
Labels: gssoc23, Ready to merge 🥳, level1

#2681 Added Othello Game
  Games/Othello/README.md
  Games/Othello/index.html
  Games/Othello/script.js
  Games/Othello/style.css
  README.md
  assets/images/Othello.png
Labels: gssoc23, level2, Ready to merge 🥳

#2682 animated scrolltBug
  assets/css/scroll.css
Labels: enhancement, good first issue, gssoc23, Ready to merge 🥳, level1

#2702 chore: update workflow to add label and pre-commit message & remove node_modules directory
  .github/dependabot.yml
  .github/node_modules/.package-lock.json
  .github/node_modules/string-similarity/LICENSE
  .github/node_modules/string-similarity/README.md
  .github/node_modules/string-similarity/package.json
  .github/node_modules/string-similarity/src/index.js
  .github/node_modules/string-similarity/umd/string-similarity.min.js
Labels: good first issue, gssoc23, Ready to merge 🥳, level1

#2724 New game added
  Games/Know_Your_Country/README.md
  Games/Know_Your_Country/index.html
  Games/Know_Your_Country/index.js
  Games/Know_Your_Country/style.css
  README.md
  assets/images/Know_Your_Country.png
  assets/images/Know_Your_Country.webp
  assets/images/desktop.ini
Labels: gssoc23, level2, Ready to merge 🥳

#2726 Enhanced chrome dino game
  Games/Chrome_Dinosaur_Game/assets/sounds/die.mp3
  Games/Chrome_Dinosaur_Game/assets/sounds/jump.mp3
  Games/Chrome_Dinosaur_Game/assets/sounds/point.mp3
  Games/Chrome_Dinosaur_Game/index.html
  Games/Chrome_Dinosaur_Game/script.js
Labels: gssoc23, level2, Ready to merge 🥳

#2723 Fix bug causing Squared Lines to not open
  assets/js/gamesData.json
Labels: good first issue, gssoc23, Ready to merge 🥳, level1, Fixed

#2727 [GSSoC'23] Code Cracker Game Ready
  Games/Code-Cracker/README.md
  Games/Code-Cracker/index.html
  Games/Code-Cracker/script.js
  Games/Code-Cracker/style.css
  README.md
  assets/images/Code_Cracker.png
Labels: gssoc23, level3, Ready to merge 🥳

#2654 # 2653 Musical Floor Game
  Games/Musical_Floor/README.md
  Games/Musical_Floor/assets/casio--9759.mp3
  Games/Musical_Floor/assets/casio-9757.mp3
  Games/Musical_Floor/assets/data-6460.mp3
  Games/Musical_Floor/assets/do-80236.mp3
  Games/Musical_Floor/assets/fa-78409.mp3
  Games/Musical_Floor/assets/g-6200.mp3
  Games/Musical_Floor/assets/la-80237.mp3
  Games/Musical_Floor/assets/mi-80239.mp3
  Games/Musical_Floor/assets/piano-37898.mp3
  Games/Musical_Floor/assets/re-78500.mp3
  Games/Musical_Floor/assets/si-80238.mp3
  Games/Musical_Floor/assets/sol-101774.mp3
  Games/Musical_Floor/assets/typing-sound-effect-117679.mp3
  Games/Musical_Floor/index.html
  Games/Musical_Floor/scripts.js
  Games/Musical_Floor/styles.css
  README.md
  assets/images/Musical_Floor.png
Labels: gssoc23, level2, Ready to merge 🥳

#2733 Hack analyse title
  .github/labeler-config.yml
  .github/workflows/add-labels-pr.yml
Labels: good first issue, gssoc23, level2, Ready to merge 🥳

#2661 Added Sky Dodge
  Games/Sky_Dodge/README.md
  Games/Sky_Dodge/index.html
  Games/Sky_Dodge/script.js
  Games/Sky_Dodge/style.css
  README.md
  assets/images/sky_dodge.png
Labels: gssoc23, level2, Ready to merge 🥳

#2738 Changes in snake water gun game
  Games/snake_water_gun/index.html
  Games/snake_water_gun/style.css
Labels: good first issue, gssoc23, Ready to merge 🥳, level1

#2742 [GSSoC'23] Hunt Card Game Completed
  Games/Hunt_Your_Card/README.md
  Games/Hunt_Your_Card/index.html
  Games/Hunt_Your_Card/script.js
  Games/Hunt_Your_Card/style.css
Labels: gssoc23, Ready to merge 🥳, level1

#2746 Connect four new game
  Games/Connect_Four/Connect-Four.png
  Games/Connect_Four/README.md
  Games/Connect_Four/index.html
  Games/Connect_Four/script.js
  Games/Connect_Four/style.css
  assets/images/Connect-Four.png
Labels: gssoc23, level2, Ready to merge 🥳

#2613 Added 3D Car Racing Game Project
  Games/1icon.png
  Games/3D_Car_Racing_Game/README.md
  Games/3D_Car_Racing_Game/assests/1icon.png
  Games/3D_Car_Racing_Game/assests/car04.png
  Games/3D_Car_Racing_Game/assests/cloud.jpg
  Games/3D_Car_Racing_Game/assests/finish.png
  Games/3D_Car_Racing_Game/assests/hero.png
  Games/3D_Car_Racing_Game/assests/icon.png
  Games/3D_Car_Racing_Game/assests/tree.png
  Games/3D_Car_Racing_Game/index.html
  Games/car04.png
  Games/cloud.jpg
  Games/finish.png
  Games/hero.png
  Games/icon.png
  Games/index.html
  Games/null.js
  Games/tree.png
Labels: gssoc23, level3, Ready to merge 🥳

#2764 Added some functionality to footer section
  assets/css/style.css
  index.html
Labels: gssoc23, level2, Ready to merge 🥳

#2749 Added a new game - Rotating Elements
  Games/Rotating_Elements/README.md
  Games/Rotating_Elements/assets/Rotating_Elements.png
  Games/Rotating_Elements/assets/after_scoring.png
  Games/Rotating_Elements/index.html
  Games/Rotating_Elements/script.js
  Games/Rotating_Elements/styles.css
  README.md
  assets/images/Rotating_Elements.png
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2754 [GSSoC'23] Swap Game Completed
  Games/Swap-Card-Game/Deck/Clubs/1-C.png
  Games/Swap-Card-Game/Deck/Clubs/10-C.png
  Games/Swap-Card-Game/Deck/Clubs/11-C.png
  Games/Swap-Card-Game/Deck/Clubs/12-C.png
  Games/Swap-Card-Game/Deck/Clubs/13-C.png
  Games/Swap-Card-Game/Deck/Clubs/2-C.png
  Games/Swap-Card-Game/Deck/Clubs/3-C.png
  Games/Swap-Card-Game/Deck/Clubs/4-C.png
  Games/Swap-Card-Game/Deck/Clubs/5-C.png
  Games/Swap-Card-Game/Deck/Clubs/6-C.png
  Games/Swap-Card-Game/Deck/Clubs/7-C.png
  Games/Swap-Card-Game/Deck/Clubs/8-C.png
  Games/Swap-Card-Game/Deck/Clubs/9-C.png
  Games/Swap-Card-Game/Deck/Diamonds/1-D.png
  Games/Swap-Card-Game/Deck/Diamonds/10-D.png
  Games/Swap-Card-Game/Deck/Diamonds/11-D.png
  Games/Swap-Card-Game/Deck/Diamonds/12-D.png
  Games/Swap-Card-Game/Deck/Diamonds/13-D.png
  Games/Swap-Card-Game/Deck/Diamonds/2-D.png
  Games/Swap-Card-Game/Deck/Diamonds/3-D.png
  Games/Swap-Card-Game/Deck/Diamonds/4-D.png
  Games/Swap-Card-Game/Deck/Diamonds/5-D.png
  Games/Swap-Card-Game/Deck/Diamonds/6-D.png
  Games/Swap-Card-Game/Deck/Diamonds/7-D.png
  Games/Swap-Card-Game/Deck/Diamonds/8-D.png
  Games/Swap-Card-Game/Deck/Diamonds/9-D.png
  Games/Swap-Card-Game/Deck/Hearts/1-H.png
  Games/Swap-Card-Game/Deck/Hearts/10-H.png
  Games/Swap-Card-Game/Deck/Hearts/11-H.png
  Games/Swap-Card-Game/Deck/Hearts/12-H.png
  Games/Swap-Card-Game/Deck/Hearts/13-H.png
  Games/Swap-Card-Game/Deck/Hearts/2-H.png
  Games/Swap-Card-Game/Deck/Hearts/3-H.png
  Games/Swap-Card-Game/Deck/Hearts/4-H.png
  Games/Swap-Card-Game/Deck/Hearts/5-H.png
  Games/Swap-Card-Game/Deck/Hearts/6-H.png
  Games/Swap-Card-Game/Deck/Hearts/7-H.png
  Games/Swap-Card-Game/Deck/Hearts/8-H.png
  Games/Swap-Card-Game/Deck/Hearts/9-H.png
  Games/Swap-Card-Game/Deck/Spades/1-S.png
  Games/Swap-Card-Game/Deck/Spades/10-S.png
  Games/Swap-Card-Game/Deck/Spades/11-S.png
  Games/Swap-Card-Game/Deck/Spades/12-S.png
  Games/Swap-Card-Game/Deck/Spades/13-S.png
  Games/Swap-Card-Game/Deck/Spades/2-S.png
  Games/Swap-Card-Game/Deck/Spades/3-S.png
  Games/Swap-Card-Game/Deck/Spades/4-S.png
  Games/Swap-Card-Game/Deck/Spades/5-S.png
  Games/Swap-Card-Game/Deck/Spades/6-S.png
  Games/Swap-Card-Game/Deck/Spades/7-S.png
  Games/Swap-Card-Game/Deck/Spades/8-S.png
  Games/Swap-Card-Game/Deck/Spades/9-S.png
  Games/Swap-Card-Game/Deck/images.png
  Games/Swap-Card-Game/README.md
  Games/Swap-Card-Game/index.html
  Games/Swap-Card-Game/script.js
  Games/Swap-Card-Game/style.css
  README.md
  assets/images/Swap-Card-Game.png
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2760 Added Flappy bubble_sofa game #2757
  Games/Flappy_Bubble_Sofa/README.md
  Games/Flappy_Bubble_Sofa/assets/README/image-1.png
  Games/Flappy_Bubble_Sofa/assets/README/image.png
  Games/Flappy_Bubble_Sofa/assets/css/styles.css
  Games/Flappy_Bubble_Sofa/assets/img/logo.png
  Games/Flappy_Bubble_Sofa/assets/js/main.js
  Games/Flappy_Bubble_Sofa/index.html
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2756 [Bug]: Correcting name convention of many games in the Repo and also updating the README.md [gssoc23]
  Games/Code_Cracker/README.md
  Games/Code_Cracker/index.html
  Games/Code_Cracker/script.js
  Games/Code_Cracker/style.css
  Games/Color_Shifter/README.md
  Games/Color_Shifter/index.html
  Games/Color_Shifter/script.js
  Games/Color_Shifter/style.css
  Games/Color_Turner/README.md
  Games/Color_Turner/index.html
  Games/Color_Turner/style.css
  Games/Infinite_Runner_Game/Readme.md
  Games/Infinite_Runner_Game/index.html
  Games/Infinite_Runner_Game/script.js
  Games/Infinite_Runner_Game/style.css
  Games/Remember_the_color/README.md
  Games/Remember_the_color/ScreenShots/Color_Matcher.png
  Games/Remember_the_color/ScreenShots/game_over.png
  Games/Remember_the_color/ScreenShots/you_win.png
  Games/Remember_the_color/css/game.css
  Games/Remember_the_color/css/main.css
  Games/Remember_the_color/index.html
  Games/Remember_the_color/js/colorHelper.js
  Games/Remember_the_color/js/script.js
  README.md
Labels: bug, documentation, gssoc23, level2, Ready to merge 🥳

#2774 Stuck Dark Theme Switch To The Top Left & Added Hover Effect To Contributor Cards
  assets/css/contributors.css
  assets/css/style.css
  index.html
Labels: enhancement, good first issue, gssoc23, Ready to merge 🥳, level1

#2775 fix: Updated alt and Meta Tags in Some Files
  Games/1024_Moves/index.html
  Games/2D_Breakout/index.html
  Games/Achluophobia/index.html
  Games/Adventure_Game/index.html
  Games/Aim_Training/index.html
  Games/Archery/index.html
  Games/Back_To_Space/index.html
  Games/Bad_Depot/index.html
  Games/Baseball/index.html
Labels: bug, gssoc23, level2, Ready to merge 🥳, Fixed

#2780 Truth and Dare
  Games/Truth_And_Dare/README.md
  Games/Truth_And_Dare/image.png
  Games/Truth_And_Dare/index.html
  Games/Truth_And_Dare/script.js
  Games/Truth_And_Dare/styles.css
  README.md
  assets/images/Truth_And_Dare.png
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2781 Added new game
  Games/Response_Reaction/README.md
  Games/Response_Reaction/index.html
  Games/Response_Reaction/index.js
  Games/Response_Reaction/style.css
  README.md
  assets/images/Response_Reaction.png
  assets/images/Response_Reaction.webp
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2768 Added Anime Clicker
  Games/Anime_Clicker/README.md
  Games/Anime_Clicker/app.html
  Games/Anime_Clicker/estilo.css
  Games/Anime_Clicker/fim_de_jogo.html
  Games/Anime_Clicker/img/bg.jpg
  Games/Anime_Clicker/img/coracao_cheio.png
  Games/Anime_Clicker/img/coracao_vazio.png
  Games/Anime_Clicker/img/game.png
  Games/Anime_Clicker/img/game_over.png
  Games/Anime_Clicker/img/mata_mosquito.png
  Games/Anime_Clicker/img/mosca.png
  Games/Anime_Clicker/index.html
  Games/Anime_Clicker/jogo.js
  Games/Anime_Clicker/vitoria.html
  README.md
  assets/images/Anime_Clicker.png
Labels: gssoc23, level2, Ready to merge 🥳

#2784 added chopsticks
  Games/Chopsticks/README.md
  Games/Chopsticks/image-0.png
  Games/Chopsticks/image-1.png
  Games/Chopsticks/image-2.png
  Games/Chopsticks/index.html
  Games/Chopsticks/media/Down.png
  Games/Chopsticks/media/Up.png
  Games/Chopsticks/media/blog-confetti.png
  Games/Chopsticks/media/chinese_takeaway.ttf
  Games/Chopsticks/media/cup.jpg
  Games/Chopsticks/media/play-button.png
  Games/Chopsticks/media/points-0-selected.svg
  Games/Chopsticks/media/points-0-unselected.svg
  Games/Chopsticks/media/points-1-selected.svg
  Games/Chopsticks/media/points-1-unselected.svg
  Games/Chopsticks/media/points-2-selected.svg
  Games/Chopsticks/media/points-2-unselected.svg
  Games/Chopsticks/media/points-3-selected.svg
  Games/Chopsticks/media/points-3-unselected.svg
  Games/Chopsticks/media/points-4-selected.svg
  Games/Chopsticks/media/points-4-unselected.svg
  Games/Chopsticks/media/update.png
  Games/Chopsticks/script.js
  Games/Chopsticks/style.css
  Games/Chopsticks/video.webm
  README.md
  assets/images/Chopsticks.png
Labels: gssoc23, level2, Ready to merge 🥳

#2799 game added road car
  Games/road_car/Readme.md
  Games/road_car/index.html
  Games/road_car/main.css
  Games/road_car/script.js
  README.md
  assets/images/road_car.png
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2785 Added a new game called Rocket Showdown
  Games/Rocket_Showdown/README.md
  Games/Rocket_Showdown/assets/Rocket_Showdown.png
  Games/Rocket_Showdown/assets/in-game_Rocket-Showdown.png
  Games/Rocket_Showdown/index.html
  Games/Rocket_Showdown/script.js
  Games/Rocket_Showdown/styles.css
  README.md
  assets/images/Rocket_Showdown.png
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2803 Changes in Typing Speed Test Game
  Games/Typing_Speed_Test_Game/style.css
Labels: enhancement, gssoc23, Ready to merge 🥳, level1

#2787 Added 3d Snake Game
  Games/3d_Snake/README.md
  Games/3d_Snake/index.html
  Games/3d_Snake/script.js
  Games/3d_Snake/style.css
  README.md
  assets/images/3d_Snake.png
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2790 Pathplex game added
  Games/Pathplex/Box2dWeb.min.js
  Games/Pathplex/Readme.md
  Games/Pathplex/Screenshots/PathPlex.png
  Games/Pathplex/Three.js
  Games/Pathplex/ball.png
  Games/Pathplex/brick.png
  Games/Pathplex/concrete.png
  Games/Pathplex/index.html
  Games/Pathplex/keyboard.js
  Games/Pathplex/maze.js
  README.md
  assets/images/PathPlex.png
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2800 [GSSoC'23] Find Extra Cube Game ✔️
  Games/Find_Extra_Cube/README.md
  Games/Find_Extra_Cube/index.html
  Games/Find_Extra_Cube/script.js
  Games/Find_Extra_Cube/style.css
  README.md
  assets/images/Find_Extra_Cube.png
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2796 Kunjgit/#2721
  Games/Rocket_game/Readme.md
  Games/Rocket_game/rocket_game.html
  README.md
  assets/images/Rocket_game.webp
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2823 Add New Game
  Games/CSS_Select/README.md
  Games/CSS_Select/css/jquery.mCustomScrollbar.css
  Games/CSS_Select/css/style.css
  Games/CSS_Select/favicon.png
  Games/CSS_Select/images/fb-share.jpg
  Games/CSS_Select/images/icon-email.svg
  Games/CSS_Select/images/icon-facebook.svg
  Games/CSS_Select/images/icon-twitter.svg
  Games/CSS_Select/images/line.gif
  Games/CSS_Select/images/share.png
  Games/CSS_Select/index.html
  Games/CSS_Select/js/jquery.js
  Games/CSS_Select/js/jquery.mCustomScrollbar.min.js
  Games/CSS_Select/js/levels.js
  Games/CSS_Select/js/restaurant.js
  README.md
  assets/images/CSS_Select.png
Labels: gssoc23, New Game 🎮, level3

#2808 Flip Coin
  Games/Flip_Coin/README.md
  Games/Flip_Coin/image.png
  Games/Flip_Coin/index.html
  Games/Flip_Coin/script.js
  Games/Flip_Coin/styles.css
  README.md
  assets/images/Flip_Coin.png
Labels: gssoc23, level2, Ready to merge 🥳

#2810 New game CSS Crossword added
  Games/CSS_Crossword/README.md
  Games/CSS_Crossword/index.html
  Games/CSS_Crossword/script.js
  Games/CSS_Crossword/style.css
  README.md
  assets/images/CSS_Crossword.png
  assets/images/CSS_Crossword.webp
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2815 Changes in SCIARA OF COLORS Game
  Games/Sciarra_Of_Colors/css/main.min.css
  Games/Sciarra_Of_Colors/index.html
Labels: enhancement, gssoc23, level2, Ready to merge 🥳

#2818 witty_word_quest
  Games/witty_word_quest/Readme.md
  Games/witty_word_quest/index.html
  Games/witty_word_quest/script.js
  Games/witty_word_quest/style.css
  README.md
  assets/images/witty_word_quest.png
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2822 Added Typing game Issue #2820
  Games/Typing_Game/README.md
  Games/Typing_Game/index.html
  Games/Typing_Game/script.js
  Games/Typing_Game/styles.css
  README.md
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2750 New game Claw Crane added
  Games/clawCrane/README.md
  Games/clawCrane/index.html
  Games/clawCrane/index.js
  Games/clawCrane/styles.css
Labels: gssoc23, New Game 🎮, level3

#2809 Fixed the Footer
  index.html
Labels: bug, gssoc23, Ready to merge 🥳, level1, Fixed

#2835 added Numeral-Whiz
  Games/numeral-whiz/README.md
  Games/numeral-whiz/index.html
  Games/numeral-whiz/script.js
  Games/numeral-whiz/style.css
  README.md
  assets/images/numeral-whiz.png
Labels: gssoc23, level2, Ready to merge 🥳

#2832 Resolving hover effect on gihub
  assets/css/style.css
Labels: good first issue, gssoc23, Ready to merge 🥳, level1, Fixed

#2846 Added Candy match saga game
  Games/Candy_Match_Saga/Readme.md
  Games/Candy_Match_Saga/assets/image.png
  Games/Candy_Match_Saga/background.jpg
  Games/Candy_Match_Saga/index.html
  Games/Candy_Match_Saga/script.js
  Games/Candy_Match_Saga/style.css
  README.md
  assets/images/Candy_match_saga.jpg
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2843 TEST YOUR BRAIN GAME IS ADDED
  Games/test_your_brain/images/img-1.png
  Games/test_your_brain/images/img-2.png
  Games/test_your_brain/images/img-3.png
  Games/test_your_brain/images/img-4.png
  Games/test_your_brain/images/img-5.png
  Games/test_your_brain/images/img-6.png
  Games/test_your_brain/images/que_icon.svg
  Games/test_your_brain/index.html
  Games/test_your_brain/readme.md
  Games/test_your_brain/script.js
  Games/test_your_brain/style.css
  assets/images/TEST_YOUR_BRAIN.png
Labels: gssoc23, New Game 🎮, level3, Ready to merge 🥳

#2833 Added a new game called Crossy Road
  Games/Crossy_Road/README.md
  Games/Crossy_Road/assets/Crossy_Road.png
  Games/Crossy_Road/assets/in-game_Crossy-Road.png
  Games/Crossy_Road/index.html
  Games/Crossy_Road/script.js
  Games/Crossy_Road/styles.css
  README.md
  assets/images/Crossy_Road.png
Labels: New Game 🎮, Conflicts on code

#2855 my mine sweeper game is added
  Games/my_mine_sweeper/README.md
  Games/my_mine_sweeper/index.html
  Games/my_mine_sweeper/script.js
  Games/my_mine_sweeper/style.css
  assets/images/my_mine_sweeper.png
Labels: gssoc23, New Game 🎮, level2, Ready to merge 🥳

#2850 [GSSoC'23] HueHero Game added
  Games/HueHero/README.md
  Games/HueHero/index.html
  Games/HueHero/js/Character.js
  Games/HueHero/js/Clock.js
  Games/HueHero/js/EventHandler.js
  Games/HueHero/js/Game.js
  Games/HueHero/js/Move.js
  Games/HueHero/js/Npc.js
  Games/HueHero/js/Painter.js
  Games/HueHero/js/Player.js
  Games/HueHero/js/Space.js
  Games/HueHero/js/Util.js
  Games/HueHero/js/Vector.js
  Games/HueHero/js/game.min.js
  Games/HueHero/styles.min.css
  README.md
  assets/images/HueHero.png
Labels: New Game 🎮
