Repository kunjgit/GameZone, pull requests merged in 2023-07, with the labels that each got.

#2084 Completed making Shadow_PokeGuess
  Games/Shadow_PokeGuess/Assets/images/Alakazam.jpg
  Games/Shadow_PokeGuess/Assets/images/Arcanine.jpg
  Games/Shadow_PokeGuess/Assets/images/Bulbasaur.jpg
  Games/Shadow_PokeGuess/Assets/images/Cubone.jpg
  Games/Shadow_PokeGuess/Assets/images/Ditto.jpg
  Games/Shadow_PokeGuess/Assets/images/Gloom.jpg
  Games/Shadow_PokeGuess/Assets/images/Gyarados.jpg
  Games/Shadow_PokeGuess/Assets/images/Hitmonlee.jpg
  Games/Shadow_PokeGuess/Assets/images/Horsea.jpg
  Games/Shadow_PokeGuess/Assets/images/Koffing.jpg
  Games/Shadow_PokeGuess/Assets/images/Mewtwo.jpg
  Games/Shadow_PokeGuess/Assets/images/Seaking.jpg
  Games/Shadow_PokeGuess/Assets/images/Tauros.jpg
  Games/Shadow_PokeGuess/Assets/images/Venonat.jpg
  Games/Shadow_PokeGuess/Assets/images/Victreebe.jpg
  Games/Shadow_PokeGuess/Assets/images/eevee.jpg
  Games/Shadow_PokeGuess/Assets/sounds/correct.mp3
  Games/Shadow_PokeGuess/Assets/sounds/wrong.mp3
  Games/Shadow_PokeGuess/README.md
  Games/Shadow_PokeGuess/index.html
  Games/Shadow_PokeGuess/script.js
  Games/Shadow_PokeGuess/style.css
  README.md
  assets/images/Shadow_PokeGuess.png
Labels: under review

#2072 [GSSoC'23] Number Sliding Game Completed
  Games/Number_Sliding_Puzzle_Game/README.md
  Games/Number_Sliding_Puzzle_Game/favicon.ico
  Games/Number_Sliding_Puzzle_Game/index.html
  Games/Number_Sliding_Puzzle_Game/script.js
  Games/Number_Sliding_Puzzle_Game/style.css
  README.md
  assets/images/Number_Sliding_Puzzle_Game.png
Labels: gssoc23, level2

#2196 Lizard Spock Game
  Games/Lizard Spock Game/README.md
  Games/Lizard Spock Game/confetti.js
  Games/Lizard Spock Game/index.html
  Games/Lizard Spock Game/main.js
  Games/Lizard Spock Game/style.css
  README.md
  assets/images/Lizard_Spock_Game.png
Labels: gssoc23, level3

#2197 added brain color mastermind game
  Games/Brain Color Mastermind/README.md
  Games/Brain Color Mastermind/index.html
  Games/Brain Color Mastermind/src/index.css
  Games/Brain Color Mastermind/src/index.js
  README.md
  assets/images/Brain Color Mastermind.png
Labels: gssoc23, level3

#2191 enhancement of simons game
  Games/Simon_Game_Challenge/game.js
  Games/Simon_Game_Challenge/index.html
  Games/Simon_Game_Challenge/styles.css
Labels: gssoc23, level2

#2166 Image issue solved
  Games/Guess_The_Number/README.md
  Games/Guess_The_Number/image.png
  assets/images/Guess_The_Number.png
  assets/images/Number_Guess.png
  assets/images/Number_Guess.webp
Labels: good first issue, gssoc23, level1

#2205 Added "Back to top" button in README.md
  README.md
Labels: enhancement, good first issue, gssoc23, level1

#2203 Duplicates are removed and replaced with the original games
  assets/js/gamesData.json
Labels: gssoc23, level1

#2219 Alphabet Learning Game
  Games/Alphabet Learning Game/README.md
  Games/Alphabet Learning Game/index.html
  Games/Alphabet Learning Game/script.js
  Games/Alphabet Learning Game/style.css
  README.md
  assets/images/Alphabet_Learning_Game.png
Labels: gssoc23, level3

#2194 Completed making Poke-Guess Blitz Game
  Games/Poke_Guess_Blitz/Assets/images/background.jpg
  Games/Poke_Guess_Blitz/Assets/sounds/correct.mp3
  Games/Poke_Guess_Blitz/Assets/sounds/wrong.mp3
  Games/Poke_Guess_Blitz/README.md
  Games/Poke_Guess_Blitz/index.html
  Games/Poke_Guess_Blitz/script.js
  Games/Poke_Guess_Blitz/style.css
  README.md
  assets/images/Poke_Guess_Blitz.png
Labels: gssoc23, level2

#2094 [Enhancement]: Add features in Country Guesser Game
  Games/Country_Guesser_Game/README.md
  Games/Country_Guesser_Game/index.html
  Games/Country_Guesser_Game/main.js
  Games/Country_Guesser_Game/style.css
  assets/images/country_guesser.png
  assets/images/country_guesser.webp
Labels: enhancement, gssoc23, level2

#2204 enhanced mole game
  Games/Whack_a_Mole/CSS/style.css
  Games/Whack_a_Mole/JS/script.js
  assets/images/Whack_a_Mole.png
Labels: gssoc23, level2

#2073 Added Chicken cannon game
  Games/Chicken_cannon/README.md
  Games/Chicken_cannon/code/game.js
  Games/Chicken_cannon/code/help.js
  Games/Chicken_cannon/code/menu.js
  Games/Chicken_cannon/code/shop.js
  Games/Chicken_cannon/code/start.js
  Games/Chicken_cannon/data.js
  Games/Chicken_cannon/fonts/manrope.ttf
  Games/Chicken_cannon/fonts/rubik.ttf
  Games/Chicken_cannon/fonts/ubuntu.ttf
  Games/Chicken_cannon/index.html
  Games/Chicken_cannon/sprites/cannon.png
  Games/Chicken_cannon/sprites/chicken.png
  Games/Chicken_cannon/sprites/collectables.png
  Games/Chicken_cannon/sprites/gameExtras.png
  Games/Chicken_cannon/sprites/ground.png
  Games/Chicken_cannon/sprites/logo.png
  Games/Chicken_cannon/sprites/outline.png
  Games/Chicken_cannon/sprites/rocket.png
  Games/Chicken_cannon/sprites/shopBuilder.png
  Games/Chicken_cannon/sprites/trampoline.png
  Games/Chicken_cannon/sprites/upgrades.png
  README.md
  assets/images/Chicken_cannon.png
Labels: gssoc23, level3

#2108 added quiz_game
  Games/quiz_game/README.md
  Games/quiz_game/index.html
  Games/quiz_game/script.js
  Games/quiz_game/style.css
  README.md
  assets/images/quiz_game.png
Labels: gssoc23, level2

#2086 Added Foosball Game
  Games/Foosball/README.md
  Games/Foosball/css/style.css
  Games/Foosball/img/awayPlayer.png
  Games/Foosball/img/background.png
  Games/Foosball/img/help.png
  Games/Foosball/img/homePlayer.png
  Games/Foosball/img/pitch3.png
  Games/Foosball/img/splash.png
  Games/Foosball/index.html
  Games/Foosball/js/SAT.js
  Games/Foosball/js/awayPlayer.png
  Games/Foosball/js/football.js
  Games/Foosball/js/homePlayer.png
  README.md
  assets/images/Foosball.png
Labels: under review

#2091 Add Triangle Back to Home Game
  Games/Triangle_Back_To_Home/README.md
  Games/Triangle_Back_To_Home/Triangle_Back_To_Home.png
  Games/Triangle_Back_To_Home/app/app.js
  Games/Triangle_Back_To_Home/app/character/character-animations.js
  Games/Triangle_Back_To_Home/app/character/character.js
  Games/Triangle_Back_To_Home/app/control.js
  Games/Triangle_Back_To_Home/app/decoration/background.js
  Games/Triangle_Back_To_Home/app/map/block.js
  Games/Triangle_Back_To_Home/app/map/map.js
  Games/Triangle_Back_To_Home/app/particles/particle.js
  Games/Triangle_Back_To_Home/app/particles/particles.js
  Games/Triangle_Back_To_Home/app/scene/camera.js
  Games/Triangle_Back_To_Home/app/scene/final-scene.js
  Games/Triangle_Back_To_Home/app/scene/scene.js
  Games/Triangle_Back_To_Home/app/scene/sfx.js
  Games/Triangle_Back_To_Home/app/scene/splash-screen.js
  Games/Triangle_Back_To_Home/app/utils/animation.js
  Games/Triangle_Back_To_Home/app/utils/color.js
  Games/Triangle_Back_To_Home/app/utils/draw.js
  Games/Triangle_Back_To_Home/app/utils/vector.js
  Games/Triangle_Back_To_Home/index.html
  README.md
  assets/images/Triangle_Back_To_Home.png
Labels: under review

#2223 fFxed the position of Theme
  index.html
Labels: good first issue, gssoc23, level1

#2187 Death by Hamster
  Games/Death by Hamster/README.md
  Games/Death by Hamster/aimerthing.png
  Games/Death by Hamster/arw.png
  Games/Death by Hamster/blip.mp3
  Games/Death by Hamster/cursor.png
  Games/Death by Hamster/favicon.ico
  Games/Death by Hamster/game.js
  Games/Death by Hamster/gun.png
  Games/Death by Hamster/hamster.png
  Games/Death by Hamster/human.png
  Games/Death by Hamster/index.html
  Games/Death by Hamster/letters.js
  Games/Death by Hamster/logothing.png
  Games/Death by Hamster/lzs.js
  Games/Death by Hamster/minify.py
  Games/Death by Hamster/t.png
  README.md
  assets/images/Death by Hamster.png
Labels: gssoc23, level2

#2220 fixed and added game data
  README.md
  assets/js/gamesData.json
  assets/js/index.js
Labels: gssoc23, level2

#2111 Added Firedog Adventure Game
  Games/Firedog_Adventure/CODE_OF_CONDUCT.md
  Games/Firedog_Adventure/CONTRIBUTING.md
  Games/Firedog_Adventure/FINAL/Bones.mp3
  Games/Firedog_Adventure/FINAL/background.js
  Games/Firedog_Adventure/FINAL/charlie-dont-surf-display-font.zip
  Games/Firedog_Adventure/FINAL/charlie-dont-surf-display-font/charlie-dont-surf.otf
  Games/Firedog_Adventure/FINAL/charlie-dont-surf-display-font/info.txt
  Games/Firedog_Adventure/FINAL/collision.png
  Games/Firedog_Adventure/FINAL/collisionanimation.js
  Games/Firedog_Adventure/FINAL/enemies.js
  Games/Firedog_Adventure/FINAL/enemy_bat_1.png
  Games/Firedog_Adventure/FINAL/enemy_bat_2.png
  Games/Firedog_Adventure/FINAL/enemy_bat_3.png
  Games/Firedog_Adventure/FINAL/enemy_digger.png
  Games/Firedog_Adventure/FINAL/enemy_fly.png
  Games/Firedog_Adventure/FINAL/enemy_ghost_1.png
  Games/Firedog_Adventure/FINAL/enemy_ghost_3.png
  Games/Firedog_Adventure/FINAL/enemy_ghost_4.png
  Games/Firedog_Adventure/FINAL/enemy_ground_zombie.png
  Games/Firedog_Adventure/FINAL/enemy_hand.png
  Games/Firedog_Adventure/FINAL/enemy_plant.png
  Games/Firedog_Adventure/FINAL/enemy_raven.png
  Games/Firedog_Adventure/FINAL/enemy_spider (1).png
  Games/Firedog_Adventure/FINAL/enemy_spider_big - Copy.png
  Games/Firedog_Adventure/FINAL/enemy_spider_big.png
  Games/Firedog_Adventure/FINAL/enemy_spinner.png
  Games/Firedog_Adventure/FINAL/enemy_worm (1).png
  Games/Firedog_Adventure/FINAL/enemy_zombie.png
  Games/Firedog_Adventure/FINAL/finalplayer.png
  Games/Firedog_Adventure/FINAL/fire.png
  Games/Firedog_Adventure/FINAL/index.html
  Games/Firedog_Adventure/FINAL/input.js
  Games/Firedog_Adventure/FINAL/layer-1.png
  Games/Firedog_Adventure/FINAL/layer-2.png
  Games/Firedog_Adventure/FINAL/layer-3.png
  Games/Firedog_Adventure/FINAL/layer-4.png
  Games/Firedog_Adventure/FINAL/layer-5.png
  Games/Firedog_Adventure/FINAL/layer-6.2.png
  Games/Firedog_Adventure/FINAL/layer-6.3.png
  Games/Firedog_Adventure/FINAL/layer-6.png
  Games/Firedog_Adventure/FINAL/layer01_Ground.1.png
  Games/Firedog_Adventure/FINAL/main.js
  Games/Firedog_Adventure/FINAL/particle.js
  Games/Firedog_Adventure/FINAL/player.js
  Games/Firedog_Adventure/FINAL/playerstate.js
  Games/Firedog_Adventure/FINAL/style.css
  Games/Firedog_Adventure/FINAL/ui.js
  Games/Firedog_Adventure/README.md
  Games/Firedog_Adventure/Squiggly-Pattern.gif
  Games/Firedog_Adventure/hexwave.gif
  Games/Firedog_Adventure/index.html
  Games/Firedog_Adventure/modern-futuristic-sci-fi-background_35913-2150 (1).webp
  Games/Firedog_Adventure/particle.gif
  Games/Firedog_Adventure/script.js
  Games/Firedog_Adventure/style.css
  README.md
  assets/images/Firedog_Adventure.png
Labels: gssoc23, level3

#2153 Added Trio_Match game
  Games/Trio_Match/README.md
  Games/Trio_Match/Trio_Match.png
  Games/Trio_Match/index.html
  Games/Trio_Match/script.js
  Games/Trio_Match/style.css
  README.md
  assets/images/Trio_Match.png
Labels: under review

#2157 Color_Crush_Game Added
  Games/Color_Crush_Game/README.md
  Games/Color_Crush_Game/index.html
  Games/Color_Crush_Game/script.js
  Games/Color_Crush_Game/style.css
  README.md
  assets/images/Color_Crush_Game.gif
Labels: gssoc23, level2

#2265 Word chain game
  Games/WordChain/README.md
  Games/WordChain/assets/WordChain.png
  Games/WordChain/assets/WordChainGame.mp4
  Games/WordChain/heading.png
  Games/WordChain/index.html
  Games/WordChain/script.js
  Games/WordChain/style.css
  README.md
  assets/images/WordChain.png
Labels: gssoc23, level3, under review

#2096 Glass_and_ball
  Games/Ball_and_glass/README.md
  Games/Ball_and_glass/cup.png
  Games/Ball_and_glass/index.html
  Games/Ball_and_glass/script.js
  Games/Ball_and_glass/style.css
  README.md
  assets/images/Ball_and_glass.png
Labels: gssoc23, level3, under review

#2113 Target_Torrent Added
  Games/Target_Torrent/CREDITS.txt
  Games/Target_Torrent/LICENSE
  Games/Target_Torrent/README.md
  Games/Target_Torrent/Target_Torrent.png
  Games/Target_Torrent/celebrate.html
  Games/Target_Torrent/dot.png
  Games/Target_Torrent/fail.html
  Games/Target_Torrent/images/01.png
  Games/Target_Torrent/images/02.png
  Games/Target_Torrent/images/03.png
  Games/Target_Torrent/images/04.png
  Games/Target_Torrent/index.html
  Games/Target_Torrent/play.html
  README.md
  assets/images/Target_Torrent.png
Labels: gssoc23, level3

#2257 Added New Game Reversi /othello
  Games/Reversi/.vscode/settings.json
  Games/Reversi/README.md
  Games/Reversi/reversi.css
  Games/Reversi/reversi.html
  Games/Reversi/reversi1.js
  README.md
  assets/images/reversi.png
Labels: gssoc23, level3

#2180 Fix Tic Tac Toe Game
  Games/Tic_Tac_Toe/script.js
Labels: gssoc23, level2

#2218 [GSSoC'23] Brain Burst Game Completed
  Games/Brain_Burst_Game/README.md
  Games/Brain_Burst_Game/favicon.ico
  Games/Brain_Burst_Game/index.html
  Games/Brain_Burst_Game/main.js
  Games/Brain_Burst_Game/style.css
  README.md
  assets/images/Brain_Burst_Game.png
Labels: gssoc23, level3

#2126 Stick The Sticker Game
  Games/StickTheSticker/README.md
  Games/StickTheSticker/assets/1.png
  Games/StickTheSticker/assets/2.png
  Games/StickTheSticker/index.html
  Games/StickTheSticker/puzzle1/p11.png
  Games/StickTheSticker/puzzle1/p12.png
  Games/StickTheSticker/puzzle1/p13.png
  Games/StickTheSticker/puzzle1/p14.png
  Games/StickTheSticker/puzzle2/p21.png
  Games/StickTheSticker/puzzle2/p22.png
  Games/StickTheSticker/puzzle2/p23.png
  Games/StickTheSticker/puzzle2/p24.png
  Games/StickTheSticker/puzzle3/p31.png
  Games/StickTheSticker/puzzle3/p32.png
  Games/StickTheSticker/puzzle3/p33.png
  Games/StickTheSticker/puzzle3/p34.png
  Games/StickTheSticker/puzzle4/p41.png
  Games/StickTheSticker/puzzle4/p42.png
  Games/StickTheSticker/puzzle4/p43.png
  Games/StickTheSticker/puzzle4/p44.png
  Games/StickTheSticker/puzzle5/p51.png
  Games/StickTheSticker/puzzle5/p52.png
  Games/StickTheSticker/puzzle5/p53.png
  Games/StickTheSticker/puzzle5/p54.png
  Games/StickTheSticker/puzzle6/p61.png
  Games/StickTheSticker/puzzle6/p62.png
  Games/StickTheSticker/puzzle6/p63.png
  Games/StickTheSticker/puzzle6/p64.png
  Games/StickTheSticker/script.js
  Games/StickTheSticker/style.css
  README.md
  assets/images/Stick_The_Sticker.png
  assets/images/Stick_The_Sticker.webp
Labels: gssoc23, level3

#2278 New tab Issue Fixed
  assets/js/index.js
Labels: gssoc23, level1

#2256 Meme Battle Game [GSSOC'23]
  Games/Meme Battle Game/README.md
  Games/Meme Battle Game/public/BATTLE game (5).png
  Games/Meme Battle Game/public/cloud.png
  Games/Meme Battle Game/public/go1.png
  Games/Meme Battle Game/public/go2.png
  Games/Meme Battle Game/public/heart.png
  Games/Meme Battle Game/public/index.html
  Games/Meme Battle Game/public/main.js
  Games/Meme Battle Game/public/memes/font/PublicPixel-z84yD.ttf
  Games/Meme Battle Game/public/memes/font/readme.md
  Games/Meme Battle Game/public/memes/fonts
  Games/Meme Battle Game/public/memes/player1/1.jpg
  Games/Meme Battle Game/public/memes/player1/10.jpg
  Games/Meme Battle Game/public/memes/player1/11.jpg
  Games/Meme Battle Game/public/memes/player1/12.jpg
  Games/Meme Battle Game/public/memes/player1/13.jpg
  Games/Meme Battle Game/public/memes/player1/14.jpg
  Games/Meme Battle Game/public/memes/player1/15.jpg
  Games/Meme Battle Game/public/memes/player1/16.png
  Games/Meme Battle Game/public/memes/player1/17.png
  Games/Meme Battle Game/public/memes/player1/18.png
  Games/Meme Battle Game/public/memes/player1/19.jpg
  Games/Meme Battle Game/public/memes/player1/2.jpg
  Games/Meme Battle Game/public/memes/player1/20.jpg
  Games/Meme Battle Game/public/memes/player1/3.jpg
  Games/Meme Battle Game/public/memes/player1/4.jpg
  Games/Meme Battle Game/public/memes/player1/5.png
  Games/Meme Battle Game/public/memes/player1/6.png
  Games/Meme Battle Game/public/memes/player1/7.png
  Games/Meme Battle Game/public/memes/player1/8.png
  Games/Meme Battle Game/public/memes/player1/9.jpg
  Games/Meme Battle Game/public/memes/player1/readme.md
  Games/Meme Battle Game/public/memes/player2/1.jpg
  Games/Meme Battle Game/public/memes/player2/10.png
  Games/Meme Battle Game/public/memes/player2/11.jpg
  Games/Meme Battle Game/public/memes/player2/12.jpg
  Games/Meme Battle Game/public/memes/player2/13.jpg
  Games/Meme Battle Game/public/memes/player2/14.jpg
  Games/Meme Battle Game/public/memes/player2/15.jpg
  Games/Meme Battle Game/public/memes/player2/16.jpg
  Games/Meme Battle Game/public/memes/player2/17.jpeg
  Games/Meme Battle Game/public/memes/player2/18.jpg
  Games/Meme Battle Game/public/memes/player2/19.jpg
  Games/Meme Battle Game/public/memes/player2/2.jpeg
  Games/Meme Battle Game/public/memes/player2/20.jpg
  Games/Meme Battle Game/public/memes/player2/3.jpg
  Games/Meme Battle Game/public/memes/player2/4.jpg
  Games/Meme Battle Game/public/memes/player2/5.png
  Games/Meme Battle Game/public/memes/player2/6.jpg
  Games/Meme Battle Game/public/memes/player2/7.jpg
  Games/Meme Battle Game/public/memes/player2/8.jpg
  Games/Meme Battle Game/public/memes/player2/9.jpg
  Games/Meme Battle Game/public/memes/player2/readme.md
  Games/Meme Battle Game/public/memes/readme.md
  Games/Meme Battle Game/public/stone.png
  Games/Meme Battle Game/public/style.css
  README.md
  assets/images/Meme Battle Game.png
Labels: gssoc23, level3

#2169 Added Bow And Arrow Game
  Games/Bow_And_Arrow/README.md
  Games/Bow_And_Arrow/index.html
  Games/Bow_And_Arrow/script.js
  Games/Bow_And_Arrow/styles.css
  README.md
  assets/images/Bow_And_Arrow.png
Labels: under review

#2235 Beyblade game added
  Games/Beyblade/README.md
  Games/Beyblade/assets/beyblade-1.jpg
  Games/Beyblade/assets/beyblade-2.jpg
  Games/Beyblade/index.html
  Games/Beyblade/script.js
  Games/Beyblade/style.css
  README.md
  assets/images/Beyblade.png
Labels: under review

#2305 The labyrinth of death
  Games/The labyrinth of death/README.md
  Games/The labyrinth of death/engine.js
  Games/The labyrinth of death/index.html
  README.md
  assets/images/The labyrinth of death.png
Labels: gssoc23, level3

#2372 Added 2D BreakThrough Out game
  Games/2D_Breakout/README.md
  Games/2D_Breakout/components.js
  Games/2D_Breakout/game.js
  Games/2D_Breakout/img/SOUND_OFF.png
  Games/2D_Breakout/img/SOUND_ON.png
  Games/2D_Breakout/img/bg.jpg
  Games/2D_Breakout/img/bg1.jpg
  Games/2D_Breakout/img/gameover.png
  Games/2D_Breakout/img/level.png
  Games/2D_Breakout/img/life.png
  Games/2D_Breakout/img/score.png
  Games/2D_Breakout/img/youwon.png
  Games/2D_Breakout/index.html
  Games/2D_Breakout/sounds/brick_hit.mp3
  Games/2D_Breakout/sounds/life_lost.mp3
  Games/2D_Breakout/sounds/paddle_hit.mp3
  Games/2D_Breakout/sounds/wall.mp3
  Games/2D_Breakout/sounds/win.mp3
  Games/2D_Breakout/style.css
  README.md
  assets/images/2D_Breakout.webp
Labels: under review

#2365 Documentation for Connect4 Game
  Games/Connect4/README.MD
Labels: gssoc23, level1

#2362 [GSSoC'23] Added Battleship Board game
  Games/Battleship/Battleship.html
  Games/Battleship/README.md
  Games/Battleship/assets/board.jpg
  Games/Battleship/assets/miss.png
  Games/Battleship/assets/ship.png
  Games/Battleship/js/battleship.js
  README.md
  assets/images/Battleship.png
Labels: gssoc23, level3

#2360 Baseball Blitz added
  Games/Baseball/README.md
  Games/Baseball/assets/batter.jpeg
  Games/Baseball/assets/pitcher.jpeg
  Games/Baseball/extra.js
  Games/Baseball/index.html
  Games/Baseball/script.js
  Games/Baseball/style.css
  README.md
  assets/images/Baseball.png
Labels: under review

#2375 Road fighter game is added
  Games/RoadFighter/README.md
  Games/RoadFighter/barrel.png
  Games/RoadFighter/car1.png
  Games/RoadFighter/car2.png
  Games/RoadFighter/car3.png
  Games/RoadFighter/car4.png
  Games/RoadFighter/car5.png
  Games/RoadFighter/car6 - Copy.png
  Games/RoadFighter/car6.png
  Games/RoadFighter/index.html
  Games/RoadFighter/map1.png
  Games/RoadFighter/map1game.html
  Games/RoadFighter/map2.png
  Games/RoadFighter/map2game.html
  Games/RoadFighter/rfmenu.png
  Games/RoadFighter/rfselectmode.png
  Games/RoadFighter/roadblock.png
  Games/RoadFighter/selectmode.html
  README.md
  assets/images/RoadFighter.png
Labels: under review

#2297 [GSSoC'23] Guitar Game Completed
  Games/Guitar_Game/README.md
  Games/Guitar_Game/index.html
  Games/Guitar_Game/style.css
  README.md
  assets/images/Guitar_Game.png
Labels: gssoc23, level3, under review

#2301 Added the game of solitaire
  Games/Solitaire/README.md
  Games/Solitaire/cards.js
  Games/Solitaire/index.html
  Games/Solitaire/script.js
  Games/Solitaire/style.css
  README.md
  assets/images/Solitaire.png
Labels: under review

#2302 Added lady tiger hunter game
  Games/Lady_Tiger_Hunter/README.md
  Games/Lady_Tiger_Hunter/index.html
  Games/Lady_Tiger_Hunter/script.js
  Games/Lady_Tiger_Hunter/style.css
  README.md
  assets/images/lady_tiger_hunter.png
Labels: under review

#2374 Accessibility added to socials of footer
  index.html
Labels: gssoc23, level2

#2440 [Enhancement] : Improve UI
  assets/css/style.css
  index.html
Labels: gssoc23, level2

#2437 modified layout of quiz_game
  Games/quiz_game/index.html
  Games/quiz_game/script.js
  Games/quiz_game/style.css
Labels: gssoc23, level2

#2444 [Enhancement] : Improving Theme Toggler and Card
  assets/css/particles.css
  assets/css/style.css
  index.html
Labels: gssoc23, level2

#2316 Add background to paragraph
  assets/css/style.css
Labels: good first issue, gssoc23, level1

#2411 Added score in bullseye game
  Games/BullseyeGame/index.html
  Games/BullseyeGame/script.js
  Games/BullseyeGame/style.css
  assets/js/gamesData.json
Labels: gssoc23, level2

#2446 Flashlight Pointer Game Added
  Games/Flashlight_Pointer_Game/README.md
  Games/Flashlight_Pointer_Game/index.html
  Games/Flashlight_Pointer_Game/script.js
  Games/Flashlight_Pointer_Game/style.css
  README.md
  assets/images/Flashlight_Pointer_Game.png
Labels: gssoc23, level3

#2361 Added Progress Bar to Scroll To Top & Minor Changes
  assets/css/scroll.css
  assets/css/style.css
  assets/js/script.js
  assets/js/scroll.js
  index.html
Labels: enhancement, good first issue, gssoc23, level2

#2452 README.md file Enhanced
  README.md
Labels: documentation, good first issue, gssoc23, level1

#2403 Added a licenses section and a MIT licenses badge
  README.md
Labels: documentation, good first issue, gssoc23, level1

#2459 [Enhancement]: Re-Added Floating Particles in Background
  assets/css/particles.css
  index.html
Labels: gssoc23, level2

#2343 Completed Lamb Lane game
  Games/Lamb_Lane/README.md
  Games/Lamb_Lane/index.html
  Games/Lamb_Lane/script.js
  Games/Lamb_Lane/style.css
  README.md
  assets/images/Lamb_Lane.png
Labels: gssoc23, level3

#2399 Added the cursor property
  index.html
Labels: enhancement, good first issue, gssoc23, level1

#2335 'Whack a Mole' Game Boxes Design Enhancement
  Games/Whack_a_Mole/CSS/style.css
  Games/Whack_a_Mole/index.html
Labels: gssoc23, level2

#2349 Enhanced the snake game
  Games/Snake_Game/assets/images/favicon.ico
  Games/Snake_Game/index.html
  Games/Snake_Game/style.css
Labels: gssoc23, level2

#2401 added Asteroids 3D Game 🌠
  Games/Asteroids_3D/Asteroids_3D.png
  Games/Asteroids_3D/README.md
  Games/Asteroids_3D/index.html
  Games/Asteroids_3D/script.js
  Games/Asteroids_3D/style.css
  README.md
  assets/images/Asteroids_3D.png
Labels: gssoc23, level3

#2466 'Snake Game' Design Enhancement
  Games/Snake_Game/index.html
  Games/Snake_Game/style.css
Labels: gssoc23, level2

#2313 Completed PiggyGame
  Games/Pig_game/README.md
  Games/Pig_game/assets/images/dice-1.png
  Games/Pig_game/assets/images/dice-2.png
  Games/Pig_game/assets/images/dice-3.png
  Games/Pig_game/assets/images/dice-4.png
  Games/Pig_game/assets/images/dice-5.png
  Games/Pig_game/assets/images/dice-6.png
  Games/Pig_game/assets/images/pig-game-animation.gif
  Games/Pig_game/assets/images/pig-game-flowchart.png
  Games/Pig_game/assets/images/screenshot.JPG
  Games/Pig_game/index.html
  Games/Pig_game/script.js
  Games/Pig_game/style.css
  README.md
  assets/images/Pig_game.JPG
Labels: gssoc23, level2, under review

#2472 [Enhancement]: Fixed the Website
  index.html
Labels: gssoc23, level1

#2442 Dinoffline
  Games/Dinoffline/README.md
  Games/Dinoffline/eyes0.png
  Games/Dinoffline/eyes1.png
  Games/Dinoffline/eyes2.png
  Games/Dinoffline/eyes3.png
  Games/Dinoffline/eyes4.png
  Games/Dinoffline/index.html
  Games/Dinoffline/script.js
  Games/Dinoffline/style.css
  README.md
  assets/images/Dinoffline.png
Labels: gssoc23, level3

#2416 [GSSoC'23] Sketch Game Project Completed
  Games/Etch-a-Sketch/README.md
  Games/Etch-a-Sketch/game.js
  Games/Etch-a-Sketch/index.html
  Games/Etch-a-Sketch/styles.css
  README.md
  assets/images/Etch-a-Sketch.png
Labels: gssoc23, level3

#2475 Math Sprint Game
  Games/Maths_Sprint_Game/README.md
  Games/Maths_Sprint_Game/index.html
  Games/Maths_Sprint_Game/main.js
  Games/Maths_Sprint_Game/shuffle.js
  Games/Maths_Sprint_Game/style.css
  README.md
  assets/images/Maths_Sprint_Game.png
Labels: gssoc23, level3

#2476 updated color of game names
  assets/css/style.css
Labels: gssoc23, level1

#2473 added Snail Game 🐌
  Games/Snail_Game/README.md
  Games/Snail_Game/Snail_Game.png
  Games/Snail_Game/index.html
  Games/Snail_Game/script.js
  Games/Snail_Game/style.css
  README.md
  assets/images/Snail_Game.png
Labels: gssoc23, level2

#2397 fix: Changes added in Scrolling Behavior with Respective Different Browsers
  assets/css/style.css
Labels: gssoc23, level2

#2487 [Enhancement]: Games Title and Description Styling Enhancement
  assets/css/style.css
Labels: good first issue, gssoc23, level1

#2491 Chrome Dinosaur Game Updated Styling
  Games/Chrome_Dinosaur_Game/index.html
  Games/Chrome_Dinosaur_Game/style.css
Labels: gssoc23, level1

#2410 Game Added : Advanced Stone Paper Scissor
  Games/Stone-Paper-Scissor/.babelrc.json
  Games/Stone-Paper-Scissor/.eslintrc.json
  Games/Stone-Paper-Scissor/.gitignore
  Games/Stone-Paper-Scissor/.prettierrc.json
  Games/Stone-Paper-Scissor/README.md
  Games/Stone-Paper-Scissor/config/dummy.js
  Games/Stone-Paper-Scissor/config/paths.js
  Games/Stone-Paper-Scissor/config/webpack.common.js
  Games/Stone-Paper-Scissor/config/webpack.dev.js
  Games/Stone-Paper-Scissor/config/webpack.prod.js
  Games/Stone-Paper-Scissor/index.html
  Games/Stone-Paper-Scissor/package-lock.json
  Games/Stone-Paper-Scissor/package.json
  Games/Stone-Paper-Scissor/postcss.config.js
  Games/Stone-Paper-Scissor/public/dumy.js
  Games/Stone-Paper-Scissor/public/human.png
  Games/Stone-Paper-Scissor/public/paper.png
  Games/Stone-Paper-Scissor/public/robot.gif
  Games/Stone-Paper-Scissor/public/rock.png
  Games/Stone-Paper-Scissor/public/scissors.png
  Games/Stone-Paper-Scissor/script.js
  Games/Stone-Paper-Scissor/src/dummy.js
  Games/Stone-Paper-Scissor/src/fonts/8BITWONDERNominal.woff
  Games/Stone-Paper-Scissor/src/fonts/8BITWONDERNominal.woff2
  Games/Stone-Paper-Scissor/src/fonts/dumy.js
  Games/Stone-Paper-Scissor/src/images/dumy.js
  Games/Stone-Paper-Scissor/src/images/favicon.png
  Games/Stone-Paper-Scissor/src/index.js
  Games/Stone-Paper-Scissor/src/js/CameraConfig.js
  Games/Stone-Paper-Scissor/src/js/Gestures.js
  Games/Stone-Paper-Scissor/src/js/Prediction.js
  Games/Stone-Paper-Scissor/src/js/SampleImage.js
  Games/Stone-Paper-Scissor/src/js/UI.js
  Games/Stone-Paper-Scissor/src/js/dumy.js
  Games/Stone-Paper-Scissor/src/styles/_game.scss
  Games/Stone-Paper-Scissor/src/styles/_variables.scss
  Games/Stone-Paper-Scissor/src/styles/dumy.js
  Games/Stone-Paper-Scissor/src/styles/index.scss
  Games/Stone-Paper-Scissor/src/template.html
  Games/Stone-Paper-Scissor/style.css
  README.md
  assets/images/StonePaper.png
  assets/js/gamesData.json
Labels: gssoc23, level3

#2488 Enhancement of Country Guesser Game
  Games/Country_Guesser_Game/README.md
  Games/Country_Guesser_Game/index.html
  Games/Country_Guesser_Game/main.js
  Games/Country_Guesser_Game/style.css
  assets/images/Country_Guesser_Game.png
  assets/images/country_guesser.png
  assets/images/country_guesser.webp
Labels: gssoc23, level2

#2396 Added new game Solitaire
  Games/Solitaire-up/README.md
  Games/Solitaire-up/index.html
  Games/Solitaire-up/index.js
  Games/Solitaire-up/solitaire.css
  Games/Solitaire/src/bg.jpg
  Games/Solitaire/src/spritesheet.png
  README.md
  assets/images/Solitaire.webp
Labels: gssoc23, level3

#2483 Added Star Trek Trivia Game
  Games/Star_Trek_Trivia/README.md
  Games/Star_Trek_Trivia/assets/star-trek-img.png
  Games/Star_Trek_Trivia/index.html
  Games/Star_Trek_Trivia/script.js
  Games/Star_Trek_Trivia/styles.css
  README.md
  assets/images/starTrek-screenshot.png
Labels: gssoc23, level2

#2507 Json file updated
  assets/js/gamesData.json
Labels: gssoc23, level2

#2510 Slime Attack[GSSOC'23]
  Games/Slime attack game/README.md
  Games/Slime attack game/index.html
  Games/Slime attack game/style.css
  README.md
  assets/images/Slime Attack.jpg
Labels: gssoc23, level2

#2467 Added Tennis Showdown
  Games/Tennis/README.md
  Games/Tennis/assets/paddle.jpeg
  Games/Tennis/index.html
  Games/Tennis/score.js
  Games/Tennis/script.js
  Games/Tennis/style.css
  README.md
  assets/images/Tennis.png
Labels: gssoc23, level3

#2517 tower_of_hanoi improved
  Games/Tower_Of_Hanoi/index.html
  Games/Tower_Of_Hanoi/script.js
  Games/Tower_Of_Hanoi/style.css
Labels: gssoc23, level2

#2495 Digit Dilemma game added
  Games/Digit_Dilemma/README.md
  Games/Digit_Dilemma/Screenshots/Digit_Dilemma.png
  Games/Digit_Dilemma/game.js
  Games/Digit_Dilemma/index.html
  Games/Digit_Dilemma/styles.css
  README.md
  assets/images/Digit_Dilemma.png
Labels: gssoc23, level3

#2530 Quiz game
  .DS_Store
  Games/Quiz_it_out/README.md
  Games/Quiz_it_out/demo.js
  Games/Quiz_it_out/index.html
  Games/Quiz_it_out/script.js
  Games/Quiz_it_out/style.css
  README.md
  assets/.DS_Store
  assets/images/.DS_Store
  assets/images/Quiz_it_out.png
Labels: gssoc23, level2, Ready to merge, under review

#2540 [Fixes: #2427] Added Match color game
  Games/Match_Color_Game/README.md
  Games/Match_Color_Game/index.html
  Games/Match_Color_Game/script.js
  README.md
  assets/images/Match_Color_Game.png
Labels: gssoc23, level2, Ready to merge, under review

#2469 Added block buster game
  Games/Block_Buster/README.md
  Games/Block_Buster/index.html
  Games/Block_Buster/script.js
  Games/Block_Buster/styles.css
  README.md
  assets/images/Block_Buster.png
Labels: gssoc23, level2, Ready to merge

#2548 Background of Memory Game changed
  Games/Memory_Game/style.css
Labels: gssoc23, Ready to merge, level1

#2511 fixed game data and image links
  README.md
  assets/js/gamesData.json
Labels: gssoc23, level2, Ready to merge, Fixed

#2513 [GSSoC'23] Illusion Game Completed
  Games/Illusion/Illusion.png
  Games/Illusion/Illusion.py
  Games/Illusion/README.md
  README.md
  assets/images/Illusion.png
Labels: gssoc23, level2, Ready to merge 🥳, under review

#2545 #2497 New game added
  Games/Guess_The_Ball/README.md
  Games/Guess_The_Ball/index.html
  Games/Guess_The_Ball/script.js
  Games/Guess_The_Ball/styles.css
  README.md
  assets/images/Guess_The_Ball.png
Labels: gssoc23, level2, Ready to merge 🥳, under review

#2553 'Catch me game' Design Enhancement
  Games/Catch_me_game/index.html
  Games/Catch_me_game/style.css
Labels: gssoc23, Ready to merge 🥳, level1

#2555 Added doremon puzzle Issue: #2554
  Games/Doremon_Puzzle/Assets/1.jpg
  Games/Doremon_Puzzle/Assets/10.jpg
  Games/Doremon_Puzzle/Assets/2.jpg
  Games/Doremon_Puzzle/Assets/3.jpg
  Games/Doremon_Puzzle/Assets/4.jpg
  Games/Doremon_Puzzle/Assets/5.jpg
  Games/Doremon_Puzzle/Assets/6.jpg
  Games/Doremon_Puzzle/Assets/7.jpg
  Games/Doremon_Puzzle/Assets/8.jpg
  Games/Doremon_Puzzle/Assets/9.jpg
  Games/Doremon_Puzzle/Assets/logo.png
  Games/Doremon_Puzzle/README.md
  Games/Doremon_Puzzle/index.html
  Games/Doremon_Puzzle/puzzle.css
  Games/Doremon_Puzzle/puzzle.js
  README.md
  assets/images/Doremon_Puzzle.png
Labels: gssoc23, level2, Ready to merge 🥳

#2560 Update README.md file for Pokedex Game
  Games/Pokedex/README.md
Labels: gssoc23, Ready to merge 🥳, level1

#2576 Added Rock Paper Scissors Lizard Spock
  Games/Rock_Paper_Scissors_Lizard_Spock/README.md
  Games/Rock_Paper_Scissors_Lizard_Spock/index.html
  Games/Rock_Paper_Scissors_Lizard_Spock/script.js
  Games/Rock_Paper_Scissors_Lizard_Spock/styles.css
  README.md
  assets/images/rock_paper_scissors_lizard_spock.png
Labels: gssoc23, level2, Ready to merge 🥳

#2558 Lighthouse score improved
  Games/2048/index.html
  Games/Green Mahjong/index.html
  Games/Snake_Ladder/index.html
  assets/images/Alphabet_Learning_Game.webp
  assets/images/Bit_Maze_Platformer_Maze.webp
  assets/images/Brain Color Mastermind.webp
  assets/images/Cosmic_Coin_Collector.webp
  assets/images/Country_Guesser_Game.webp
  assets/images/Crack_The_Code.webp
  assets/images/Flag_Guess_Game.webp
  assets/images/Guess_The_Number.webp
  assets/images/Lizard_Spock_Game.webp
  assets/images/Math_Game.webp
  assets/images/Number_Sliding_Puzzle_Game.webp
  assets/images/Observe the Cloud.webp
  assets/images/Pikachu_Volleyball.webp
  assets/images/Poke_Guess_Blitz.webp
  assets/images/Shadow_PokeGuess.webp
  assets/images/Skeleathon.webp
  assets/images/cross_the_road.webp
  assets/images/reactiontime.webp
  assets/index_old.html
  assets/js/gamesData.json
  assets/js/index.js
  assets/js/script.js
  index.html
Labels: gssoc23, level2, Ready to merge 🥳

#2563 Trivia Game background changed
  Games/Trivia_It/style.css
Labels: gssoc23, Ready to merge 🥳, level1

#2571 Guess the celebrity using two pictures
  Games/Guess_The_Celeb/README.md
  Games/Guess_The_Celeb/android-chrome-192x192.png
  Games/Guess_The_Celeb/android-chrome-512x512.png
  Games/Guess_The_Celeb/apple-touch-icon.png
  Games/Guess_The_Celeb/assets/css/style.css
  Games/Guess_The_Celeb/assets/img/aishwaryarai_1.jpg
  Games/Guess_The_Celeb/assets/img/aishwaryarai_2.jpg
  Games/Guess_The_Celeb/assets/img/amitabhbachchan_1.jpg
  Games/Guess_The_Celeb/assets/img/amitabhbachchan_2.jpg
  Games/Guess_The_Celeb/assets/img/angelinajolie_1.jpg
  Games/Guess_The_Celeb/assets/img/angelinajolie_2.jpg
  Games/Guess_The_Celeb/assets/img/cristianoronaldo_1.jpg
  Games/Guess_The_Celeb/assets/img/cristianoronaldo_2.jpg
  Games/Guess_The_Celeb/assets/img/emmawatson_1.jpg
  Games/Guess_The_Celeb/assets/img/emmawatson_2.jpg
  Games/Guess_The_Celeb/assets/img/hritikroshan_1.jpg
  Games/Guess_The_Celeb/assets/img/hritikroshan_2.jpg
  Games/Guess_The_Celeb/assets/img/leonardodicaprio_1.jpg
  Games/Guess_The_Celeb/assets/img/leonardodicaprio_2.jpg
  Games/Guess_The_Celeb/assets/img/leonelmessi_1.jpg
  Games/Guess_The_Celeb/assets/img/leonelmessi_2.jpg
  Games/Guess_The_Celeb/assets/img/shahrukhkhan_1.jpg
  Games/Guess_The_Celeb/assets/img/shahrukhkhan_2.jpg
  Games/Guess_The_Celeb/assets/img/souravganguly_1.jpg
  Games/Guess_The_Celeb/assets/img/souravganguly_2.jpg
  Games/Guess_The_Celeb/assets/img/tomcruise_1.jpg
  Games/Guess_The_Celeb/assets/img/tomcruise_2.jpg
  Games/Guess_The_Celeb/assets/img/viratkohli_1.jpg
  Games/Guess_The_Celeb/assets/img/viratkohli_2.jpg
  Games/Guess_The_Celeb/assets/js/index.js
  Games/Guess_The_Celeb/favicon-16x16.png
  Games/Guess_The_Celeb/favicon-32x32.png
  Games/Guess_The_Celeb/favicon.ico
  Games/Guess_The_Celeb/index.html
  Games/Guess_The_Celeb/site.webmanifest
  README.md
  assets/images/Guess_The_Celeb.png
  assets/images/Guess_The_Celeb.webp
Labels: gssoc23, Pending, level3, changes requested, Ready to merge 🥳

#2599 Elemental riddles
  Games/Elemental Riddles/README.md
  Games/Elemental Riddles/index.html
  Games/Elemental Riddles/script.js
  Games/Elemental Riddles/style.css
  README.md
  assets/images/Elemental_Riddles.png
Labels: gssoc23, level3, Ready to merge 🥳

#2585 [GSSoC'23] Enlisting all the contributors
  assets/css/contributors.css
  assets/js/contributors.js
  index.html
Labels: enhancement, gssoc23, level2, Ready to merge 🥳

#2591 Opensource
  assets/css/style.css
  assets/images/Screenshot 2023-07-23 215605.png
  assets/images/image.png.png
Labels: gssoc23, Ready to merge 🥳, level1, Fixed

#2577 Falling Ball
  Games/Falling_Ball/README.md
  Games/Falling_Ball/index.html
  Games/Falling_Ball/script.js
  Games/Falling_Ball/style.css
  README.md
  assets/images/Falling_Ball.png
Labels: gssoc23, level2, Ready to merge 🥳, under review

#2578 hit the target game
  Games/Hit_Target/README.md
  Games/Hit_Target/image.png
  Games/Hit_Target/index.html
  Games/Hit_Target/script.js
  Games/Hit_Target/styles.css
  README.md
  assets/images/Hit_Target.png
Labels: gssoc23, level2

#2611 Fixed Scroll To Top Button & Reduced Overlap between Contributor Cards/Pictures
  assets/css/contributors.css
  assets/css/style.css
Labels: gssoc23, Ready to merge 🥳, level1, Fixed

#2627 [GSSoC'23] Animal Match Game Enhacement completed
  Games/Animal_Match_Game/README.md
  Games/Animal_Match_Game/index.html
  Games/Animal_Match_Game/script.js
  Games/Animal_Match_Game/style.css
  assets/images/Animal_Match_Game.png
  assets/images/Animal_Match_Game.webp
Labels: gssoc23, level2, Ready to merge 🥳

#2632 Color switch challenger added
  Games/color_switch_challenger/README.md
  Games/color_switch_challenger/index.html
  Games/color_switch_challenger/script.js
  Games/color_switch_challenger/style.css
  README.md
  assets/images/color_switch_challenger.png
Labels: gssoc23, level3, Ready to merge 🥳

#2623 [Bug]: Correcting name convention of many games in the Repo and also updating the README.md [gssoc23]
  Games/AI_CHESS_Game/chess.png
  Games/AI_CHESS_Game/index.html
  Games/AI_CHESS_Game/readme.md
  Games/AI_CHESS_Game/script.js
  Games/AI_CHESS_Game/style.css
  Games/Observe_the_Cloud/README.md
  Games/Observe_the_Cloud/game.js
  Games/Observe_the_Cloud/images/bg.gif
  Games/Observe_the_Cloud/images/cloud.png
  Games/Observe_the_Cloud/index.html
  Games/Observe_the_Cloud/style.css
  Games/Stone_Paper_Scissor/.babelrc.json
  Games/Stone_Paper_Scissor/.eslintrc.json
  Games/Stone_Paper_Scissor/.gitignore
  Games/Stone_Paper_Scissor/.prettierrc.json
  Games/Stone_Paper_Scissor/README.md
  Games/Stone_Paper_Scissor/config/dummy.js
  Games/Stone_Paper_Scissor/config/paths.js
  Games/Stone_Paper_Scissor/config/webpack.common.js
  Games/Stone_Paper_Scissor/config/webpack.dev.js
  Games/Stone_Paper_Scissor/config/webpack.prod.js
  Games/Stone_Paper_Scissor/index.html
  Games/Stone_Paper_Scissor/package-lock.json
  Games/Stone_Paper_Scissor/package.json
  Games/Stone_Paper_Scissor/postcss.config.js
  Games/Stone_Paper_Scissor/public/dumy.js
  Games/Stone_Paper_Scissor/public/human.png
  Games/Stone_Paper_Scissor/public/paper.png
  Games/Stone_Paper_Scissor/public/robot.gif
  Games/Stone_Paper_Scissor/public/rock.png
  Games/Stone_Paper_Scissor/public/scissors.png
  Games/Stone_Paper_Scissor/script.js
  Games/Stone_Paper_Scissor/src/dummy.js
  Games/Stone_Paper_Scissor/src/fonts/8BITWONDERNominal.woff
  Games/Stone_Paper_Scissor/src/fonts/8BITWONDERNominal.woff2
  Games/Stone_Paper_Scissor/src/fonts/dumy.js
  Games/Stone_Paper_Scissor/src/images/dumy.js
  Games/Stone_Paper_Scissor/src/images/favicon.png
  Games/Stone_Paper_Scissor/src/index.js
  Games/Stone_Paper_Scissor/src/js/CameraConfig.js
  Games/Stone_Paper_Scissor/src/js/Gestures.js
  Games/Stone_Paper_Scissor/src/js/Prediction.js
  Games/Stone_Paper_Scissor/src/js/SampleImage.js
  Games/Stone_Paper_Scissor/src/js/UI.js
  Games/Stone_Paper_Scissor/src/js/dumy.js
  Games/Stone_Paper_Scissor/src/styles/_game.scss
  Games/Stone_Paper_Scissor/src/styles/_variables.scss
  Games/Stone_Paper_Scissor/src/styles/dumy.js
  Games/Stone_Paper_Scissor/src/styles/index.scss
  Games/Stone_Paper_Scissor/src/template.html
  Games/Stone_Paper_Scissor/style.css
  Games/The_labyrinth_of_death/README.md
  Games/The_labyrinth_of_death/engine.js
  Games/The_labyrinth_of_death/index.html
  README.md
Labels: gssoc23, level3, Ready to merge 🥳

#2636 Updated main README.md
  README.md
Labels: documentation, gssoc23, Ready to merge 🥳, level1

#2619 fix: Improved Footer UI in Main Page
  index.html
Labels: gssoc23, Ready to merge 🥳, level1

#2648 Made Page Numbers scroll to top on clicking
  assets/js/script.js
Labels: enhancement, good first issue, gssoc23, Ready to merge 🥳, level1

#2610 New Game: Simon Says
  Games/simon says/Readme.md
  Games/simon says/script.js
  Games/simon says/simon.html
  Games/simon says/styles.css
Labels: gssoc23, level2, Ready to merge 🥳

#2625 typing speed test is updated
  Games/Typing_Speed_Test_Game/index.html
  Games/Typing_Speed_Test_Game/style.css
Labels: gssoc23, level2, Ready to merge 🥳

#2662 Updateed the game styling so now it looks better also imporved functionality
  Games/Hit_Target/image.png
  Games/Hit_Target/index.html
  Games/Hit_Target/script.js
  Games/Hit_Target/styles.css
  assets/images/Hit_Target.png
Labels: gssoc23, level2, Ready to merge 🥳

#2671 [GSSoC'23] Avoider Game Enhancement completed
  Games/Avoider_Game/README.md
  Games/Avoider_Game/app.js
  Games/Avoider_Game/assets/bgMusic.mp3
  Games/Avoider_Game/assets/boy.png
  Games/Avoider_Game/assets/demon.png
  Games/Avoider_Game/assets/gameOver.wav
  Games/Avoider_Game/assets/move.mp3
  Games/Avoider_Game/index.html
  Games/Avoider_Game/style.css
  assets/images/Avoider_Game.png
  assets/images/Avoider_Game.webp
Labels: enhancement, gssoc23, level2, Ready to merge 🥳

#2665 Added Bash mole game [Gssoc'23]
  Games/Bash_mole/README.md
  Games/Bash_mole/Screenshot 2023-07-29 162654-1.png
  Games/Bash_mole/Screenshot 2023-07-29 162654.png
  Games/Bash_mole/app.js
  Games/Bash_mole/assets/mole-logo.png
  Games/Bash_mole/assets/mole.png
  Games/Bash_mole/assets/whack.png
  Games/Bash_mole/index.html
  Games/Bash_mole/style.css
  assets/images/Bash_mole.png
Labels: gssoc23, level3, Ready to merge 🥳

#2695 Search container focus
  assets/js/index.js
  index.html
Labels: good first issue, gssoc23, Ready to merge 🥳, level1
