Repository kunjgit/GameZone, pull requests merged in 2023-05, with the labels that each got.

#59 Adding Snake Game
  Games/Snake_Game/README.md
  Games/Snake_Game/index.html
  Games/Snake_Game/script.js
  Games/Snake_Game/style.css
  README.md
  assets/images/Snake_Game.png
  index.html
Labels: GSSoC23, level3

#62 Dino Runner
  Games/Dino_Runner_Game/README.md
  Games/Dino_Runner_Game/bg.png
  Games/Dino_Runner_Game/dino.png
  Games/Dino_Runner_Game/dinosaur-monuments-svgrepo-com.svg
  Games/Dino_Runner_Game/dragon.png
  Games/Dino_Runner_Game/gameover.mp3
  Games/Dino_Runner_Game/index.html
  Games/Dino_Runner_Game/music.mp3
  Games/Dino_Runner_Game/script.js
  Games/Dino_Runner_Game/style.css
  README.md
  assets/images/Dino_Runner_Game.png
  index.html
Labels: GSSoC23, New Game 🎮, level3

#246 Added Instructions in Simon game with screenshot in readme file (#69)
  Games/Simon_Game_Challenge/README.md
  Games/Simon_Game_Challenge/index.html
  Games/Simon_Game_Challenge/styles.css
  assets/animations/SimonVideo (2).gif
  assets/images/Simon-game.png
  assets/images/Simon_Game_Challenge.png
Labels: GSSoC23, level2

#263 Created a Ludo_Game
  Games/Ludo_Game/.prettierrc
  Games/Ludo_Game/README.md
  Games/Ludo_Game/dice-1.png
  Games/Ludo_Game/dice-2.png
  Games/Ludo_Game/dice-3.png
  Games/Ludo_Game/dice-4.png
  Games/Ludo_Game/dice-5.png
  Games/Ludo_Game/dice-6.png
  Games/Ludo_Game/dice-six-faces-five.svg
  Games/Ludo_Game/dice-six-faces-four.svg
  Games/Ludo_Game/dice-six-faces-one.svg
  Games/Ludo_Game/dice-six-faces-six.svg
  Games/Ludo_Game/dice-six-faces-three.svg
  Games/Ludo_Game/dice-six-faces-two.svg
  Games/Ludo_Game/index.html
  Games/Ludo_Game/script.js
  Games/Ludo_Game/style.css
  README.md
  assets/images/Ludo_Game.png
Labels: GSSoC23, level3

#339 Made website responsive for screen width larger than 1024px
  assets/css/style.css
Labels: GSSoC23, level1

#302 [New Game]:Atari breakout
  Games/Atari_breakout/README.md
  Games/Atari_breakout/assets/lives.png
  Games/Atari_breakout/index.html
  Games/Atari_breakout/script.js
  Games/Atari_breakout/styles.css
  README.md
  assets/images/Atari_breakout.png
Labels: GSSoC23, level3

#345 [New Game]: Chrome Dinosaur game added.
  Games/Chrome_Dinosaur_Game/README.md
  Games/Chrome_Dinosaur_Game/assets/big-cactus1.png
  Games/Chrome_Dinosaur_Game/assets/big-cactus2.png
  Games/Chrome_Dinosaur_Game/assets/big-cactus3.png
  Games/Chrome_Dinosaur_Game/assets/bird1.png
  Games/Chrome_Dinosaur_Game/assets/bird2.png
  Games/Chrome_Dinosaur_Game/assets/cactus1.png
  Games/Chrome_Dinosaur_Game/assets/cactus2.png
  Games/Chrome_Dinosaur_Game/assets/cactus3.png
  Games/Chrome_Dinosaur_Game/assets/cloud.png
  Games/Chrome_Dinosaur_Game/assets/dino-dead.png
  Games/Chrome_Dinosaur_Game/assets/dino-duck1.png
  Games/Chrome_Dinosaur_Game/assets/dino-duck2.png
  Games/Chrome_Dinosaur_Game/assets/dino-jump.png
  Games/Chrome_Dinosaur_Game/assets/dino-run1.png
  Games/Chrome_Dinosaur_Game/assets/dino-run2.png
  Games/Chrome_Dinosaur_Game/assets/dino.png
  Games/Chrome_Dinosaur_Game/assets/game-over.png
  Games/Chrome_Dinosaur_Game/assets/reset.png
  Games/Chrome_Dinosaur_Game/assets/track.png
  Games/Chrome_Dinosaur_Game/index.html
  Games/Chrome_Dinosaur_Game/script.js
  Games/Chrome_Dinosaur_Game/style.css
  README.md
  assets/images/Chrome_dinosaur_runner.png
Labels: GSSoC23, level3

#312 [New Game]: Guess the colour by RGB.
  Games/Colour_Guessing_Game/README.md
  Games/Colour_Guessing_Game/index.html
  Games/Colour_Guessing_Game/script.js
  Games/Colour_Guessing_Game/styles.css
  README.md
  assets/images/Colour_Guessing_Game.png
Labels: GSSoC23, level3

#395 Guess the number
  Games/Guess_The_Number/README.md
  Games/Guess_The_Number/Screenshot.png
  Games/Guess_The_Number/Screenshots/Screenshot.png
  Games/Guess_The_Number/index.html
  Games/Guess_The_Number/main.js
  Games/Guess_The_Number/style.css
  README.md
  assets/images/Guess_The_Number.png
Labels: GSSoC23, level3

#405 Changed Readme.MD to readme.md
  Games/race_car/README.md
  Games/race_car/images/1icon.png
  Games/race_car/images/car04.png
  Games/race_car/images/cloud.jpg
  Games/race_car/images/finish.png
  Games/race_car/images/hero.png
  Games/race_car/images/icon.png
  Games/race_car/images/tree.png
  Games/race_car/index.html
  Games/race_car/script.js
  Games/race_car/style.css
  README.md
  assets/images/race_car.png
Labels: GSSoC23, level3

#415 [New Game]: Alien shooters added.
  Games/Alien_Shooters/README.md
  Games/Alien_Shooters/assets/0.png
  Games/Alien_Shooters/assets/1.png
  Games/Alien_Shooters/assets/2.png
  Games/Alien_Shooters/assets/3.png
  Games/Alien_Shooters/assets/shooter.png
  Games/Alien_Shooters/index.html
  Games/Alien_Shooters/script.js
  Games/Alien_Shooters/style.css
  README.md
  assets/images/Alien_Shooter.png
Labels: GSSoC23, level3

#422 [#151 issue] Added Fruit_Ninja
  Games/Fruit_Ninja/assets/game_assets/apple-1.png
  Games/Fruit_Ninja/assets/game_assets/apple-2.png
  Games/Fruit_Ninja/assets/game_assets/apple.png
  Games/Fruit_Ninja/assets/game_assets/background.jpg
  Games/Fruit_Ninja/assets/game_assets/banana-1.png
  Games/Fruit_Ninja/assets/game_assets/banana-2.png
  Games/Fruit_Ninja/assets/game_assets/banana.png
  Games/Fruit_Ninja/assets/game_assets/boom.png
  Games/Fruit_Ninja/assets/game_assets/fruit.png
  Games/Fruit_Ninja/assets/game_assets/fruitMode.png
  Games/Fruit_Ninja/assets/game_assets/game-over.png
  Games/Fruit_Ninja/assets/game_assets/home-mask.png
  Games/Fruit_Ninja/assets/game_assets/new-game.png
  Games/Fruit_Ninja/assets/game_assets/ninja.png
  Games/Fruit_Ninja/assets/game_assets/peach-1.png
  Games/Fruit_Ninja/assets/game_assets/peach-2.png
  Games/Fruit_Ninja/assets/game_assets/peach.png
  Games/Fruit_Ninja/assets/game_assets/score.png
  Games/Fruit_Ninja/assets/game_assets/strawberry-1.png
  Games/Fruit_Ninja/assets/game_assets/strawberry-2.png
  Games/Fruit_Ninja/assets/game_assets/strawberry.png
  Games/Fruit_Ninja/assets/game_assets/watermelon-1.png
  Games/Fruit_Ninja/assets/game_assets/watermelon-2.png
  Games/Fruit_Ninja/assets/game_assets/watermelon.png
  Games/Fruit_Ninja/assets/game_assets/website_icon.ico
  Games/Fruit_Ninja/assets/game_assets/x1.png
  Games/Fruit_Ninja/assets/game_assets/x2.png
  Games/Fruit_Ninja/assets/game_assets/x3.png
  Games/Fruit_Ninja/assets/game_assets/xx1.png
  Games/Fruit_Ninja/assets/game_assets/xx2.png
  Games/Fruit_Ninja/assets/game_assets/xx3.png
  Games/Fruit_Ninja/assets/home_page_assets/Fruit-Ninja-Katsuro.png
  Games/Fruit_Ninja/assets/home_page_assets/logo.png
  Games/Fruit_Ninja/assets/home_page_assets/temple.jpeg
  Games/Fruit_Ninja/assets/screenshots/Fruit_Ninja_Screenshot_1.png
  Games/Fruit_Ninja/assets/screenshots/Fruit_Ninja_Screenshot_2.png
  Games/Fruit_Ninja/assets/screenshots/Fruit_Ninja_Screenshot_3.png
  Games/Fruit_Ninja/index.html
  Games/Fruit_Ninja/js/fruit.js
  Games/Fruit_Ninja/js/main.js
  Games/Fruit_Ninja/js/swords.js
  Games/Fruit_Ninja/main.html
  Games/Fruit_Ninja/p5/.DS_Store
  Games/Fruit_Ninja/p5/addons/.DS_Store
  Games/Fruit_Ninja/p5/addons/p5.dom.js
  Games/Fruit_Ninja/p5/addons/p5.dom.min.js
  Games/Fruit_Ninja/p5/addons/p5.sound.js
  Games/Fruit_Ninja/p5/addons/p5.sound.min.js
  Games/Fruit_Ninja/p5/p5.js
  Games/Fruit_Ninja/p5/p5.min.js
  Games/Fruit_Ninja/readme.md
  Games/Fruit_Ninja/sounds/boom.mp3
  Games/Fruit_Ninja/sounds/missed.mp3
  Games/Fruit_Ninja/sounds/over.mp3
  Games/Fruit_Ninja/sounds/splatter.mp3
  Games/Fruit_Ninja/sounds/start.mp3
  Games/Fruit_Ninja/style.css
  README.md
  assets/images/Fruit_Ninja_Thumbnail.png
Labels: GSSoC23, level3

#426 Enhancement of Master_typing
  Games/Master_Typing/README.md
  Games/Master_Typing/index.html
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
  assets/images/Master_Typing.png
Labels: GSSoC23, level2

#427 [New Game]: Doodle jump
  Games/Doodle_Jump/README.md
  Games/Doodle_Jump/assets/doodlejumpbg.png
  Games/Doodle_Jump/assets/doodler-left.png
  Games/Doodle_Jump/assets/doodler-right.png
  Games/Doodle_Jump/assets/platform-broken.png
  Games/Doodle_Jump/assets/platform.png
  Games/Doodle_Jump/index.html
  Games/Doodle_Jump/script.js
  Games/Doodle_Jump/style.css
  README.md
  assets/images/Doodle_Jump_Game.png
Labels: GSSoC23, level3

#443 Aplhabet Game added
  Games/Alphabet/README.md
  Games/Alphabet/images/apple.png
  Games/Alphabet/images/ball.png
  Games/Alphabet/images/cat.png
  Games/Alphabet/images/dog.png
  Games/Alphabet/images/elephant.png
  Games/Alphabet/images/fish.png
  Games/Alphabet/images/fox.png
  Games/Alphabet/images/grass.png
  Games/Alphabet/images/hat.png
  Games/Alphabet/images/insect.png
  Games/Alphabet/images/jar.png
  Games/Alphabet/images/kite.png
  Games/Alphabet/images/lamp.png
  Games/Alphabet/images/monkey.png
  Games/Alphabet/images/nose.png
  Games/Alphabet/images/ocean.png
  Games/Alphabet/images/parrot.png
  Games/Alphabet/images/queen.png
  Games/Alphabet/images/rat.png
  Games/Alphabet/images/sun.png
  Games/Alphabet/images/tap.png
  Games/Alphabet/images/umbrella.png
  Games/Alphabet/images/violin.png
  Games/Alphabet/images/water.png
  Games/Alphabet/images/yellow.png
  Games/Alphabet/images/zebra.png
  Games/Alphabet/index.html
  Games/Alphabet/index.js
  Games/Alphabet/sounds/a.mp3
  Games/Alphabet/sounds/b.mp3
  Games/Alphabet/sounds/c.mp3
  Games/Alphabet/sounds/d.mp3
  Games/Alphabet/sounds/e.mp3
  Games/Alphabet/sounds/f.mp3
  Games/Alphabet/sounds/g.mp3
  Games/Alphabet/sounds/h.mp3
  Games/Alphabet/sounds/i.mp3
  Games/Alphabet/sounds/j.mp3
  Games/Alphabet/sounds/k.mp3
  Games/Alphabet/sounds/l.mp3
  Games/Alphabet/sounds/m.mp3
  Games/Alphabet/sounds/n.mp3
  Games/Alphabet/sounds/o.mp3
  Games/Alphabet/sounds/p.mp3
  Games/Alphabet/sounds/q.mp3
  Games/Alphabet/sounds/r.mp3
  Games/Alphabet/sounds/s.mp3
  Games/Alphabet/sounds/t.mp3
  Games/Alphabet/sounds/u.mp3
  Games/Alphabet/sounds/v.mp3
  Games/Alphabet/sounds/w.mp3
  Games/Alphabet/sounds/x.mp3
  Games/Alphabet/sounds/y.mp3
  Games/Alphabet/sounds/z.mp3
  Games/Alphabet/styles.css
  README.md
  assets/images/Alphabet.png
Labels: GSSoC23, level3

#447 [New Game]: Candy Crush
  Games/Candy_Crush/README.md
  Games/Candy_Crush/assets/Blue-Striped-Horizontal.png
  Games/Candy_Crush/assets/Blue-Striped-Vertical.png
  Games/Candy_Crush/assets/Blue-Wrapped.png
  Games/Candy_Crush/assets/Blue.png
  Games/Candy_Crush/assets/Choco.png
  Games/Candy_Crush/assets/Green-Striped-Horizontal.png
  Games/Candy_Crush/assets/Green-Striped-Vertical.png
  Games/Candy_Crush/assets/Green-Wrapped.png
  Games/Candy_Crush/assets/Green.png
  Games/Candy_Crush/assets/Orange-Striped-Horizontal.png
  Games/Candy_Crush/assets/Orange-Striped-Vertical.png
  Games/Candy_Crush/assets/Orange-Wrapped.png
  Games/Candy_Crush/assets/Orange.png
  Games/Candy_Crush/assets/Purple-Striped-Horizontal.png
  Games/Candy_Crush/assets/Purple-Striped-Vertical.png
  Games/Candy_Crush/assets/Purple-Wrapped.png
  Games/Candy_Crush/assets/Purple.png
  Games/Candy_Crush/assets/Red-Striped-Horizontal.png
  Games/Candy_Crush/assets/Red-Striped-Vertical.png
  Games/Candy_Crush/assets/Red-Wrapped.png
  Games/Candy_Crush/assets/Red.png
  Games/Candy_Crush/assets/Yellow-Striped-Horizontal.png
  Games/Candy_Crush/assets/Yellow-Striped-Vertical.png
  Games/Candy_Crush/assets/Yellow-Wrapped.png
  Games/Candy_Crush/assets/Yellow.png
  Games/Candy_Crush/assets/blank.png
  Games/Candy_Crush/index.html
  Games/Candy_Crush/script.js
  Games/Candy_Crush/style.css
  README.md
  assets/images/candy_crush.png
Labels: GSSoC23, level3

#463 #248 Word_Association_Game
  Games/Word_Association_Game/README.md
  Games/Word_Association_Game/Screenshots/wa1.png
  Games/Word_Association_Game/Screenshots/wa2.png
  Games/Word_Association_Game/Screenshots/wa3.png
  Games/Word_Association_Game/Screenshots/wa4.png
  Games/Word_Association_Game/Screenshots/wa5.png
  Games/Word_Association_Game/app.js
  Games/Word_Association_Game/index.html
  Games/Word_Association_Game/level1.js
  Games/Word_Association_Game/level2.js
  Games/Word_Association_Game/level3.js
  Games/Word_Association_Game/level4.js
  Games/Word_Association_Game/level5.js
  Games/Word_Association_Game/styles.css
  README.md
  assets/images/Word_Association.png
Labels: GSSoC23, level3

#442 Footer being sticky #438
  assets/css/style.css
  index.html
Labels: GSSoC23, level1

#118 Flapp Bird Added #22 Resolved
  Games/Flappy_Bird/README.md
  Games/Flappy_Bird/assets/bottompipe.png
  Games/Flappy_Bird/assets/flappybird.png
  Games/Flappy_Bird/assets/flappybirdbg.png
  Games/Flappy_Bird/assets/toppipe.png
  Games/Flappy_Bird/index.html
  Games/Flappy_Bird/script.js
  Games/Flappy_Bird/style.css
  README.md
  assets/images/Flappy_Bird_Game.png
Labels: GSSoC23, level3

#147 Added "Trivia It"
  Games/Trivia_It/README.md
  Games/Trivia_It/index.html
  Games/Trivia_It/js/questions.js
  Games/Trivia_It/js/script.js
  Games/Trivia_It/style.css
  README.md
  assets/images/Trivia_It.png
  index.html
Labels: GSSoC23, level3

#200 Minesweeper
  Games/Minesweeper/Minesweeper.png
  Games/Minesweeper/Minesweeper1.png
  Games/Minesweeper/README.md
  Games/Minesweeper/index.html
  Games/Minesweeper/script.js
  Games/Minesweeper/styles.css
  README.md
  assets/images/Minesweeper.png
Labels: GSSoC23, level3

#252 Dice Showdown Game Added to the Game folder of the repository.
  Games/Dice_Showdown_Game/README.md
  Games/Dice_Showdown_Game/dicee.html
  Games/Dice_Showdown_Game/images/dice1.png
  Games/Dice_Showdown_Game/images/dice2.png
  Games/Dice_Showdown_Game/images/dice3.png
  Games/Dice_Showdown_Game/images/dice4.png
  Games/Dice_Showdown_Game/images/dice5.png
  Games/Dice_Showdown_Game/images/dice6.png
  Games/Dice_Showdown_Game/index.js
  Games/Dice_Showdown_Game/styles.css
  README.md
  assets/images/Dice_Game.png
Labels: GSSoC23, level3

#287 To Add Bricker Breaker Game
  Games/Brick_Breaker/README.md
  Games/Brick_Breaker/index.html
  Games/Brick_Breaker/script.js
  Games/Brick_Breaker/styles.css
  README.md
  assets/images/Brick_Breaker.png
Labels: GSSoC23, level3

#366 mute/unmute feature added, fixes #330
  Games/Dino_Runner_Game/index.html
  Games/Dino_Runner_Game/mute.png
  Games/Dino_Runner_Game/script.js
  Games/Dino_Runner_Game/style.css
  Games/Dino_Runner_Game/unmute.png
Labels: GSSoC23, level2

#520 Magic Square
  Games/Magic_Square/Readme.md
  Games/Magic_Square/index.html
  Games/Magic_Square/script.js
  Games/Magic_Square/style.css
  README.md
  assets/images/Magic_Square.JPG
Labels: GSSoC23, level3

#356 restarts automatically and no scrolling up down pressing arrows:SNAKE
  Games/Snake_Game/script.js
  Games/Snake_Game/style.css
Labels: GSSoC23, level2, Ready to merge

#477 Fix Text in README
  README.md
Labels: GSSoC23, Ready to merge, level1

#504 Fix some Typos
  Games/Simon_Game_Challenge/README.md
Labels: GSSoC23, level1

#509 Added Lighthouse Game
  Games/Lighthouse/Game_night.png
  Games/Lighthouse/Game_start.png
  Games/Lighthouse/Gameover.png
  Games/Lighthouse/Lighthouse_1.png
  Games/Lighthouse/README.md
  Games/Lighthouse/index.html
  Games/Lighthouse/script.js
  Games/Lighthouse/style.css
  README.md
  assets/animations/Lighthouse.mp4
  assets/images/LightHouse.png
Labels: GSSoC23, level3

#518 added the search bar with improved ui
  assets/css/style.css
  index.html
  package-lock.json
  package.json
Labels: GSSoC23, level2

#521 Lights out game
  Games/Lights_Out/README.md
  Games/Lights_Out/index.html
  Games/Lights_Out/script.js
  Games/Lights_Out/style.css
  README.md
  assets/images/Lights_Out.png
Labels: GSSoC23, level3

#271 Pearl
  Games/Tetris/README.md
  Games/Tetris/index.html
  Games/Tetris/script.js
  Games/Tetris/style.css
  README.md
  assets/images/Tetris.png
Labels: GSSoC23, level3

#536 Planet
  Games/Planet_Defense/README.md
  Games/Planet_Defense/index.html
  Games/Planet_Defense/script.js
  Games/Planet_Defense/space.jpg
  Games/Planet_Defense/style.css
  README.md
  assets/images/Planet_Defense.png
Labels: GSSoC23, level3

#567 Roll_Race game added
  Games/Roll_Race/README.md
  Games/Roll_Race/forest.ico
  Games/Roll_Race/images/bg-bottom.png
  Games/Roll_Race/images/bg.png
  Games/Roll_Race/images/dice/dice1.png
  Games/Roll_Race/images/dice/dice2.png
  Games/Roll_Race/images/dice/dice3.png
  Games/Roll_Race/images/dice/dice4.png
  Games/Roll_Race/images/dice/dice5.png
  Games/Roll_Race/images/dice/dice6.png
  Games/Roll_Race/images/path/path-1.png
  Games/Roll_Race/images/path/path-null.png
  Games/Roll_Race/images/path/path0.png
  Games/Roll_Race/images/path/path1.png
  Games/Roll_Race/images/path/path2.png
  Games/Roll_Race/images/path/path3.png
  Games/Roll_Race/images/path/path4.png
  Games/Roll_Race/images/path/path5.png
  Games/Roll_Race/images/path/path6.png
  Games/Roll_Race/images/path/path7.png
  Games/Roll_Race/images/path/path8.png
  Games/Roll_Race/images/path/pathvictory.png
  Games/Roll_Race/images/red-dice.png
  Games/Roll_Race/index.html
  Games/Roll_Race/index.js
  Games/Roll_Race/style.css
  README.md
  assets/images/Roll_Race.png
Labels: GSSoC23, level3

#600 LIGHT-DARK Theme Switch added !
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: GSSoC23, level2
