Repository kunjgit/GameZone, pull requests merged in 2024-08, with the labels that each got.

#5000 Add Alien Language Translator with Enhanced Features
  Games/Alien_Language_Translator/README.md
  Games/Alien_Language_Translator/images/alien.png
  Games/Alien_Language_Translator/indexes.html
  Games/Alien_Language_Translator/script.js
  Games/Alien_Language_Translator/style.css
  README.md
  assets/images/Alien_Language_Translator.png
Labels: Ready to merge 🥳, level3, gssoc

#5017 Added 2D_Fighting_Game
  Games/2D_Fighting_game/README.md
  Games/2D_Fighting_game/img/background.png
  Games/2D_Fighting_game/img/kenji/Attack1.png
  Games/2D_Fighting_game/img/kenji/Attack2.png
  Games/2D_Fighting_game/img/kenji/Death.png
  Games/2D_Fighting_game/img/kenji/Fall.png
  Games/2D_Fighting_game/img/kenji/Idle.png
  Games/2D_Fighting_game/img/kenji/Jump.png
  Games/2D_Fighting_game/img/kenji/Run.png
  Games/2D_Fighting_game/img/kenji/Take hit.png
  Games/2D_Fighting_game/img/samuraiMack/Attack1.png
  Games/2D_Fighting_game/img/samuraiMack/Attack2.png
  Games/2D_Fighting_game/img/samuraiMack/Death.png
  Games/2D_Fighting_game/img/samuraiMack/Fall.png
  Games/2D_Fighting_game/img/samuraiMack/Idle.png
  Games/2D_Fighting_game/img/samuraiMack/Jump.png
  Games/2D_Fighting_game/img/samuraiMack/Run.png
  Games/2D_Fighting_game/img/samuraiMack/Take Hit - white silhouette.png
  Games/2D_Fighting_game/img/samuraiMack/Take Hit.png
  Games/2D_Fighting_game/img/shop.png
  Games/2D_Fighting_game/index.html
  Games/2D_Fighting_game/index.js
  Games/2D_Fighting_game/js/classes.js
  Games/2D_Fighting_game/js/utils.js
  README.md
  assets/images/2D_Fighting_Game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5032 [new game] : animal name guessing game added
  Games/Animal_Name_Guessing/Readme.md
  Games/Animal_Name_Guessing/game.html
  Games/Animal_Name_Guessing/index.html
  Games/Animal_Name_Guessing/js/results.js
  Games/Animal_Name_Guessing/js/script.js
  Games/Animal_Name_Guessing/results.html
  Games/Animal_Name_Guessing/style.css
  README.md
  assets/images/Animal_Name_Guessing.png
Labels: Ready to merge 🥳, level3, gssoc

#5035 Added Catch the object game
  Games/Catch_The_Objects/README.md
  Games/Catch_The_Objects/index.html
  Games/Catch_The_Objects/script.js
  Games/Catch_The_Objects/styles.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#5036 Added New Game: Ping pong
  Games/Ping_Pong/README.md
  Games/Ping_Pong/index.html
  Games/Ping_Pong/script.js
  Games/Ping_Pong/style.css
  README.md
  assets/images/Ping_Pong.png
Labels: Ready to merge 🥳, level3, gssoc

#4971 Sand Tetris
  Games/sand_tetris/assets/1.md
  Games/sand_tetris/assets/screenshot_sand_tetris.png
  Games/sand_tetris/handleinput.js
  Games/sand_tetris/index.html
  Games/sand_tetris/logo.png
  Games/sand_tetris/piece.js
  Games/sand_tetris/playfield.js
  Games/sand_tetris/readme.md
  Games/sand_tetris/script.js
  Games/sand_tetris/style.css
  README.md
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5052 Added Hole and Mole Game
  Games/Hole_And_Mole_Game/README.md
  Games/Hole_And_Mole_Game/img/hole.png
  Games/Hole_And_Mole_Game/img/mole.png
  Games/Hole_And_Mole_Game/index.html
  Games/Hole_And_Mole_Game/script.js
  Games/Hole_And_Mole_Game/style.css
  README.md
  assets/images/Hole_And_Mole_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4463 New game Language Learner Adventure
  Games/Language_Learner_Adventure/README.md
  Games/Language_Learner_Adventure/index.html
  Games/Language_Learner_Adventure/script.js
  Games/Language_Learner_Adventure/styles.css
  README.md
  assets/images/Language_Learner_Adventure.png
Labels: Ready to merge 🥳, level3, gssoc

#5053 Adding a game smash monty mole, contributing under GSSOC'24
  Games/Smash-Monty-mole-master-main/README.md
  Games/Smash-Monty-mole-master-main/index.html
  Games/Smash-Monty-mole-master-main/mario-bg.jpg
  Games/Smash-Monty-mole-master-main/mole.css
  Games/Smash-Monty-mole-master-main/mole.js
  Games/Smash-Monty-mole-master-main/monty-mole.png
  Games/Smash-Monty-mole-master-main/pipe.png
  Games/Smash-Monty-mole-master-main/piranha-plant.png
  Games/Smash-Monty-mole-master-main/soil.png
  README.md
  assets/images/Screenshot 2024-08-01 002501.png
Labels: Ready to merge 🥳, level3, gssoc

#5065 Added Synonym symphony game
  Games/Synonym_Symphony/README.md
  Games/Synonym_Symphony/images/image_01.png
  Games/Synonym_Symphony/images/image_02.png
  Games/Synonym_Symphony/images/image_03.png
  Games/Synonym_Symphony/images/image_04.png
  Games/Synonym_Symphony/images/image_05.png
  Games/Synonym_Symphony/index.html
  Games/Synonym_Symphony/script.js
  Games/Synonym_Symphony/styles.css
  README.md
  assets/images/Synonym_Symphony.png
Labels: Ready to merge 🥳, level3, gssoc

#5066 navbar changes
  assets/css/contributors.css
  assets/css/cursor_transition.css
  assets/css/navbar.css
  assets/css/scroll.css
  assets/js/cursor_transition.js
  index.html
Labels: level1, Ready to merge 🥳, gssoc

#5067 Updated background color, text appearance, balloons colors, alignment…
  Games/Balloon_Popup/Balloon_Popup.png
  Games/Balloon_Popup/app.js
  Games/Balloon_Popup/ballon.png
  Games/Balloon_Popup/balloon_pop.png
  Games/Balloon_Popup/index.html
  Games/Balloon_Popup/pop.png
  Games/Balloon_Popup/style.css
Labels: level1, Ready to merge 🥳, gssoc

#5069 fix: Made the newsletter section responsive on footer
  assets/css/style.css
Labels: level1, Ready to merge 🥳, gssoc

#5079 Added Sky Jumper Game
  Games/Sky_Jumper/README.md
  Games/Sky_Jumper/game.js
  Games/Sky_Jumper/index.html
  Games/Sky_Jumper/styles.css
  README.md
  assets/images/Sky_Jumper.png
Labels: Ready to merge 🥳, level3, gssoc

#5082 added the game Memory_Card
  Games/Memory_Card/Readme.md
  Games/Memory_Card/index.html
  Games/Memory_Card/script.js
  Games/Memory_Card/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4952 Added Unword It ( reverse dumb-shard multiplayer game )
  Games/Unword_it/asset/Images/Unword_It_gameplay.png
  Games/Unword_it/asset/Images/Unword_It_landing.png
  Games/Unword_it/asset/Images/Unword_It_reveal_letter.png
  Games/Unword_it/asset/Images/Unword_It_successful_guess.png
  Games/Unword_it/asset/Images/Unword_It_times_up.png
  Games/Unword_it/asset/Images/desktop.ini
  Games/Unword_it/index.html
  Games/Unword_it/readme.md
  Games/Unword_it/script.js
  Games/Unword_it/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4962 Added Quiz game
  Games/Quiz_With_Timer/README.md
  Games/Quiz_With_Timer/index.html
  Games/Quiz_With_Timer/js/questions.js
  Games/Quiz_With_Timer/js/script.js
  Games/Quiz_With_Timer/style.css
  README.md
  assets/images/Quiz_With_Timer.png
Labels: level2, Ready to merge 🥳, gssoc

#5057 Added King_Sword_Runner
  Games/King_Sword_Runner/README.md
  Games/King_Sword_Runner/img/background.png
  Games/King_Sword_Runner/img/warrior/Attack1.png
  Games/King_Sword_Runner/img/warrior/Attack2.png
  Games/King_Sword_Runner/img/warrior/Attack3.png
  Games/King_Sword_Runner/img/warrior/Death.png
  Games/King_Sword_Runner/img/warrior/Fall.png
  Games/King_Sword_Runner/img/warrior/FallLeft.png
  Games/King_Sword_Runner/img/warrior/Idle.png
  Games/King_Sword_Runner/img/warrior/IdleLeft.png
  Games/King_Sword_Runner/img/warrior/Jump.png
  Games/King_Sword_Runner/img/warrior/JumpLeft.png
  Games/King_Sword_Runner/img/warrior/Run.png
  Games/King_Sword_Runner/img/warrior/RunLeft.png
  Games/King_Sword_Runner/img/warrior/Take Hit - white silhouette.png
  Games/King_Sword_Runner/img/warrior/Take Hit.png
  Games/King_Sword_Runner/index.html
  Games/King_Sword_Runner/index.js
  Games/King_Sword_Runner/js/classes/CollisionBlock.js
  Games/King_Sword_Runner/js/classes/Player.js
  Games/King_Sword_Runner/js/classes/Sprite.js
  Games/King_Sword_Runner/js/data/collisions.js
  Games/King_Sword_Runner/js/utils.js
  README.md
  assets/images/King_Sword_Runner.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5086 Add Sentence scramble game
  Games/Sentence_Scramble/README.md
  Games/Sentence_Scramble/images/image_01.png
  Games/Sentence_Scramble/images/image_02.png
  Games/Sentence_Scramble/images/image_03.png
  Games/Sentence_Scramble/index.html
  Games/Sentence_Scramble/script.js
  Games/Sentence_Scramble/styles.css
  README.md
  assets/images/Sentence_Scramble.png
Labels: Ready to merge 🥳, level3, gssoc

#5042 Added Icy_tower_game
  Games/Icy_Tower_Game/.babelrc
  Games/Icy_Tower_Game/.eslintrc.json
  Games/Icy_Tower_Game/.github/workflows/linters.yml
  Games/Icy_Tower_Game/.gitignore
  Games/Icy_Tower_Game/.stylelintrc.json
  Games/Icy_Tower_Game/LICENSE
  Games/Icy_Tower_Game/Readme.md
  Games/Icy_Tower_Game/_tests_/getScore.test.js
  Games/Icy_Tower_Game/_tests_/updateScore.test.js
  Games/Icy_Tower_Game/build/project.bundle.js
  Games/Icy_Tower_Game/index.html
  Games/Icy_Tower_Game/package-lock.json
  Games/Icy_Tower_Game/package.json
  Games/Icy_Tower_Game/src/Button.js
  Games/Icy_Tower_Game/src/Config/config.js
  Games/Icy_Tower_Game/src/Model.js
  Games/Icy_Tower_Game/src/Scenes/BootScene.js
  Games/Icy_Tower_Game/src/Scenes/CreditsScene.js
  Games/Icy_Tower_Game/src/Scenes/GameScene.js
  Games/Icy_Tower_Game/src/Scenes/OptionsScene.js
  Games/Icy_Tower_Game/src/Scenes/PreloaderScene.js
  Games/Icy_Tower_Game/src/Scenes/ScoreScene.js
  Games/Icy_Tower_Game/src/Scenes/TitleScene.js
  Games/Icy_Tower_Game/src/assets/Icy_back.png
  Games/Icy_Tower_Game/src/assets/Icy_dude.png
  Games/Icy_Tower_Game/src/assets/Icy_iceberg.png
  Games/Icy_Tower_Game/src/assets/ThemeSong.mp3
  Games/Icy_Tower_Game/src/assets/icy.gif
  Games/Icy_Tower_Game/src/assets/jump.ogg
  Games/Icy_Tower_Game/src/assets/logo.gif
  Games/Icy_Tower_Game/src/assets/platform.png
  Games/Icy_Tower_Game/src/assets/score.JPG
  Games/Icy_Tower_Game/src/assets/singledude.png
  Games/Icy_Tower_Game/src/assets/stair.JPG
  Games/Icy_Tower_Game/src/assets/style.css
  Games/Icy_Tower_Game/src/assets/ui/blue_boxCheckmark.png
  Games/Icy_Tower_Game/src/assets/ui/blue_button02.png
  Games/Icy_Tower_Game/src/assets/ui/blue_button03.png
  Games/Icy_Tower_Game/src/assets/ui/grey_box.png
  Games/Icy_Tower_Game/src/index.js
  Games/Icy_Tower_Game/src/modules/score.js
  Games/Icy_Tower_Game/webpack.config.js
  Games/Icy_Tower_Game/webpack/base.js
  Games/Icy_Tower_Game/webpack/prod.js
  README.md
  assets/animations/Icy_logo.gif
  assets/animations/icy.gif
  assets/audio/ThemeSong.mp3
  assets/images/Icy_back.png
  assets/images/Icy_dude.png
  assets/images/Icy_iceberg.png
  assets/images/Icy_platform.png
  assets/images/Icy_score.JPG
  assets/images/Icy_singledude.png
  assets/images/Icy_stair.JPG
Labels: Ready to merge 🥳, level3, gssoc

#5051 removed redundancies
  assets/js/gamesData.json
Labels: level1, Ready to merge 🥳, gssoc

#5054 added gem cruncher
  Games/Gem_Cruncher/README.md
  Games/Gem_Cruncher/package-lock.json
  Games/Gem_Cruncher/package.json
  Games/Gem_Cruncher/public/Gem_Cruncher - Shortcut.lnk
  Games/Gem_Cruncher/public/assets/bg-blured.png
  Games/Gem_Cruncher/public/assets/match.wav
  Games/Gem_Cruncher/public/assets/target.svg
  Games/Gem_Cruncher/public/assets/tilesheet.png
  Games/Gem_Cruncher/public/assets/tilesheet.webp
  Games/Gem_Cruncher/public/build/bundle.css
  Games/Gem_Cruncher/public/build/bundle.css.map
  Games/Gem_Cruncher/public/build/bundle.js
  Games/Gem_Cruncher/public/build/bundle.js.map
  Games/Gem_Cruncher/public/global.css
  Games/Gem_Cruncher/public/index.html
  Games/Gem_Cruncher/public/pic.png
  Games/Gem_Cruncher/rollup.config.js
  Games/Gem_Cruncher/src/components/App.svelte
  Games/Gem_Cruncher/src/components/Board.svelte
  Games/Gem_Cruncher/src/components/Button.svelte
  Games/Gem_Cruncher/src/components/Game.svelte
  Games/Gem_Cruncher/src/components/GameFooter.svelte
  Games/Gem_Cruncher/src/components/GameHeader.svelte
  Games/Gem_Cruncher/src/components/GameOverModal.svelte
  Games/Gem_Cruncher/src/components/Tile.svelte
  Games/Gem_Cruncher/src/components/_GameHeader.svelte
  Games/Gem_Cruncher/src/components/_LevelTarget.svelte
  Games/Gem_Cruncher/src/main.js
  Games/Gem_Cruncher/src/store/game.actions.js
  Games/Gem_Cruncher/src/store/game.store.js
  Games/Gem_Cruncher/src/store/game.utils.js
  README.md
  assets/images/Gem_Cruncher.png
Labels: Ready to merge 🥳, level3, gssoc

#5095 Added Multiplayer_Shooting_Game
  Games/Multiplayer_Shooting_Game/.gitignore
  Games/Multiplayer_Shooting_Game/.prettierrc
  Games/Multiplayer_Shooting_Game/backend.js
  Games/Multiplayer_Shooting_Game/package-lock.json
  Games/Multiplayer_Shooting_Game/package.json
  Games/Multiplayer_Shooting_Game/public/img/webb-dark.png
  Games/Multiplayer_Shooting_Game/public/index.html
  Games/Multiplayer_Shooting_Game/public/js/classes/Enemy.js
  Games/Multiplayer_Shooting_Game/public/js/classes/Particle.js
  Games/Multiplayer_Shooting_Game/public/js/classes/Player.js
  Games/Multiplayer_Shooting_Game/public/js/classes/Projectile.js
  Games/Multiplayer_Shooting_Game/public/js/eventListeners.js
  Games/Multiplayer_Shooting_Game/public/js/frontend.js
  Games/Multiplayer_Shooting_Game/readme.md
  README.md
  assets/images/Multiplayer_Shooting_Game.jpeg
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5098 Added: Gravity Drops Game
  Games/Gravity_Dropss/README.md
  Games/Gravity_Dropss/index.html
  Games/Gravity_Dropss/script.js
  Games/Gravity_Dropss/style.css
  README.md
  assets/images/Gravity_Drops.png
Labels: Ready to merge 🥳, level3, gssoc

#5102 Added space Dash Game
  Games/Space_Dash/README.md
  Games/Space_Dash/asteroid-dash.js
  Games/Space_Dash/index.html
  Games/Space_Dash/styles.css
  README.md
  assets/images/space_invader.png
Labels: Ready to merge 🥳, level3, gssoc

#5105 Added Belt_Black game
  Games/Belt_Black/README.md
  Games/Belt_Black/assets/images/Belt_Black.png
  Games/Belt_Black/assets/images/background.png
  Games/Belt_Black/assets/images/logo.png
  Games/Belt_Black/assets/ninjas-imgs/1/1.gif
  Games/Belt_Black/assets/ninjas-imgs/1/2.gif
  Games/Belt_Black/assets/ninjas-imgs/1/3.gif
  Games/Belt_Black/assets/ninjas-imgs/1/4.gif
  Games/Belt_Black/assets/ninjas-imgs/1/5.gif
  Games/Belt_Black/assets/ninjas-imgs/1/6.gif
  Games/Belt_Black/assets/ninjas-imgs/1/tmp.gif
  Games/Belt_Black/assets/ninjas-imgs/2/1.gif
  Games/Belt_Black/assets/ninjas-imgs/2/2.gif
  Games/Belt_Black/assets/ninjas-imgs/2/3.gif
  Games/Belt_Black/assets/ninjas-imgs/2/4.gif
  Games/Belt_Black/assets/ninjas-imgs/2/tmp1.gif
  Games/Belt_Black/assets/sound/fight.mp3
  Games/Belt_Black/game.html
  Games/Belt_Black/index.html
  Games/Belt_Black/script.js
  Games/Belt_Black/style.css
  README.md
  assets/images/Belt_Black.png
Labels: Ready to merge 🥳, level3, gssoc

#5107 Added cross road game
  Games/Cross_Road_Game/README.md
  Games/Cross_Road_Game/index.html
  Games/Cross_Road_Game/script.js
  Games/Cross_Road_Game/style.css
  README.md
  assets/images/Cross_Road_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#5109 Contributing under GSSOC'24. Adding a simple game
  Games/Prime-No-Finder-Game/bg.jpg
  Games/Prime-No-Finder-Game/default.png
  Games/Prime-No-Finder-Game/index.html
  Games/Prime-No-Finder-Game/script.js
  Games/Prime-No-Finder-Game/skull.jpg
  Games/Prime-No-Finder-Game/star.jpg
  README.md
  assets/images/Prime-No-Finder Game.png
Labels: Ready to merge 🥳, level3, gssoc

#5106 Added find the missing letter game
  Games/Find_The_Missing_Letter/README.md
  Games/Find_The_Missing_Letter/index.html
  Games/Find_The_Missing_Letter/script.js
  Games/Find_The_Missing_Letter/style.css
  README.md
  assets/images/Find_The_Missing_Letter.png
Labels: Ready to merge 🥳, level3, gssoc

#5092 [new game]:Am I the number?
  Games/Am_I_the_number/README.md
  Games/Am_I_the_number/index.html
  Games/Am_I_the_number/script.js
  Games/Am_I_the_number/style.css
  README.md
  assets/images/amithenumber.png
Labels: Ready to merge 🥳, level3, gssoc

#5112 Added Tower Building Game
  Games/Tower_Building_Game/README.md
  Games/Tower_Building_Game/images/img.png
  Games/Tower_Building_Game/index.html
  Games/Tower_Building_Game/script.js
  Games/Tower_Building_Game/style.css
  README.md
  assets/images/img.png
Labels: Ready to merge 🥳, level3, gssoc

#5121 Changes to gamesdata.json for thumbnail rendering
  assets/js/gamesData.json
Labels: Ready to merge 🥳, gssoc

#5125 Contributing under GSSOC'24. Added new game
  Games/Synonym-Typing-Game/README.md
  Games/Synonym-Typing-Game/bg.jpg
  Games/Synonym-Typing-Game/bg1.jpg
  Games/Synonym-Typing-Game/image.png
  Games/Synonym-Typing-Game/img1.jpg
  Games/Synonym-Typing-Game/index.html
  Games/Synonym-Typing-Game/script.js
  Games/Synonym-Typing-Game/styles.css
  README.md
  assets/images/Synonym-Typing-Game.png
Labels: Ready to merge 🥳, level3, gssoc

#5127 Updated game link in README.md for Sky Lift Dash Game 🎮
  Games/Sky_Lift_Dash/README.md
  Games/Sky_Lift_Dash/images/gameover.png
  Games/Sky_Lift_Dash/images/maingame.png
  Games/Sky_Lift_Dash/index.html
  Games/Sky_Lift_Dash/script.js
  Games/Sky_Lift_Dash/style.css
  README.md
  assets/images/Sky_Lift_Dash.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#4220 Added bounce ball game
  Games/Bounce_Ball/Clarity.js
  Games/Bounce_Ball/README.md
  Games/Bounce_Ball/assets/images/image.png
  Games/Bounce_Ball/index.html
  Games/Bounce_Ball/style.css
  README.md
  assets/images/Screenshot 2024-06-04 224119.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4225 Added new game - Mechanica
  Games/Mechanica/Mechanica.png
  Games/Mechanica/README.md
  Games/Mechanica/angler1.png
  Games/Mechanica/angler2.png
  Games/Mechanica/drone.png
  Games/Mechanica/fireExplosion.png
  Games/Mechanica/gears.png
  Games/Mechanica/hivewhale.png
  Games/Mechanica/index.html
  Games/Mechanica/layer1.png
  Games/Mechanica/layer2.png
  Games/Mechanica/layer3.png
  Games/Mechanica/layer4.png
  Games/Mechanica/lucky.png
  Games/Mechanica/player.png
  Games/Mechanica/projectile.png
  Games/Mechanica/scripts.js
  Games/Mechanica/smokeExplosion.png
  Games/Mechanica/styles.css
  README.md
  assets/images/Mechanica.png
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#5093 added infinite cars
  Games/Infinite_Cars/README.md
  Games/Infinite_Cars/assets/audios/accelerate.wav
  Games/Infinite_Cars/assets/audios/crashed.wav
  Games/Infinite_Cars/assets/audios/drive.wav
  Games/Infinite_Cars/assets/audios/overtake.wav
  Games/Infinite_Cars/assets/audios/select.wav
  Games/Infinite_Cars/assets/audios/start.wav
  Games/Infinite_Cars/assets/fonts/LuckiestGuy-Regular.ttf
  Games/Infinite_Cars/assets/icons/infinite-cars-icon-android-144x144.png
  Games/Infinite_Cars/assets/icons/infinite-cars-icon-android-192x192.png
  Games/Infinite_Cars/assets/icons/infinite-cars-icon-android-36x36.png
  Games/Infinite_Cars/assets/icons/infinite-cars-icon-android-48x48.png
  Games/Infinite_Cars/assets/icons/infinite-cars-icon-android-72x72.png
  Games/Infinite_Cars/assets/icons/infinite-cars-icon-android-96x96.png
  Games/Infinite_Cars/assets/images/infinite-cars-character.png
  Games/Infinite_Cars/assets/images/infinite-cars-computer.png
  Games/Infinite_Cars/assets/images/infinite-cars-explosion.png
  Games/Infinite_Cars/assets/images/infinite-cars-flower.png
  Games/Infinite_Cars/assets/images/infinite-cars-grass.png
  Games/Infinite_Cars/assets/images/infinite-cars-left-gutter.png
  Games/Infinite_Cars/assets/images/infinite-cars-left-road.png
  Games/Infinite_Cars/assets/images/infinite-cars-middle-road.png
  Games/Infinite_Cars/assets/images/infinite-cars-right-gutter.png
  Games/Infinite_Cars/assets/images/infinite-cars-right-road.png
  Games/Infinite_Cars/assets/images/infinite-cars-road-cone.png
  Games/Infinite_Cars/assets/images/infinite-cars-sound.png
  Games/Infinite_Cars/assets/images/infinite-cars-stop-light.png
  Games/Infinite_Cars/assets/images/infinite-cars-tree.png
  Games/Infinite_Cars/background.js
  Games/Infinite_Cars/index.html
  Games/Infinite_Cars/scripts/includes/Constants.js
  Games/Infinite_Cars/scripts/includes/Methods.js
  Games/Infinite_Cars/scripts/infinite-cars.js
  Games/Infinite_Cars/scripts/infinite-cars.processed.js
  Games/Infinite_Cars/scripts/libs/phaser.min.js
  Games/Infinite_Cars/scripts/scenes/GameScene.js
  Games/Infinite_Cars/scripts/scenes/LoadingScene.js
  Games/Infinite_Cars/scripts/scenes/MainScene.js
  Games/Infinite_Cars/styles/infinite-cars.css
  Games/Infinite_Cars/styles/infinite-cars.processed.css
  README.md
  assets/images/infinite_cars.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5020 Cow Bull Game
  Games/CowBull/README.md
  Games/CowBull/css/game.css
  Games/CowBull/css/index.css
  Games/CowBull/game.html
  Games/CowBull/image.png
  Games/CowBull/index.html
  Games/CowBull/js/app.js
  Games/CowBull/js/game.js
  Games/CowBull/js/index.js
  Games/CowBull/js/particles.min.js
  README.md
  assets/images/cowhome.png
  assets/images/cowlogo.png
Labels: Ready to merge 🥳, level3, gssoc

#5123 Added number sorting game
  Games/Number_Sorting_Game/README.md
  Games/Number_Sorting_Game/index.html
  Games/Number_Sorting_Game/scripts.js
  Games/Number_Sorting_Game/styles.css
  README.md
  assets/images/Number_Sorting_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#5132 Adds Block Vault game 🕹️
  Games/Block_Vault/README.md
  Games/Block_Vault/assets/preview.png
  Games/Block_Vault/index.html
  Games/Block_Vault/script.js
  Games/Block_Vault/style.css
  README.md
  assets/images/Block_Vault.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5126 Drop Dash Game is added
  Games/Drop_Dash_Game/README.md
  Games/Drop_Dash_Game/index.html
  Games/Drop_Dash_Game/script.js
  Games/Drop_Dash_Game/style.css
  README.md
  assets/images/Drop_Dash_Game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5137 New game Path_Finder_Challenge
  Games/Alien_Language_Translator/script.js
  Games/Path_Finder_Challenge/README.md
  Games/Path_Finder_Challenge/image/imageofgame.png
  Games/Path_Finder_Challenge/index.html
  Games/Path_Finder_Challenge/script.js
  Games/Path_Finder_Challenge/styles.css
  README.md
  assets/images/Alien_Language.png
  assets/images/Path_Finder_Challenge.png
Labels: Ready to merge 🥳, level3, gssoc

#5139 number catcher game added
  Games/Number_Catcher_Game/README.md
  Games/Number_Catcher_Game/index.html
  Games/Number_Catcher_Game/scripts.js
  Games/Number_Catcher_Game/styles.css
  README.md
  assets/images/Number_Catcher_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#5142 Added a new game called Elemental Flux
  Games/Elemental_Flux/Gameplay/Game_1.png
  Games/Elemental_Flux/Gameplay/Game_2.png
  Games/Elemental_Flux/Gameplay/Game_3.png
  Games/Elemental_Flux/Gameplay/desktop.ini
  Games/Elemental_Flux/images/coal.jpeg
  Games/Elemental_Flux/images/gas.jpeg
  Games/Elemental_Flux/images/geo.jpeg
  Games/Elemental_Flux/images/hydro.jpeg
  Games/Elemental_Flux/images/nuclear.jpeg
  Games/Elemental_Flux/images/oil.jpeg
  Games/Elemental_Flux/images/solor.jpeg
  Games/Elemental_Flux/images/wind.jpeg
  Games/Elemental_Flux/index.html
  Games/Elemental_Flux/readme.md
  Games/Elemental_Flux/script.js
  Games/Elemental_Flux/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#5144 New Game:[The Mystery Adventure Game]
  Games/The_Mystery_Adventure_Game/Dream Library.jpeg
  Games/The_Mystery_Adventure_Game/README.md
  Games/The_Mystery_Adventure_Game/index.html
  Games/The_Mystery_Adventure_Game/script.js
  Games/The_Mystery_Adventure_Game/style.css
  README.md
  assets/images/The Mystery Adventure Game.png
Labels: Ready to merge 🥳, level3, gssoc

#5146 Box In Air Game is added
  Games/Box_In_Air_Game/README.md
  Games/Box_In_Air_Game/index.html
  Games/Box_In_Air_Game/script.js
  Games/Box_In_Air_Game/style.css
  README.md
  assets/images/Box_In_Air_Game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5150 Added ball and Paddle game with dynamic scoring!
  Games/Ball-And-Paddle-Game/README.md
  Games/Ball-And-Paddle-Game/index.html
  Games/Ball-And-Paddle-Game/script.js
  Games/Ball-And-Paddle-Game/style.css
  README.md
  assets/images/Ball-And-Paddle-game.md
Labels: Ready to merge 🥳, level3, gssoc

#5147 Adds Random Choice Picker game 🕹️
  Games/Random_Choice_Picker/README.md
  Games/Random_Choice_Picker/assets/preview.png
  Games/Random_Choice_Picker/assets/random__choice_picker.webm
  Games/Random_Choice_Picker/index.html
  Games/Random_Choice_Picker/script.js
  Games/Random_Choice_Picker/style.css
  README.md
  assets/images/Random_Choice_Picker.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5162 Gravity Switch Game is added
  Games/Gravity_Switch_Game/README.md
  Games/Gravity_Switch_Game/index.html
  Games/Gravity_Switch_Game/script.js
  Games/Gravity_Switch_Game/style.css
  README.md
  assets/images/Gravity_Switch_Game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5163 Adds Drummer Kit game 🥁
  Games/Drummer_Kit/README.md
  Games/Drummer_Kit/app.js
  Games/Drummer_Kit/assets/bg-1.jpg
  Games/Drummer_Kit/assets/dj.jpg
  Games/Drummer_Kit/index.html
  Games/Drummer_Kit/sounds/boom.wav
  Games/Drummer_Kit/sounds/clap.wav
  Games/Drummer_Kit/sounds/hihat.wav
  Games/Drummer_Kit/sounds/kick.wav
  Games/Drummer_Kit/sounds/openhat.wav
  Games/Drummer_Kit/sounds/ride.wav
  Games/Drummer_Kit/sounds/snare.wav
  Games/Drummer_Kit/sounds/tink.wav
  Games/Drummer_Kit/sounds/tom.wav
  Games/Drummer_Kit/style.css
  README.md
  assets/images/Drummer_Kit.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5157 Balloon Defense Game added
  Games/Balloon_Defense_Game/README.md
  Games/Balloon_Defense_Game/index.htm
  Games/Balloon_Defense_Game/scripts.js
  Games/Balloon_Defense_Game/styles.css
  README.md
  assets/images/Balloon_Defense_Game.png
Labels: Ready to merge 🥳, level3, gssoc
