Repository kunjgit/GameZone, pull requests merged in 2024-05, with the labels that each got.

#3109 updated the script.js file
  Games/Alphabet_Learning_Game/script.js
Labels: level3, gssoc

#3111 Added event listeners for specific keyboard buttons and implemented the functionality to play music
  Games/Piano/Piano.md
  Games/Piano/index.html
  Games/Piano/script.js
  Games/Piano/style.css
Labels: level3, gssoc

#3119 Fixed gap in hero section and pagination
  assets/css/style.css
Labels: level3, gssoc

#3141 Fixed snake game
  Games/Snake_Game/index.html
  Games/Snake_Game/index.js
  Games/Snake_Game/script.js
  Games/Snake_Game/style.css
Labels: level3, gssoc

#3159 Game Button Functionality and Styling Issue Resolved
  Games/Whack_a_Mole/CSS/style.css
  Games/Whack_a_Mole/JS/script.js
Labels: level3, gssoc

#3166 Responsive of Guess_the _Number
  Games/Guess_The_Number/style.css
Labels: level3, gssoc

#3169 Pop My Balloon Game Added
  Games/Pop_My_Balloon/BallonText.html
  Games/Pop_My_Balloon/BalloonAnimation.css
  Games/Pop_My_Balloon/index.html
  Games/Pop_My_Balloon/readme.md
  Games/Pop_My_Balloon/script.js
  Games/Pop_My_Balloon/styles.css
  README.md
  assets/images/Pop_My_Balloon.png
  assets/index_old.html
Labels: level1, gssoc

#3175 Vinayak repeat
  Games/Guess_The_Number/main.js
  Games/Guess_The_Number/style.css
Labels: level3, gssoc

#3245 Enhanced Home Page for Snake Game
  Games/Snake_Game/index.html
  Games/Snake_Game/style.css
Labels: level2, gssoc

#3295 [New Game]: Maze_Game
  Games/Maze_Game/README.md
  Games/Maze_Game/cheese.png
  Games/Maze_Game/index.html
  Games/Maze_Game/jerry.png
  Games/Maze_Game/script.js
  Games/Maze_Game/style.css
  README.md
  assets/images/Maze_Game.png
  assets/index_old.html
Labels: level3, gssoc

#3302 Enabled the game 'run and jump' to pause and resume
  Games/Run and Jump/index.html
  Games/Run and Jump/script.js
  Games/Run and Jump/style.css
Labels: level2, gssoc

#3274 Knife thrower
  Games/Knife-Thrower/README.md
  Games/Knife-Thrower/knife.css
  Games/Knife-Thrower/knife.html
  Games/Knife-Thrower/knife.js
  Games/Knife-Thrower/knife.png
  README.md
  assets/images/Knife-Thrower.png
Labels: level3, gssoc

#3319 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, gssoc

#3335 Added Words, and removed repetation
  Games/Tennis/script.js
  Games/Tennis/style.css
  Games/Word_Guessing_Game/script.js
  Games/Word_Guessing_Game/word.js
Labels: level2, gssoc

#3305 Tower Stack Game added.
  Games/Tower_Stack/GameDemo.png
  Games/Tower_Stack/README.md
  Games/Tower_Stack/TweenMax.min.js
  Games/Tower_Stack/index.html
  Games/Tower_Stack/script.js
  Games/Tower_Stack/style.css
  Games/Tower_Stack/three.min.js
  README.md
  assets/images/Tower_Stack.png
  assets/index_old.html
Labels: Pending ⏱️

#3363 Added a feature to store and display highscore
  Games/Run and Jump/index.html
  Games/Run and Jump/script.js
  Games/Run and Jump/style.css
Labels: level2, gssoc

#3376 Ball_Shooting_Game is added
  Games/Ball_Shooting_Game/README.md
  Games/Ball_Shooting_Game/index.html
  Games/Ball_Shooting_Game/script.js
  Games/Ball_Shooting_Game/styles.css
  README.md
  assets/images/Ball_Shooting_Game.png
Labels: under review

#3196 bulls and cows game added
  Games/Bulls_and_Cows/README.md
  Games/Bulls_and_Cows/assets/bulls-and-cows.png
  Games/Bulls_and_Cows/index.html
  Games/Bulls_and_Cows/script.js
  Games/Bulls_and_Cows/styles.css
  README.md
  assets/images/bulls-and-cows.png
  assets/index_old.html
  assets/js/gamesData.json
Labels: Pending ⏱️

#3250 new game : dinosaur memory game added
  Games/Dinosaur_Memory_Game/README.md
  Games/Dinosaur_Memory_Game/assets/images/Dinosaur_memory_game.png
  Games/Dinosaur_Memory_Game/index.html
  Games/Dinosaur_Memory_Game/script.js
  Games/Dinosaur_Memory_Game/style.css
  README.md
  assets/images/Dinosaur_memory_game.png
Labels: level3, gssoc

#3344 Whack_a_Mole_Mario_Version Game
  Games/Whack_a_Mole_Mario_Version/README.md
  Games/Whack_a_Mole_Mario_Version/WhackaMole_MarioVersion.png
  Games/Whack_a_Mole_Mario_Version/index.html
  Games/Whack_a_Mole_Mario_Version/mario-bg.jpg
  Games/Whack_a_Mole_Mario_Version/monty-mole.png
  Games/Whack_a_Mole_Mario_Version/pipe.png
  Games/Whack_a_Mole_Mario_Version/piranha-plant.png
  Games/Whack_a_Mole_Mario_Version/restart.png
  Games/Whack_a_Mole_Mario_Version/soil.png
  Games/Whack_a_Mole_Mario_Version/whackamole.css
  Games/Whack_a_Mole_Mario_Version/whackamole.js
  README.md
  assets/images/Whack_a_Mole_Mario_Version.png
Labels: level3, under review, gssoc

#3373 Diplay player turns and win,lose or tie on the screen
  Games/Tic_Tac_Toe/README.md
  Games/Tic_Tac_Toe/style.css
  assets/images/Tic_Tac_Toe.png
  assets/images/Tic_Tac_Toe.webp
Labels: level2, gssoc

#3389 Add a 10 secs alert to Master Typing Game
  Games/Master_Typing/index.html
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
Labels: level2, gssoc

#3402 Fixes #3406 Add Run_Dora_Run New Game
  Games/Run_Dora_Run/README.md
  Games/Run_Dora_Run/background.png
  Games/Run_Dora_Run/cake.png
  Games/Run_Dora_Run/doraemon.png
  Games/Run_Dora_Run/game.js
  Games/Run_Dora_Run/index.html
  Games/Run_Dora_Run/obstacle.png
  Games/Run_Dora_Run/styles.css
  Games/Run_Dora_Run/trap.png
  README.md
  assets/images/Run_Dora_Run.png
Labels: level3, under review, gssoc

#3417 Changes in number guessing game that appear more interractive and looks like good
  Games/Guess_The_Number/index.html
  Games/Guess_The_Number/main.js
  Games/Guess_The_Number/style.css
  Games/HangMan/index.html
  Games/HangMan/scripts/script.js
  Games/HangMan/sounds/green.mp3
  Games/HangMan/sounds/red.mp3
  Games/HangMan/sounds/wrong.mp3
  Games/Simon_Game_Challenge/index.html
  Games/Simon_Game_Challenge/styles.css
Labels: level2, gssoc

#3425 Added new game TriHand_Tactics
  Games/TriHand_Tactics/README.md
  Games/TriHand_Tactics/images/paper-emoji.png
  Games/TriHand_Tactics/images/rock-emoji.png
  Games/TriHand_Tactics/images/scissors-emoji.png
  Games/TriHand_Tactics/images/webview.png
  Games/TriHand_Tactics/index.html
  Games/TriHand_Tactics/script.js
  Games/TriHand_Tactics/styles.css
  README.md
  assets/images/TriHand_Tactics.png
Labels: under review

#3429 Adding Shape Finder Game
  Games/Shape Finder/README.md
  Games/Shape Finder/favicon.ico
  Games/Shape Finder/index.html
  Games/Shape Finder/script.js
  Games/Shape Finder/style.css
  README.md
  assets/images/Shape Finder.png
Labels: under review

#3444 Added game CatchTheBall
  Games/CatchTheBall/README.md
  Games/CatchTheBall/index.html
  Games/CatchTheBall/script.js
  Games/CatchTheBall/style.css
  README.md
  assets/images/CatchTheBall.png
Labels: under review

#3446 New Game Added [Memory Card Flip]
  Games/Memory_Cards_Game/Memory_Cards_Game.png
  Games/Memory_Cards_Game/README.md
  Games/Memory_Cards_Game/images/img-1.png
  Games/Memory_Cards_Game/images/img-2.png
  Games/Memory_Cards_Game/images/img-3.png
  Games/Memory_Cards_Game/images/img-4.png
  Games/Memory_Cards_Game/images/img-5.png
  Games/Memory_Cards_Game/images/img-6.png
  Games/Memory_Cards_Game/images/que_icon.svg
  Games/Memory_Cards_Game/index.html
  Games/Memory_Cards_Game/script.js
  Games/Memory_Cards_Game/style.css
  README.md
  assets/images/Memory_Cards_Game.png
  assets/js/gamesData.json
Labels: under review

#3470 Added [New game] Rock_paper_scissor
  Games/Rock_paper_scissor/README.md
  Games/Rock_paper_scissor/images/paper.png
  Games/Rock_paper_scissor/images/rock.png
  Games/Rock_paper_scissor/images/scissors.png
  Games/Rock_paper_scissor/index.html
  Games/Rock_paper_scissor/script.js
  Games/Rock_paper_scissor/styles.css
  README.md
  assets/images/Rock_paper_scissor.png
  assets/images/paper.png
  assets/images/rock.png
  assets/images/scissors.png
Labels: under review

#3477 New Game-Color_Blast
  Games/Color_Blast/Color_Blast.png
  Games/Color_Blast/README.md
  Games/Color_Blast/index.html
  Games/Color_Blast/script.js
  Games/Color_Blast/style.css
  README.md
  assets/images/Color_Blast.png
Labels: under review

#3381 added a new game escape room (puzzle version)
  Games/escaperoom/README.md
  Games/escaperoom/index.html
  Games/escaperoom/script.js
  Games/escaperoom/styles.css
  README.md
  assets/images/escaperoom.png
  assets/js/gamesData.json
  assets/js/index.js
Labels: under review

#3396 Added "Rating and Feedback" in the Master Typing Game
  Games/Master_Typing/assets/Feedback Form.png
  Games/Master_Typing/assets/Rating Prompt.png
  Games/Master_Typing/index.html
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
Labels: level2, gssoc

#3408 Added instructions and game title in Master Typing Game
  Games/Master_Typing/index.html
  Games/Master_Typing/rules.html
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
  Games/Simon_Game_Challenge/styles.css
Labels: Pending ⏱️

#3412 new game added
  Games/DoraemonRun/README.md
  Games/DoraemonRun/image/PngItem_148881.png
  Games/DoraemonRun/image/back.webp
  Games/DoraemonRun/image/chuaaa.mp3
  Games/DoraemonRun/image/dora.png
  Games/DoraemonRun/image/doracake.png
  Games/DoraemonRun/image/doracake4.png
  Games/DoraemonRun/image/food.mp3
  Games/DoraemonRun/image/gameover.mp3
  Games/DoraemonRun/image/grass_template2.jpg
  Games/DoraemonRun/image/move.mp3
  Games/DoraemonRun/image/musicdoralarge.mp3
  Games/DoraemonRun/image/smalldoral3.png
  Games/DoraemonRun/image/tasty.m4a
  Games/DoraemonRun/index.html
  Games/DoraemonRun/script.js
  Games/DoraemonRun/styles.css
  README.md
  assets/images/dora.png
  assets/index_old.html
Labels: Pending ⏱️, under review

#3473 Added Score Counter and Practice Key Advisor
  Games/Master_Typing/index.html
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
Labels: Pending ⏱️

#3495 ADDED BLOCK GAME
  Games/Block Game/Block Game.jpg
  Games/Block Game/README.md
  Games/Block Game/index.html
  Games/Block Game/script.js
  Games/Block Game/style.css
  README.md
  assets/images/Block Game.jpg
Labels: under review

#3507 Bottle Flip Game
  Games/Bottle_Flip/README.md
  Games/Bottle_Flip/index.html
  Games/Bottle_Flip/script.js
  Games/Bottle_Flip/styles.css
  README.md
  assets/images/BottleFlip_Background.jpg
  assets/images/BottleFlip_Bottle.png
  assets/images/BottleFlip_Bottle1.png
  assets/images/BottleFlip_ss.png
Labels: level3, under review, gssoc

#3541 dice roller game added
  Games/Dice_Roller/README.md
  Games/Dice_Roller/index.html
  Games/Dice_Roller/script.js
  Games/Dice_Roller/style.css
  Games/Dino_Runner_Game/script.js
  Games/index.html
  README.md
  assets/images/Dice_Roller.png
  assets/js/gamesData.json
Labels: under review

#3450 [New game ] : technical mind game added
  Games/Technical_Mind_Game/README.md
  Games/Technical_Mind_Game/beep-07a.wav
  Games/Technical_Mind_Game/demo.mp4
  Games/Technical_Mind_Game/index.html
  Games/Technical_Mind_Game/script.js
  Games/Technical_Mind_Game/style.css
  README.md
  assets/images/Technical_Mind_Game.png
  assets/js/gamesData.json
Labels: Pending ⏱️, under review

#3433 Mancala_Game
  Games/Mancala_Game/README.md
  Games/Mancala_Game/assets/Images/Mancala_Game.jpeg
  Games/Mancala_Game/assets/Videos/Mancala.mp4
  Games/Mancala_Game/index.html
  Games/Mancala_Game/script.js
  Games/Mancala_Game/style.css
  README.md
  assets/images/Mancala_Game.jpeg
Labels: Pending ⏱️

#3499 City_Builder_Game is added
  Games/City_Builder_Game/README.md
  Games/City_Builder_Game/index.html
  Games/City_Builder_Game/script.js
  Games/City_Builder_Game/styles.css
  README.md
  assets/images/City_Builder_Game.png
Labels: Pending ⏱️, under review

#3502 requested changes made (Dot_Connect #3131)
  Games/Dot_Connect/README.md
  Games/Dot_Connect/assets/images/Dot_Connect1.png
  Games/Dot_Connect/assets/images/Dot_Connect2.png
  Games/Dot_Connect/assets/images/Dot_Connect3.png
  Games/Dot_Connect/index.html
  Games/Dot_Connect/script.js
  Games/Dot_Connect/style.css
  README.md
  assets/images/Dot_Connect.png
  assets/js/gamesData.json
Labels: Pending ⏱️

#3434 Added a new game Slide_Master_Puzzle
  Games/Slide_Master_Puzzle/Readme.md
  Games/Slide_Master_Puzzle/Slide_Master_Puzzle.png
  Games/Slide_Master_Puzzle/index.html
  Games/Slide_Master_Puzzle/script.js
  Games/Slide_Master_Puzzle/style.css
  README.md
  assets/images/Slide_Master_Puzzle.png
Labels: changes requested, pending

#3540 Master Typing and Snake game enhancement
  Games/Master_Typing/README.md
  Games/Master_Typing/assets/images/game_initial_state.png
  Games/Master_Typing/assets/images/reset_button_functionality.png
  Games/Master_Typing/assets/images/start_button_functionality.png
  Games/Master_Typing/index.html
  Games/Master_Typing/script.js
  Games/Master_Typing/style.css
  Games/Snake_Game/index.html
  Games/Snake_Game/style.css
Labels: level3, gssoc

#3546 added google chrome dino game
  Games/Chrome_Dino_Game/README.md
  Games/Chrome_Dino_Game/cactus.js
  Games/Chrome_Dino_Game/dino.js
  Games/Chrome_Dino_Game/ground.js
  Games/Chrome_Dino_Game/imgs/cactus.png
  Games/Chrome_Dino_Game/imgs/dino-lose.png
  Games/Chrome_Dino_Game/imgs/dino-run-0.png
  Games/Chrome_Dino_Game/imgs/dino-run-1.png
  Games/Chrome_Dino_Game/imgs/dino-stationary.png
  Games/Chrome_Dino_Game/imgs/ground.png
  Games/Chrome_Dino_Game/index.html
  Games/Chrome_Dino_Game/script.js
  Games/Chrome_Dino_Game/styles.css
  Games/Chrome_Dino_Game/updateCustomProperty.js
  README.md
  assets/images/Chrome_Dino_Game.png
  assets/js/gamesData.json
Labels: level3, gssoc

#3580 Solved issue # 3578- Word Association game
  Games/word_association/README.md
  Games/word_association/index.html
  Games/word_association/script.js
  Games/word_association/style.css
  README.md
  assets/images/Word_Association_img.png
Labels: Pending ⏱️

#3586 Catch_The_Circle is added
  Games/Catch_The_Circle/README.md
  Games/Catch_The_Circle/index.html
  README.md
  assets/images/Catch_The_Circle.png
Labels: Pending ⏱️

#3588 Steampunk Flappy Bird has been added
  Games/Steampunk_FlappyBird/README.md
  Games/Steampunk_FlappyBird/assets/audio/charge.mp3
  Games/Steampunk_FlappyBird/assets/audio/flap1.mp3
  Games/Steampunk_FlappyBird/assets/audio/flap2.mp3
  Games/Steampunk_FlappyBird/assets/audio/flap3.mp3
  Games/Steampunk_FlappyBird/assets/audio/flap4.mp3
  Games/Steampunk_FlappyBird/assets/audio/flap5.mp3
  Games/Steampunk_FlappyBird/assets/audio/lose.mp3
  Games/Steampunk_FlappyBird/assets/audio/win.mp3
  Games/Steampunk_FlappyBird/assets/images/background_single.png
  Games/Steampunk_FlappyBird/assets/images/player_fish.png
  Games/Steampunk_FlappyBird/assets/images/smallGears.png
  Games/Steampunk_FlappyBird/assets/scripts/audio.js
  Games/Steampunk_FlappyBird/assets/scripts/background.js
  Games/Steampunk_FlappyBird/assets/scripts/fullscreen.js
  Games/Steampunk_FlappyBird/assets/scripts/main.js
  Games/Steampunk_FlappyBird/assets/scripts/obstacles.js
  Games/Steampunk_FlappyBird/assets/scripts/player.js
  Games/Steampunk_FlappyBird/index.html
  Games/Steampunk_FlappyBird/style.css
  README.md
  assets/images/Steampunk_FlappyBird.png
Labels: Pending ⏱️

#3559 Animations Added
  assets/css/style.css
  index.html
Labels: Pending ⏱️

#3566 Adding Bomb Throw Game
  Games/Bomb Throw Game/Bomb Throw Game.png
  Games/Bomb Throw Game/README.md
  Games/Bomb Throw Game/index.html
  Games/Bomb Throw Game/script.js
  Games/Bomb Throw Game/style.css
  README.md
  assets/images/Bomb Throw Game.png
Labels: Pending ⏱️

#3596 new game added path finder puzzle
  Games/path_finder/README.md
  Games/path_finder/index.html
  Games/path_finder/script.js
  Games/path_finder/styles.css
  README.md
  assets/images/pf3.png
  assets/js/gamesData.json
  assets/js/index.js
Labels: level3, gssoc

#3603 Random Advice Generator
  Games/Random_Advice_Generator/README.md
  Games/Random_Advice_Generator/images/icon-dice.svg
  Games/Random_Advice_Generator/images/pattern-divider-desktop.svg
  Games/Random_Advice_Generator/images/pattern-divider-mobile.svg
  Games/Random_Advice_Generator/index.html
  Games/Random_Advice_Generator/index.js
  Games/Random_Advice_Generator/style.css
  README.md
  assets/images/Random_Advice_Generator.png
Labels: Pending ⏱️

#3610 Balloon buster
  Games/Balloon_Buster/README.md
  Games/Balloon_Buster/index.html
  Games/Balloon_Buster/script.js
  Games/Balloon_Buster/style.css
  README.md
  assets/images/Balloon_Buster.jpeg
Labels: level3, gssoc

#3631 [New Game]: Adding Catching the Falling stars game
  Games/catch_the_falling_stars/README.md
  Games/catch_the_falling_stars/index.html
  Games/catch_the_falling_stars/script.js
  Games/catch_the_falling_stars/styles.css
  README.md
  assets/images/Screenshot 2024-05-22 123450.png
Labels: Pending ⏱️

#3633 New Game Coloron
  Games/Coloron/Coloron.png
  Games/Coloron/README.md
  Games/Coloron/index.html
  Games/Coloron/script.js
  Games/Coloron/style.css
  README.md
  assets/images/Coloron.png
Labels: Pending ⏱️

#3343 Astronaut_runner
  Games/Astronaunt_runner/README.md
  Games/Astronaunt_runner/Screenshot 2024-05-16 184235.png
  Games/Astronaunt_runner/[removal.ai]_7c44869d-9a02-4ea6-a955-04cbe0cbaad7-meteroid.png
  Games/Astronaunt_runner/astronanut2-unscreen.gif
  Games/Astronaunt_runner/backgroundimagespace.jpg
  Games/Astronaunt_runner/index.html
  Games/Astronaunt_runner/script.js
  Games/Astronaunt_runner/style.css
  README.md
  assets/images/Screenshot 2024-05-16 184235.png
Labels: Pending ⏱️, Changes Requested ⚒️

#3636 brick and ball added
  Games/Brick_and_Ball/README.md
  Games/Brick_and_Ball/index.html
  Games/Brick_and_Ball/script.js
  Games/Brick_and_Ball/style.css
  README.md
  assets/images/Brick_and_Ball.png
  assets/js/gamesData.json
Labels: level3

#3655 Added Automated rock Paper Scissor
  Games/automated_rock_paper_scissor/README.md
  Games/automated_rock_paper_scissor/index.html
  README.md
  assets/images/image.png
Labels: level3, gssoc

#3686 Solved issue #3685- Space Explorer game
  Games/space_explorer/README.md
  Games/space_explorer/index.html
  Games/space_explorer/script.js
  Games/space_explorer/styles.css
  README.md
  assets/images/Space_Explorer.png
Labels: level3, gssoc

#3693 Added game QuickFingers
  Games/QuickFingers/README.md
  Games/QuickFingers/index.html
  Games/QuickFingers/script.js
  Games/QuickFingers/styles.css
  README.md
  assets/images/QuickFingers.png
Labels: level3, gssoc

#3677 Shrek Vs Wild game added
  Games/Shrek_Vs_Wild/README.md
  Games/Shrek_Vs_Wild/docs/assets/images/Boss_Sprite.png
  Games/Shrek_Vs_Wild/docs/assets/images/Game Boy Advance - Shrek Reekin Havoc - Shrek.png
  Games/Shrek_Vs_Wild/docs/assets/images/GameBackground.png
  Games/Shrek_Vs_Wild/docs/assets/images/Homebackground.png
  Games/Shrek_Vs_Wild/docs/assets/images/NUN_SPRITES.png
  Games/Shrek_Vs_Wild/docs/assets/images/SimonSpriteSheet.png
  Games/Shrek_Vs_Wild/docs/assets/images/ZOMBIE_SPRITE.png
  Games/Shrek_Vs_Wild/docs/assets/images/Zombie.png
  Games/Shrek_Vs_Wild/docs/assets/images/bossImage.png
  Games/Shrek_Vs_Wild/docs/assets/images/boss_bullets.png
  Games/Shrek_Vs_Wild/docs/assets/images/boss_bullets_vertical.png
  Games/Shrek_Vs_Wild/docs/assets/images/bullet.png
  Games/Shrek_Vs_Wild/docs/assets/images/canvas-img.png
  Games/Shrek_Vs_Wild/docs/assets/images/chieficon.png
  Games/Shrek_Vs_Wild/docs/assets/images/d2jt4f5-62c435b7-5e49-4306-86f5-409b08d681da.png
  Games/Shrek_Vs_Wild/docs/assets/images/health_bar.png
  Games/Shrek_Vs_Wild/docs/assets/images/main_char_sprite.png
  Games/Shrek_Vs_Wild/docs/assets/images/nun_orig-black-NESW.png
  Games/Shrek_Vs_Wild/docs/assets/images/nun_sprite.png
  Games/Shrek_Vs_Wild/docs/assets/images/pickle_rick_bullet.png
  Games/Shrek_Vs_Wild/docs/assets/images/unicorn.png
  Games/Shrek_Vs_Wild/docs/assets/images/zombies_sprite.png
  Games/Shrek_Vs_Wild/docs/assets/sounds/background-song.mp3
  Games/Shrek_Vs_Wild/docs/assets/sounds/boss-song.mp3
  Games/Shrek_Vs_Wild/highscore.html
  Games/Shrek_Vs_Wild/index.html
  Games/Shrek_Vs_Wild/scripts/bindings.js
  Games/Shrek_Vs_Wild/scripts/components.js
  Games/Shrek_Vs_Wild/scripts/game.js
  Games/Shrek_Vs_Wild/scripts/highscore.js
  Games/Shrek_Vs_Wild/scripts/main.js
  Games/Shrek_Vs_Wild/scripts/shooting.js
  Games/Shrek_Vs_Wild/styles/highscorestyles.css
  Games/Shrek_Vs_Wild/styles/styles.css
  README.md
  assets/images/Shrek_Vs_Wild.png
  assets/index_old.html
  assets/js/gamesData.json
Labels: level3, gssoc

#3679 Virtual Pet Game added
  Games/Virtual_Pet_Game/.gitignore
  Games/Virtual_Pet_Game/README.md
  Games/Virtual_Pet_Game/assets/rigFull.svg
  Games/Virtual_Pet_Game/docs/baloo.woff2
  Games/Virtual_Pet_Game/docs/button.mp3
  Games/Virtual_Pet_Game/docs/button.wav
  Games/Virtual_Pet_Game/docs/index.html
  Games/Virtual_Pet_Game/docs/script.js
  Games/Virtual_Pet_Game/docs/style.css
  Games/Virtual_Pet_Game/docs/svg.js
  Games/Virtual_Pet_Game/package-lock.json
  Games/Virtual_Pet_Game/package.json
  Games/Virtual_Pet_Game/prototype/animation.js
  Games/Virtual_Pet_Game/prototype/animations.css
  Games/Virtual_Pet_Game/prototype/animations.html
  Games/Virtual_Pet_Game/prototype/prototype.html
  Games/Virtual_Pet_Game/prototype/prototype.js
  Games/Virtual_Pet_Game/prototype/svg.js
  Games/Virtual_Pet_Game/scripts/pack.js
  README.md
  assets/images/Virtual_Pet_Game.png
  assets/index_old.html
  assets/js/gamesData.json
Labels: Pending ⏱️

#3696 Chess.com added
  Games/Chess.com/Bbishop.png
  Games/Chess.com/Bking.png
  Games/Chess.com/Bknight.png
  Games/Chess.com/Bpawn.png
  Games/Chess.com/Bqueen.png
  Games/Chess.com/Brook.png
  Games/Chess.com/README.md
  Games/Chess.com/Wbishop.png
  Games/Chess.com/Wking.png
  Games/Chess.com/Wknight.png
  Games/Chess.com/Wpawn.png
  Games/Chess.com/Wqueen.png
  Games/Chess.com/Wrook.png
  Games/Chess.com/index.html
  Games/Chess.com/script.js
  Games/Chess.com/style.css
  README.md
  assets/images/Chess.com.jpg
  assets/js/gamesData.json
Labels: level3, gssoc

#3704 Added Guess_Num Game
  Games/Guess_num/README.md
  Games/Guess_num/index.html
  Games/Guess_num/script.js
  Games/Guess_num/style.css
  README.md
  assets/images/Guess_num.png
Labels: Pending ⏱️

#3769 [New Game]: color_matching_application
  Games/color_matching_application/README.md
  Games/color_matching_application/images/color_matching_application.png
  Games/color_matching_application/index.html
  Games/color_matching_application/script.js
  Games/color_matching_application/style.css
  README.md
  assets/images/color_matching_application.png
Labels: level3, gssoc

#3774 Created new game, issue #3724
  Games/Fruit_Catching_Game/README.md
  Games/Fruit_Catching_Game/images/apple.png
  Games/Fruit_Catching_Game/images/grapes.png
  Games/Fruit_Catching_Game/images/orange.png
  Games/Fruit_Catching_Game/images/scenery.svg
  Games/Fruit_Catching_Game/images/watermelon.webp
  Games/Fruit_Catching_Game/index.html
  Games/Fruit_Catching_Game/script.js
  Games/Fruit_Catching_Game/style.css
  README.md
  assets/images/fruit_catch_game (2).png
  assets/images/fruit_catch_game.png
Labels: Pending ⏱️, Changes Requested ⚒️

#3784 Added Pictionary Game
  Games/Pictionary_Game/Index.html
  Games/Pictionary_Game/README.md
  Games/Pictionary_Game/scripts/script.js
  Games/Pictionary_Game/src/styles.css
  README.md
  assets/images/Pictionary.png
Labels: Pending ⏱️, Changes Requested ⚒️

#3702 2048_win
  Games/2048_win/2048_win.png
  Games/2048_win/Readme.md
  Games/2048_win/index.html
  Games/2048_win/script.js
  Games/2048_win/style.css
  README.md
  assets/images/2048_win.png
  assets/images/2048_win.webp
Labels: Pending ⏱️

#3729 NEW GAME: HIT YOUR FRIEND
  Games/HitYourFriend/README.md
  Games/HitYourFriend/index.html
  Games/HitYourFriend/script.js
  Games/HitYourFriend/style.css
  README.md
  assets/images/Hit-Your-Friend-winner.png
Labels: Pending ⏱️, Changes Requested ⚒️

#3731 [New game]: Touch-No-Fire-Fame
  Games/Touch-No-Fire-Game/README.md
  Games/Touch-No-Fire-Game/images/fire.png
  Games/Touch-No-Fire-Game/index.html
  Games/Touch-No-Fire-Game/script.js
  Games/Touch-No-Fire-Game/style.css
  README.md
  assets/images/fire.png
  index.html
  loader.gif
Labels: Pending ⏱️, Changes Requested ⚒️

#3787 Added Tiny Fishing game
  Games/Tiny-Fishing/README.md
  Games/Tiny-Fishing/html5game/TinyFishing.js
  Games/Tiny-Fishing/html5game/TinyFishing_texture_0.png
  Games/Tiny-Fishing/html5game/TinyFishing_texture_1.png
  Games/Tiny-Fishing/html5game/TinyFishing_texture_2.png
  Games/Tiny-Fishing/html5game/TinyFishing_texture_3.png
  Games/Tiny-Fishing/html5game/TinyFishing_texture_4.png
  Games/Tiny-Fishing/html5game/aqh_GameAnalytics.js
  Games/Tiny-Fishing/html5game/bqh_GameAnalyticsExt.js
  Games/Tiny-Fishing/html5game/cqh_djs.js
  Games/Tiny-Fishing/html5game/eqh_gamesnacks.js
  Games/Tiny-Fishing/html5game/load.png
  Games/Tiny-Fishing/html5game/snd_boost.ogg
  Games/Tiny-Fishing/html5game/snd_butClick.ogg
  Games/Tiny-Fishing/html5game/snd_buyForCoins.ogg
  Games/Tiny-Fishing/html5game/snd_buyForCoins2.ogg
  Games/Tiny-Fishing/html5game/snd_catchPop.ogg
  Games/Tiny-Fishing/html5game/snd_catchPopGolden.ogg
  Games/Tiny-Fishing/html5game/snd_coinAdded.ogg
  Games/Tiny-Fishing/html5game/snd_coinCollect.ogg
  Games/Tiny-Fishing/html5game/snd_coins.ogg
  Games/Tiny-Fishing/html5game/snd_fishReel.ogg
  Games/Tiny-Fishing/html5game/snd_levComplBest.ogg
  Games/Tiny-Fishing/html5game/snd_musicBackground.ogg
  Games/Tiny-Fishing/html5game/snd_openPrize.ogg
  Games/Tiny-Fishing/html5game/snd_pop.ogg
  Games/Tiny-Fishing/html5game/snd_splash1.ogg
  Games/Tiny-Fishing/html5game/snd_splash2.ogg
  Games/Tiny-Fishing/html5game/snd_startFishing.ogg
  Games/Tiny-Fishing/html5game/snd_swoosh.ogg
  Games/Tiny-Fishing/html5game/snd_unlockHook.ogg
  Games/Tiny-Fishing/html5game/snd_upgradeSnd.ogg
  Games/Tiny-Fishing/html5game/snd_water.ogg
  Games/Tiny-Fishing/html5game/tph_PokiExt.js
  Games/Tiny-Fishing/html5game/trads.csv
  Games/Tiny-Fishing/html5game/uph_cookieManager.js
  Games/Tiny-Fishing/html5game/vph_HTML5Func.js
  Games/Tiny-Fishing/html5game/wph_API_Fullscreen.js
  Games/Tiny-Fishing/html5game/xph_external.js
  Games/Tiny-Fishing/html5game/zph_djl.js
  Games/Tiny-Fishing/index.html
  Games/Tiny-Fishing/thumb.png
  Games/Tiny-Fishing/tiny-fishing.png
  README.md
  assets/images/Tiny-fishing.png
  assets/images/tiny-fishing.webp
  assets/index_old.html
  assets/js/gamesData.json
Labels: level3, gssoc

#3805 Random joke generator
  Games/Random_Joke_Generator/README.md
  Games/Random_Joke_Generator/index.html
  Games/Random_Joke_Generator/script.js
  Games/Random_Joke_Generator/styles.css
  README.md
  assets/images/Random_Joke_Generator.jpeg
Labels: Pending ⏱️

#3808 candy crush saga added
  Games/Candy_Crush_Saga/Images/blue-candy.png
  Games/Candy_Crush_Saga/Images/green-candy.png
  Games/Candy_Crush_Saga/Images/orange-candy.png
  Games/Candy_Crush_Saga/Images/purple-candy.png
  Games/Candy_Crush_Saga/Images/red-candy.png
  Games/Candy_Crush_Saga/Images/yellow-candy.png
  Games/Candy_Crush_Saga/README.md
  Games/Candy_Crush_Saga/candy-crush-background-2.png
  Games/Candy_Crush_Saga/index.html
  Games/Candy_Crush_Saga/script.js
  Games/Candy_Crush_Saga/style.css
  README.md
  assets/images/Candy_Crush_Saga.png
  assets/js/gamesData.json
Labels: Pending ⏱️

#3816 Knife Hit game added
  Games/Knife_hit/README.md
  Games/Knife_hit/index.html
  Games/Knife_hit/knife.png
  Games/Knife_hit/script.js
  Games/Knife_hit/styles.css
  README.md
  assets/images/Knife_hit.png
  assets/js/gamesData.json
Labels: Pending ⏱️

#3831 Added game Laser Darts
  Games/LaserDarts/README.md
  Games/LaserDarts/index.html
  Games/LaserDarts/script.js
  Games/LaserDarts/styles.css
  README.md
  assets/images/LaserDarts.png
Labels: level3, gssoc

#3832 Added Catch_Stars Game
  Games/Catch_Stars/README.md
  Games/Catch_Stars/app.js
  Games/Catch_Stars/index.html
  Games/Catch_Stars/style.css
  README.md
  assets/images/Catch_Stars.jpeg
Labels: level3, gssoc

#3834 Created Arkanoid game
  Games/Arkanoid_Game/README.md
  Games/Arkanoid_Game/index.html
  Games/Arkanoid_Game/script.js
  Games/Arkanoid_Game/style.css
  README.md
  assets/images/Arkanoid_Game (1).png
  assets/images/Arkanoid_Game (2).png
Labels: Pending ⏱️

#3835 Tushar/main
  Games/Piano/index.html
  Games/Piano/script.js
  Games/Piano/style.css
  Games/Run and Jump/ads.wav
  Games/Run and Jump/script.js
Labels: level2, gssoc

#3840 new game NewsJunction added
  Games/NewsJunction/README.md
  Games/NewsJunction/index.html
  README.md
  assets/images/NewsJunction.png
Labels: level3, gssoc

#3759 Anagram Checker Game #3510
  Games/Anagram_Checker_Game/README.md
  Games/Anagram_Checker_Game/index.html
  Games/Anagram_Checker_Game/script.js
  Games/Anagram_Checker_Game/styles.css
  README.md
  assets/images/Anagram_Checker_Game.png
  assets/index_old.html
  assets/js/gamesData.json
Labels: level3, gssoc

#3870 Added new game Virtual Pet
  Games/Virtual_Pet/README.md
  Games/Virtual_Pet/assets/pet-happy.png
  Games/Virtual_Pet/assets/pet-neutral.png
  Games/Virtual_Pet/assets/pet-sad.png
  Games/Virtual_Pet/index.html
  Games/Virtual_Pet/script.js
  Games/Virtual_Pet/styles.css
  README.md
  assets/images/Virtual_Pet.png
Labels: level3, gssoc

#3879 16-puzzle added
  Games/16_Puzzle/README.md
  Games/16_Puzzle/index.html
  Games/16_Puzzle/script.js
  Games/16_Puzzle/style.css
  README.md
  assets/images/16_Puzzle.png
  assets/js/gamesData.json
Labels: Pending ⏱️

#3891 Added Recognizing_figures Game
  Games/Recognizing_Figures/README.md
  Games/Recognizing_Figures/app.js
  Games/Recognizing_Figures/index.html
  Games/Recognizing_Figures/style.css
  README.md
  assets/images/Recognizing_Figures.jpeg
Labels: Pending ⏱️

#3890 Adding : Color The Page Game
  Games/Color The Page/README.md
  Games/Color The Page/index.html
  Games/Color The Page/randomcolor.css
  Games/Color The Page/randomcolor.js
  README.md
  assets/images/Color the page.png
Labels: level3, gssoc

#3916 Added Find_the_ball Game
  Games/Find_the_ball/README.md
  Games/Find_the_ball/app.js
  Games/Find_the_ball/index.html
  Games/Find_the_ball/style.css
  README.md
  assets/images/Find_the_ball.jpeg
Labels: level3, gssoc

#3936 Added Musical Memory Game
  Games/Musical_Memory/Images/Screenshot 2024-05-30 233405.png
  Games/Musical_Memory/Images/Screenshot 2024-05-30 233432.png
  Games/Musical_Memory/Musical_Memory.html
  Games/Musical_Memory/readme.md
  Games/Musical_Memory/script.js
  Games/Musical_Memory/soundsA.wav
  Games/Musical_Memory/soundsB.wav
  Games/Musical_Memory/soundsC.wav
  Games/Musical_Memory/soundsD.wav
  Games/Musical_Memory/soundsE.wav
  Games/Musical_Memory/soundsF.wav
  Games/Musical_Memory/soundsG.wav
  Games/Musical_Memory/style.css
  Games/Pixel_Painter/README.md
  Games/Pixel_Painter/index.html
  Games/Pixel_Painter/script.js
  Games/Pixel_Painter/styles.css
  README.md
  assets/images/Pixel_Painter.png
Labels: Pending ⏱️
