Repository kunjgit/GameZone, pull requests merged in 2024-06, with the labels that each got.

#3948 pen pointer fight game wtr to #3889
  Games/PenPointerFight/Readme.md
  Games/PenPointerFight/index.html
  Games/pixel_painter/README.md
  Games/pixel_painter/index.html
  Games/pixel_painter/script.js
  Games/pixel_painter/styles.css
  README.md
  assets/images/PenPointerFight.png
  assets/js/gamesData.json
  assets/js/index.js
Labels: Pending ⏱️, Changes Requested ⚒️

#3881 Tic-Tac-Toe Game Added
  Games/Tic-Tac-Toe Game/README.md
  Games/Tic-Tac-Toe Game/index.html
  Games/Tic-Tac-Toe Game/script.js
  Games/Tic-Tac-Toe Game/styles.css
  README.md
  assets/images/Tic-Tac-Toe Game.png
Labels: Pending ⏱️, Changes Requested ⚒️

#3963 Random Colour Generator
  Games/Colour_Generator_Game/README.md
  Games/Colour_Generator_Game/index.html
  Games/Colour_Generator_Game/script.js
  Games/Colour_Generator_Game/style.css
  README.md
  assets/images/Colour_Generator_Game.png
  assets/js/gamesData.json
Labels: level3, gssoc

#3966 Added new rapid frenzy game
  Games/rapid_click_frenzy/README.md
  Games/rapid_click_frenzy/index.html
  Games/rapid_click_frenzy/script.js
  Games/rapid_click_frenzy/styles.css
  README.md
  assets/images/rapidgame.png
  assets/js/gamesData.json
Labels: Pending ⏱️

#3969 New game added :- Reflex Game
  Games/Reflex_Game/README.md
  Games/Reflex_Game/index.html
  Games/Reflex_Game/script.js
  Games/Reflex_Game/style.css
  README.md
  assets/images/Reflex_Game.png
  assets/images/Reflex_Game.webp
Labels: Pending ⏱️

#3970 Screen pet game
  Games/Screen_Pet_Game/README.md
  Games/Screen_Pet_Game/assets/images/Screen_Pet_Game_1.png
  Games/Screen_Pet_Game/assets/images/Screen_Pet_Game_2.png
  Games/Screen_Pet_Game/assets/images/Screen_Pet_Game_3.png
  Games/Screen_Pet_Game/assets/images/Screen_Pet_Game_4.png
  Games/Screen_Pet_Game/index.html
  Games/Screen_Pet_Game/script.js
  Games/Screen_Pet_Game/styles.css
  README.md
  assets/images/Screen_Pet_Game.png
  assets/js/gamesData.json
Labels: Pending ⏱️

#3971 new game added:-color matcher
  Games/color matcher/README.md
  Games/color matcher/ReadMe.md
  Games/color matcher/Screenshot 2024-05-21 144653.png
  Games/color matcher/index.html
  Games/color matcher/script.js
  Games/color matcher/styles.css
  README.md
  assets/images/Screenshot 2024-05-21 144653.png
  color matcher
Labels: Pending ⏱️, Changes Requested ⚒️

#3978 Solved issue #3977- Forest Guardian Game
  Games/Forest_Guardian/README.md
  Games/Forest_Guardian/index.html
  Games/Forest_Guardian/script.js
  Games/Forest_Guardian/styles.css
  README.md
  assets/Forest_guardian.png
  assets/images/Forest_guardian.png
Labels: level3, gssoc

#3987 Scroll to top button added
  assets/js/scroll.js
  index.html
Labels: level1, gssoc

#4013 Adding Love Calculator Game
  Games/Love Calculator Game/README.md
  Games/Love Calculator Game/heart.png
  Games/Love Calculator Game/index.html
  Games/Love Calculator Game/script.js
  Games/Love Calculator Game/style.css
  README.md
  assets/images/Love calculator game.png
Labels: Pending ⏱️

#4042 Aqua sort
  Games/AquaSort_Game/README.md
  Games/AquaSort_Game/index.html
  Games/AquaSort_Game/script.js
  Games/AquaSort_Game/style.css
  README.md
  assets/images/AquaSort.png
  assets/images/Pixel_Painter.png
  assets/images/pixel_painter.png
Labels: Pending ⏱️, Changes Requested ⚒️

#4049 added new game Hit the hamster
  Games/Hit_the_hamster/README.md
  Games/Hit_the_hamster/images/Hit_the_hamster.webp
  Games/Hit_the_hamster/images/Hit_the_hamster_board.webp
  Games/Hit_the_hamster/index.html
  Games/Hit_the_hamster/script.js
  Games/Hit_the_hamster/style.css
  README.md
  assets/images/Hit_the_hamster_game.png
Labels: Pending ⏱️

#4067 math quiz wrt #4063
  Games/MathQuiz/Readme.md
  Games/MathQuiz/index.html
  Games/MathQuiz/script.js
  Games/MathQuiz/styles.css
  README.md
  assets/images/MathQuiz.png
  assets/js/gamesData.json
  assets/js/index.js
Labels: Pending ⏱️, Changes Requested ⚒️

#4076 [New Game] Roll_The_Dice game added
  Games/Roll_The_Dice/README.md
  Games/Roll_The_Dice/index.html
  Games/Roll_The_Dice/index.js
  Games/Roll_The_Dice/styles.css
  README.md
  assets/images/Roll_The_Dice.png
  assets/images/Roll_The_Dice.webp.png
Labels: Pending ⏱️

#4170 Added turn on the light game
  Games/Turn_on_the_light/README.md
  Games/Turn_on_the_light/index.html
  Games/Turn_on_the_light/script.js
  Games/Turn_on_the_light/style.css
  README.md
  assets/images/turnonthelight.jpg
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4129 Black breaker game added
  Games/Menja_block_breaker/README.md
  Games/Menja_block_breaker/index.html
  Games/Menja_block_breaker/script.js
  Games/Menja_block_breaker/style.css
  README.md
  assets/images/Menja.png
  assets/images/menja_Block_breaker.png
  assets/js/gamesData.json
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#3247 Added a button.
  Games/Wault_master/app.js
  Games/Wault_master/dist/output.css
  Games/Wault_master/index.html
Labels: level2, Ready to merge 🥳, gssoc

#4235 new game brick buster added
  Games/Brick Buster/README.md
  Games/Brick Buster/index.html
  Games/Brick Buster/script.js
  Games/Brick Buster/style.css
  README.md
  assets/images/brick.png
  assets/js/gamesData.json
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4094 Cartoon character guessing game
  Games/Cartoon_Character_Guessing_Game/README.md
  Games/Cartoon_Character_Guessing_Game/game.html
  Games/Cartoon_Character_Guessing_Game/images/image_01.png
  Games/Cartoon_Character_Guessing_Game/images/image_02.png
  Games/Cartoon_Character_Guessing_Game/images/image_03.png
  Games/Cartoon_Character_Guessing_Game/index.html
  Games/Cartoon_Character_Guessing_Game/script.js
  Games/Cartoon_Character_Guessing_Game/style.css
  README.md
  assets/images/Cartoon_Character_Guessing_Game.png
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4087 Adding building block game wrt #4056
  Games/Buliding Block Game/Readme.md
  Games/Buliding Block Game/assets
  Games/Buliding Block Game/index.html
  Games/Buliding Block Game/script.js
  Games/Buliding Block Game/style.css
  README.md
  assets/images/Building Block Game.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4019 Added Home Icon in Connect 4 game
  .github/workflows/pr_tags.yaml
  Games/Connect_Four/index.html
Labels: level1, Ready to merge 🥳, gssoc

#4147 added Reverse memory game
  Games/Reverse Memory Game
  Games/Reverse Memory/README.md
  Games/Reverse Memory/index.html
  Games/Reverse Memory/script.js
  Games/Reverse Memory/styles.css
  README.md
  assets/images/Reverse_Memory.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4114 Footer improved
  assets/css/style.css
  index.html
Labels: level1, Ready to merge 🥳, gssoc

#4188 Added Anagram-word-game
  Games/Anagram -Word-Game/README.md
  Games/Anagram -Word-Game/index.html
  Games/Anagram -Word-Game/script.js
  Games/Anagram -Word-Game/style.css
  README.md
  assets/images/Anagram-Word-Game.jpeg
Labels: Pending ⏱️

#4193 New game :- Gravity_Simulation_Game
  Games/Gravity_Simulation_Game/README.md
  Games/Gravity_Simulation_Game/index.html
  Games/Gravity_Simulation_Game/script.js
  Games/Gravity_Simulation_Game/style.css
  README.md
  assets/images/Gravity_Simulation_Game.png
  assets/images/Gravity_Simulation_Game.webp
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4151 [Enhancement]: Whack a Mole : Game's start button's style should be modified and there should be a message after starting the game
  Games/Master_Typing/README.md
  Games/Whack_a_Mole/README.md
  Games/Whack_a_Mole/audio/game-music.mp3
  Games/Whack_a_Mole/audio/game-over.mp3
  Games/Whack_a_Mole/index.html
  Games/Whack_a_Mole/mole.css
  Games/Whack_a_Mole/mole.js
Labels: level1, Ready to merge 🥳, gssoc

#4104 Added Physics quiz game: #4092
  Games/Physics_Quizz/README.md
  Games/Physics_Quizz/assets/background_image.jpeg
  Games/Physics_Quizz/index.html
  Games/Physics_Quizz/script.js
  Games/Physics_Quizz/style.css
  README.md
  assets/images/Physics_Quizz.png
Labels: Pending ⏱️, level2, Ready to merge 🥳, gssoc

#4262 Dsa_quiz game added
  Games/Dsa_quiz_game/README.md
  Games/Dsa_quiz_game/index.html
  Games/Dsa_quiz_game/script.js
  Games/Dsa_quiz_game/style.css
  README.md
  assets/images/Dsa_quiz1.png
  assets/images/Dsa_quiz2.png
Labels: Pending ⏱️

#4234 Added Chess game with Computer
  Games/Chess_Game_computer/README.md
  Games/Chess_Game_computer/index.html
  Games/Chess_Game_computer/script.js
  Games/Chess_Game_computer/style.css
  README.md
  assets/images/chessComputer.png
Labels: Pending ⏱️, Changes Requested ⚒️, level2, Ready to merge 🥳, gssoc

#4200 Quick Click
  .gitignore
  Games/Quick_Click/README.md
  Games/Quick_Click/assets/Images/image.png
  Games/Quick_Click/index.html
  Games/Quick_Click/script.js
  Games/Quick_Click/style.css
  README.md
  assets/images/Quick Click.png
Labels: Pending ⏱️, Changes Requested ⚒️, level2, Ready to merge 🥳, gssoc

#4388 Number_Guessing_Game
  Games/Number_Guessing_Game/README.md
  Games/Number_Guessing_Game/favicon/android-chrome-192x192.png
  Games/Number_Guessing_Game/favicon/android-chrome-512x512.png
  Games/Number_Guessing_Game/favicon/apple-touch-icon.png
  Games/Number_Guessing_Game/favicon/favicon-16x16.png
  Games/Number_Guessing_Game/favicon/favicon-32x32.png
  Games/Number_Guessing_Game/favicon/favicon.ico
  Games/Number_Guessing_Game/favicon/site.webmanifest
  Games/Number_Guessing_Game/index.html
  README.md
  assets/images/NumberGuessingGame.png
Labels: Pending ⏱️, level2, Ready to merge 🥳, gssoc

#4286 soccer game added
  Games/Soccer/README.md
  Games/Soccer/index.html
  Games/Soccer/script.js
  Games/Soccer/style.css
  README.md
  assets/images/Soccer.png
  assets/js/gamesData.json
  assets/js/index.js
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4285 Fixes #4282
  Games/Intellect_Quest/README.md
  Games/Intellect_Quest/index.html
  Games/Intellect_Quest/script.js
  Games/Intellect_Quest/style.css
  README.md
  assets/images/Intellect_Quest.png
Labels: Pending ⏱️, Changes Requested ⚒️, level2, Ready to merge 🥳, gssoc

#4284 Added Grab The carrot
  Games/Grab_The_Carrot/README.md
  Games/Grab_The_Carrot/index.html
  Games/Grab_The_Carrot/script.js
  Games/Grab_The_Carrot/styles.css
  README.md
  assets/images/grabthecarrot.png
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4253 Update README.md
  README.md
Labels: level1, Ready to merge 🥳, gssoc

#4270 Added Morse_Code_Generator
  Games/Morse_Code_Generator/README.md
  Games/Morse_Code_Generator/index.html
  Games/Morse_Code_Generator/script.js
  Games/Morse_Code_Generator/style.css
  README.md
  assets/images/Morse_Code_Generator.png
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4277 fixed #4259
  README.md
  assets/images/demo_bug.jpeg
  index.html
Labels: Pending ⏱️, level1, Changes Requested ⚒️, Ready to merge 🥳, gssoc

#4440 Anjaliavv51/issue4313
  Games/Computer_Bingo/README.md
  Games/Computer_Bingo/WhatsApp Video 2024-06-07 at 18.53.41_01758a15.mp4
  Games/Computer_Bingo/favicon/image.png
  Games/Computer_Bingo/image.png
  Games/Computer_Bingo/index.html
  Games/Computer_Bingo/script.js
  Games/Computer_Bingo/style.css
  README.md
  assets/images/Computer_Bingo.png
  assets/images/image.png
Labels: Ready to merge 🥳, level3, gssoc

#4397 Added Typing Speed Test Game
  Games/Typing_Speed_Test2/README.md
  Games/Typing_Speed_Test2/assets/images/Typing_Speed_Test2.png
  Games/Typing_Speed_Test2/data.js
  Games/Typing_Speed_Test2/index.html
  Games/Typing_Speed_Test2/script.js
  Games/Typing_Speed_Test2/style.css
  README.md
  assets/images/Typing_Speed_Test2.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4433 Added Tower Block game
  Games/Tower_Block_Game/README.md
  Games/Tower_Block_Game/index.html
  Games/Tower_Block_Game/script.js
  Games/Tower_Block_Game/styles.css
  README.md
  assets/images/Tower_Block_Game.png
Labels: level2, Ready to merge 🥳, gssoc

#4358 [Enhancement]: UI OF brick game
  Games/Brick_Breaker/README.md
  Games/Brick_Breaker/index.html
  Games/Brick_Breaker/script.js
  Games/Brick_Breaker/styles.css
Labels: level2, Ready to merge 🥳, gssoc

#4357 Resolved Dark mode issue
  assets/js/script.js
Labels: level1, Ready to merge 🥳, gssoc

#4345 Added Alphabet and Vowels Game
  Games/Alphabet-and-Vowels/README.md
  Games/Alphabet-and-Vowels/app.js
  Games/Alphabet-and-Vowels/index.html
  Games/Alphabet-and-Vowels/style.css
  README.md
  assets/images/Alphabet-and-Vowels.jpeg
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4337 Added Block_Ninja Game to the Repository
  Games/Block_Ninja/README.md
  Games/Block_Ninja/index.html
  Games/Block_Ninja/script.js
  Games/Block_Ninja/style.css
  README.md
  assets/images/Block_Ninja.png
Labels: level2, Ready to merge 🥳, gssoc

#4315 Updating UI of memory game
  Games/Memory_Game/img1.jpg
  Games/Memory_Game/index.html
  Games/Memory_Game/mind.jpeg
  Games/Memory_Game/mind.png
  Games/Memory_Game/mind1.jpg
  Games/Memory_Game/script.js
  Games/Memory_Game/style.css
  assets/images/memory-game.png
Labels: level2, Ready to merge 🥳, gssoc

#4310 added restart button and enhanced text style and size
  Games/Tilting_Maze/index.html
  Games/Tilting_Maze/script.js
  Games/Tilting_Maze/style.css
Labels: level1, Ready to merge 🥳, gssoc

#4294 Added new game:- SNAKE
  Games/snake/README.md
  Games/snake/index.html
  Games/snake/script.js
  Games/snake/style.css
  README.md
  assets/images/snake.png
Labels: Pending ⏱️, level2, Ready to merge 🥳, gssoc

#4461 Added new Game "Harmony Mixer"
  Games/Harmony_Mixer/Assets/Background.svg
  Games/Harmony_Mixer/Assets/Pause-button.png
  Games/Harmony_Mixer/Assets/Play-button.png
  Games/Harmony_Mixer/Assets/Reset.png
  Games/Harmony_Mixer/Assets/Upload-2.png
  Games/Harmony_Mixer/Assets/Upload.png
  Games/Harmony_Mixer/Assets/logo.svg
  Games/Harmony_Mixer/README.md
  Games/Harmony_Mixer/index.html
  Games/Harmony_Mixer/script.js
  Games/Harmony_Mixer/style.css
  README.md
  assets/images/Harmony_Mixer.png
Labels: Ready to merge 🥳, level3, gssoc

#4451 [Enhancement]: Addition of Chatbot
  index.html
Labels: level1, Ready to merge 🥳, gssoc

#4450 Added Tic Tac Toe
  Games/Tic_tac_toe_responsive/README.md
  Games/Tic_tac_toe_responsive/assets/images/PointerBody.png
  Games/Tic_tac_toe_responsive/assets/images/PointerHover.png
  Games/Tic_tac_toe_responsive/assets/images/PointerText.png
  Games/Tic_tac_toe_responsive/assets/images/Tic_tac_toe_responsive.png
  Games/Tic_tac_toe_responsive/index.html
  Games/Tic_tac_toe_responsive/script.js
  Games/Tic_tac_toe_responsive/style.css
  README.md
  assets/images/Tic_tac_toe_responsive.png
Labels: Ready to merge 🥳, level3, gssoc

#4439 Added game Disney Trivia
  Games/Disney_Trivia/README.md
  Games/Disney_Trivia/disney_b.jpg
  Games/Disney_Trivia/index.html
  Games/Disney_Trivia/script.js
  Games/Disney_Trivia/style.css
  README.md
  assets/images/Disney_Trivia.png
Labels: Ready to merge 🥳, level3, gssoc

#4415 Kill The Bird game added
  Games/Kill_The_Bird/index.html
  Games/Kill_The_Bird/styles.css
  Games/Virtual_Pet/README.md
  README.md
  assets/images/grabthecarrot.png
  assets/images/killthebird.jpeg
Labels: Ready to merge 🥳, level3, gssoc

#4361 Added Tetris Game
  Games/Tetris_Game/Readme.md
  Games/Tetris_Game/assets/Board/Board.png
  Games/Tetris_Game/assets/Shape Blocks/I.png
  Games/Tetris_Game/assets/Shape Blocks/I1.png
  Games/Tetris_Game/assets/Shape Blocks/J.png
  Games/Tetris_Game/assets/Shape Blocks/J1.png
  Games/Tetris_Game/assets/Shape Blocks/J2.png
  Games/Tetris_Game/assets/Shape Blocks/J3.png
  Games/Tetris_Game/assets/Shape Blocks/L.png
  Games/Tetris_Game/assets/Shape Blocks/L1.png
  Games/Tetris_Game/assets/Shape Blocks/L2.png
  Games/Tetris_Game/assets/Shape Blocks/L3.png
  Games/Tetris_Game/assets/Shape Blocks/O.png
  Games/Tetris_Game/assets/Shape Blocks/S.png
  Games/Tetris_Game/assets/Shape Blocks/S1.png
  Games/Tetris_Game/assets/Shape Blocks/T.png
  Games/Tetris_Game/assets/Shape Blocks/T1.png
  Games/Tetris_Game/assets/Shape Blocks/T2.png
  Games/Tetris_Game/assets/Shape Blocks/T3.png
  Games/Tetris_Game/assets/Shape Blocks/Z.png
  Games/Tetris_Game/assets/Shape Blocks/Z1.png
  Games/Tetris_Game/assets/Single Blocks/Blue.png
  Games/Tetris_Game/assets/Single Blocks/Green.png
  Games/Tetris_Game/assets/Single Blocks/LightBlue.png
  Games/Tetris_Game/assets/Single Blocks/Orange.png
  Games/Tetris_Game/assets/Single Blocks/Purple.png
  Games/Tetris_Game/assets/Single Blocks/Red.png
  Games/Tetris_Game/assets/Single Blocks/Yellow.png
  Games/Tetris_Game/assets/Sound Effects/clear-lines.mp3
  Games/Tetris_Game/assets/Title/Title.png
  Games/Tetris_Game/assets/Title/retry.png
  Games/Tetris_Game/index.html
  Games/Tetris_Game/main.js
  Games/Tetris_Game/style.css
  README.md
  assets/images/black.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4351 Solved issue #4187- Tower Defence Game
  Games/Tower_Defence_Game/README.md
  Games/Tower_Defence_Game/Tower_Game.png
  Games/Tower_Defence_Game/game.js
  Games/Tower_Defence_Game/index.html
  Games/Tower_Defence_Game/styles.css
  README.md
  assets/images/Tower_Game.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4376 Noughts And Crosses
  Games/Noughts_And_Crosses/README.md
  Games/Noughts_And_Crosses/index.html
  Games/Noughts_And_Crosses/style.css
  Games/Noughts_And_Crosses/style.js
  README.md
  assets/images/Noughts_And_Crosses.png
Labels: Pending ⏱️, Changes Requested ⚒️, level2, Ready to merge 🥳, gssoc

#4407 Added Word shuffle game
  Games/Word_Shuffle_Game/README.md
  Games/Word_Shuffle_Game/index.html
  Games/Word_Shuffle_Game/script.js
  Games/Word_Shuffle_Game/style.css
  README.md
  assets/images/shuffle.png
Labels: Ready to merge 🥳, level3, gssoc

#4409 [New-Game] Lunar_Lander Added
  Games/Lunar_Lander/README.md
  Games/Lunar_Lander/css/index.css
  Games/Lunar_Lander/index.html
  Games/Lunar_Lander/info.html
  Games/Lunar_Lander/js/delayer.js
  Games/Lunar_Lander/js/htmlfrontend.js
  Games/Lunar_Lander/js/lunarcalc.js
  Games/Lunar_Lander/js/lunarcontrol.js
  Games/Lunar_Lander/lunar.html
  README.md
  assets/images/Lunar_Lander.png
Labels: Ready to merge 🥳, level3, gssoc

#4445 Added ATLAS game
  .vscode/settings.json
  Games/Atlas_Game/README.md
  Games/Atlas_Game/bg.webp
  Games/Atlas_Game/index.html
  Games/Atlas_Game/places.json
  Games/Atlas_Game/script.js
  Games/Atlas_Game/style.css
  README.md
  assets/images/Atlas_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4455 Added Bouncing ball Game
  Games/Bouncing_Ball_Game/ReAdMe.md
  Games/Bouncing_Ball_Game/index.html
  Games/Bouncing_Ball_Game/script.js
  Games/Bouncing_Ball_Game/style.css
  README.md
  assets/images/Bouncing_Ball_Game.png
Labels: level2, Ready to merge 🥳, gssoc

#4468 Added Memory Matching Game
  Games/Memory_Matching_Game/README.md
  Games/Memory_Matching_Game/index.html
  Games/Memory_Matching_Game/script.js
  Games/Memory_Matching_Game/styles.css
  README.md
  assets/images/Memory_Matching_Game.png
Labels: level2, Ready to merge 🥳, gssoc

#4472 Shoot_Duck_Game
  Games/Shoot_Duck_Game/README.md
  Games/Shoot_Duck_Game/main.html
  Games/Shoot_Duck_Game/script.js
  Games/Shoot_Duck_Game/styles.css
  README.md
  assets/images/Shoot_Duck_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4473 Fruit Slicer
  Games/Fruit_Slicer_Game/README.md
  Games/Fruit_Slicer_Game/assets/audio_slicefruit.mp3
  Games/Fruit_Slicer_Game/assets/bg3 - Copy.jpg
  Games/Fruit_Slicer_Game/assets/image.png
  Games/Fruit_Slicer_Game/assets/slicefruit.ogg
  Games/Fruit_Slicer_Game/assets/slicefruit.wav
  Games/Fruit_Slicer_Game/assets/splash.png
  Games/Fruit_Slicer_Game/assets/wood-bg2.jpg
  Games/Fruit_Slicer_Game/assets/wrong.png
  Games/Fruit_Slicer_Game/index.html
  Games/Fruit_Slicer_Game/script.js
  Games/Fruit_Slicer_Game/style.css
  README.md
  assets/images/Fruit-Slicer.png
Labels: Ready to merge 🥳, level3, gssoc

#4476 Added CopyCat game
  Games/CopyCat/README.md
  Games/CopyCat/index.html
  Games/CopyCat/script.js
  Games/CopyCat/style.css
  README.md
  assets/images/CopyCat.png
  assets/images/CopyCat1.png
Labels: Ready to merge 🥳, level3, gssoc

#4485 Added Etch a Sketch 2
  Games/Etch_a_Sketch_2/README.md
  Games/Etch_a_Sketch_2/assets/images/Etch_a_Sketch_2.png
  Games/Etch_a_Sketch_2/index.html
  Games/Etch_a_Sketch_2/script.js
  Games/Etch_a_Sketch_2/style.css
  README.md
  assets/images/Etch_a_Sketch_2.png
Labels: Ready to merge 🥳, level3, gssoc

#4489 Added Minesweeper Easy
  Games/MineSweeper_Easy/README.md
  Games/MineSweeper_Easy/assets/images/MineSweeper_Easy.png
  Games/MineSweeper_Easy/index.html
  Games/MineSweeper_Easy/script.js
  Games/MineSweeper_Easy/style.css
  README.md
  assets/images/MineSweeper_Easy.png
Labels: Ready to merge 🥳, level3, gssoc

#4495 Steam Punk Game Added
  Games/Steam_Punk/README.md
  Games/Steam_Punk/assets/angler1.png
  Games/Steam_Punk/assets/angler2.png
  Games/Steam_Punk/assets/drone.png
  Games/Steam_Punk/assets/fireExplosion.png
  Games/Steam_Punk/assets/gears.png
  Games/Steam_Punk/assets/hivewhale.png
  Games/Steam_Punk/assets/layer1.png
  Games/Steam_Punk/assets/layer2.png
  Games/Steam_Punk/assets/layer3.png
  Games/Steam_Punk/assets/layer4.png
  Games/Steam_Punk/assets/lucky.png
  Games/Steam_Punk/assets/player.png
  Games/Steam_Punk/assets/projectile.png
  Games/Steam_Punk/assets/smokeExplosion.png
  Games/Steam_Punk/index.html
  Games/Steam_Punk/script.js
  Games/Steam_Punk/style.css
  README.md
  assets/images/Steam_Punk.png
Labels: Ready to merge 🥳, level3, gssoc

#4422 Update README.md
  README.md
Labels: level1, Ready to merge 🥳, gssoc

#4502 Add Social media Instagram
  index.html
Labels: level1, Ready to merge 🥳, gssoc

#4431 Added Mario Game
  Games/mario-game/README.md
  Games/mario-game/bg.png
  Games/mario-game/brick.png
  Games/mario-game/checkPoint.mp3
  Games/mario-game/collided.png
  Games/mario-game/die.mp3
  Games/mario-game/gameOver.png
  Games/mario-game/ground2.png
  Games/mario-game/index.html
  Games/mario-game/jump.mp3
  Games/mario-game/mario00.png
  Games/mario-game/mario01.png
  Games/mario-game/mario02.png
  Games/mario-game/mario03.png
  Games/mario-game/myMario_Game_2020_12_22_09_54_02.zip
  Games/mario-game/obstacle1.png
  Games/mario-game/obstacle2.png
  Games/mario-game/obstacle3.png
  Games/mario-game/obstacle4.png
  Games/mario-game/p5.dom.min.js
  Games/mario-game/p5.js
  Games/mario-game/p5.play.js
  Games/mario-game/p5.sound.min.js
  Games/mario-game/restart.png
  Games/mario-game/sketch.js
  Games/mario-game/style.css
  README.md
  assets/images/mario-game (1).png
  assets/images/mario-game (10).png
  assets/images/mario-game (11).png
  assets/images/mario-game (12).png
  assets/images/mario-game (13).png
  assets/images/mario-game (2).png
  assets/images/mario-game (3).png
  assets/images/mario-game (4).png
  assets/images/mario-game (5).png
  assets/images/mario-game (6).png
  assets/images/mario-game (7).png
  assets/images/mario-game (8).png
  assets/images/mario-game (9).png
Labels: Ready to merge 🥳, level3, gssoc

#4264 Catch the ball
  Games/Catch_The_Ball/README.md
  Games/Catch_The_Ball/index.html
  Games/Catch_The_Ball/script.js
  Games/Catch_The_Ball/style.css
  README.md
  assets/images/catch-the-ball.png
Labels: Pending ⏱️, level2, Ready to merge 🥳, gssoc

#3939 New Game : Hit Or Miss 🏏
  Games/HitOrMiss/README.md
  Games/HitOrMiss/index.html
  Games/HitOrMiss/script.js
  Games/HitOrMiss/style.css
  README.md
  assets/images/HitOrMiss.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4000 Update README.md
  Games/CareTaker/README.md
Labels: Ready to merge 🥳, gssoc

#4033 Added Dice_Game
  Games/Dice_Game/README.md
  Games/Dice_Game/images/dice1.png
  Games/Dice_Game/images/dice2.png
  Games/Dice_Game/images/dice3.png
  Games/Dice_Game/images/dice4.png
  Games/Dice_Game/images/dice5.png
  Games/Dice_Game/images/dice6.png
  Games/Dice_Game/index.html
  Games/Dice_Game/script.js
  Games/Dice_Game/styles.css
  README.md
  assets/images/Dice_Game.png
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4196 Added a new game
  Games/Wordling/README.md
  Games/Wordling/Screenshot 2024-06-04 004406.png
  Games/Wordling/_config.yml
  Games/Wordling/dictionary.js
  Games/Wordling/index.html
  Games/Wordling/index.js
  Games/Wordling/package.json
  Games/Wordling/style.css
  README.md
  assets/images/Wordling.png
Labels: Pending ⏱️, level2, Ready to merge 🥳, gssoc

#4290 Added a new game GoFish
  Games/GoFish/GoFish.png
  Games/GoFish/README.MD
  Games/GoFish/index.html
  Games/GoFish/script.js
  Games/GoFish/style.css
  README.md
  assets/images/GoFish.png
Labels: Pending ⏱️, Changes Requested ⚒️, level2, Ready to merge 🥳, gssoc

#4348 mole
  Games/Mole/index.html
  Games/Mole/mole.css
  Games/Mole/mole.js
  Games/Mole/readme.md
  README.md
  assets/images/mario-bg.jpg.png
  assets/images/mole.png
  assets/images/pipe.png
  assets/images/piranha-plant.png
  assets/images/soil.png
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4378 [Feature]: Footer Enhancement
  assets/css/style.css
  index.html
Labels: level1, Ready to merge 🥳, gssoc

#4424 done #4420
  Games/Currency_Converter/README.md
  Games/Currency_Converter/app.js
  Games/Currency_Converter/codes.js
  Games/Currency_Converter/index.html
  Games/Currency_Converter/style.css
  README.md
  assets/images/Currency_Converter.png
  assets/images/Currency_Converter.wep.png
Labels: level2, Ready to merge 🥳, gssoc

#4494 Add Math race game (fixes #4418)
  Games/Math_Race_Game/README.md
  Games/Math_Race_Game/images/computer.png
  Games/Math_Race_Game/images/image_01.png
  Games/Math_Race_Game/images/image_02.png
  Games/Math_Race_Game/images/player.png
  Games/Math_Race_Game/index.html
  Games/Math_Race_Game/script.js
  Games/Math_Race_Game/styles.css
  README.md
  assets/images/Math_Race_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4507 Enhancement: All games recovered and 3D box game URL fixed
  assets/js/gamesData.json
  assets/js/index.js
  assets/js/script.js
Labels: level1, Ready to merge 🥳, gssoc

#4514 Puzzle game Added
  Games/puzzle-game/.vscode/settings.json
  Games/puzzle-game/README.md
  Games/puzzle-game/favicon.jpg
  Games/puzzle-game/index.html
  Games/puzzle-game/main.js
  Games/puzzle-game/style.css
  README.md
  assets/images/puzzle-game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#4525 Added New Game Cosmic Blast
  Games/Cosmic_Blast/README.md
  Games/Cosmic_Blast/assets/Cosmic_Blast.png
  Games/Cosmic_Blast/assets/asteroid-1.png
  Games/Cosmic_Blast/assets/asteroid-2.png
  Games/Cosmic_Blast/assets/asteroid-3.png
  Games/Cosmic_Blast/assets/background.jpg
  Games/Cosmic_Blast/assets/earth.png
  Games/Cosmic_Blast/assets/explode.mp3
  Games/Cosmic_Blast/index.html
  Games/Cosmic_Blast/script.js
  Games/Cosmic_Blast/style.css
  README.md
  assets/images/Cosmic_Blast.png
Labels: Ready to merge 🥳, level3, gssoc

#4535 Added Pong Game
  Games/Pong/README.md
  Games/Pong/assets/images/Pong.png
  Games/Pong/index.html
  Games/Pong/script.js
  Games/Pong/styles.css
  README.md
  assets/images/Pong.png
Labels: Ready to merge 🥳, level3, gssoc

#4536 Dot and Box game added
  Games/Dot_Box_Game/Readme.md
  Games/Dot_Box_Game/assets/dot_box_game.png
  Games/Dot_Box_Game/assets/initial_state.png
  Games/Dot_Box_Game/index.html
  Games/Dot_Box_Game/js/jquery.min.js
  Games/Dot_Box_Game/js/script.js
  Games/Dot_Box_Game/style.css
  README.md
  assets/images/Dot_Box_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4538 Audio Wordle Game
  Games/Audio_Wordle/README.md
  Games/Audio_Wordle/images/backspace-outline.svg
  Games/Audio_Wordle/images/d.svg
  Games/Audio_Wordle/images/github.svg
  Games/Audio_Wordle/images/return.svg
  Games/Audio_Wordle/index.html
  Games/Audio_Wordle/script.js
  Games/Audio_Wordle/style.css
  Games/Audio_Wordle/testAudio/Ae_Mere_Humsafar_Vinod.mp3
  Games/Audio_Wordle/testAudio/All_Iz_Well_Shaan.mp3
  Games/Audio_Wordle/testAudio/Kabira_Rekha.mp3
  Games/Audio_Wordle/testAudio/Maula_Javed.mp3
  Games/Audio_Wordle/testAudio/Tum_Se_Hi_Mohit.mp3
  Games/Audio_Wordle/testAudio/Zindagi_Ka_Naam_Dosti_Nitin.mp3
  README.md
  assets/images/Audio_Wordle.png
Labels: Ready to merge 🥳, level3, gssoc

#4545 Wheel_of_fortune
  Games/Wheel_of_fortune/README.md
  Games/Wheel_of_fortune/design.css
  Games/Wheel_of_fortune/index.html
  Games/Wheel_of_fortune/script.js
  README.md
  assets/images/Wheel_of_fortune.jpg
Labels: Ready to merge 🥳, level3, gssoc

#4549 Added About us page for modulo game
  Games/Modulo_Game/about.css
  Games/Modulo_Game/about.html
  Games/Modulo_Game/index.html
Labels: level1, Ready to merge 🥳, gssoc

#4551 [New game]: Ghost Busting Added
  Games/Ghost_busting_game/back1.jpg
  Games/Ghost_busting_game/background.jpg
  Games/Ghost_busting_game/game window.png
  Games/Ghost_busting_game/ghost_busting.png
  Games/Ghost_busting_game/index.html
  Games/Ghost_busting_game/readme.md
  Games/Ghost_busting_game/score.png
  Games/Ghost_busting_game/style.css
  README.md
  assets/images/ghost_busting.png
  assets/images/ghost_busting_gamewindow.png
Labels: Ready to merge 🥳, level3, gssoc

#4555 Added Wheel Of Fortunes game
  Games/Wheel_of_Fortunes/README.md
  Games/Wheel_of_Fortunes/Wheel_of_Fortune.png
  Games/Wheel_of_Fortunes/index.html
  Games/Wheel_of_Fortunes/script.js
  Games/Wheel_of_Fortunes/styles.css
  README.md
  assets/images/Wheel_of_Fortunes.png
Labels: Ready to merge 🥳, level3, gssoc

#4546 added new pottery game
  Games/Pottery-Game/README.md
  Games/Pottery-Game/test.html
  README.md
  assets/images/Pottery.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#4369 New Game : Ganesh QR Maker
  Games/Ganesh QR Maker/QR CODE Generator.png
  Games/Ganesh QR Maker/README.md
  Games/Ganesh QR Maker/index.html
  Games/Ganesh QR Maker/script.js
  Games/Ganesh QR Maker/style.css
  README.md
  assets/images/Ganesh QR Maker'.png
Labels: Pending ⏱️, Changes Requested ⚒️, level2, Ready to merge 🥳, gssoc

#4523 Spirograph
  Games/Spirograph/Readme.md
  Games/Spirograph/index.html
  Games/Spirograph/main.js
  Games/Spirograph/style.css
  README.md
  assets/images/Spirograph.png
Labels: Ready to merge 🥳, level3, gssoc

#4616 Enhancement of carrom game UI
  Games/Carrom/carrom.html
  Games/Carrom/css/main.css
  Games/Carrom/js/canvasCalls.js
  Games/Carrom/js/main.js
Labels: level1, Ready to merge 🥳, gssoc

#4619 Added New game Tic Tac Toe
  Games/Tic-tac-toe/README.md
  Games/Tic-tac-toe/index.html
  Games/Tic-tac-toe/panda.avif
  Games/Tic-tac-toe/script.js
  Games/Tic-tac-toe/styles.css
  Games/Tic-tac-toe/win-music.mp3
  README.md
  assets/images/Tic-tac-toe.png
Labels: level2, Ready to merge 🥳, gssoc

#4336 New Game: Catch_The_Falling_Objects
  Games/Catch_The_Falling_Object/README.md
  Games/Catch_The_Falling_Object/index.html
  Games/Catch_The_Falling_Object/script.js
  Games/Catch_The_Falling_Object/style.css
  README.md
  assets/images/Catch_the_falling_object-1.png
  assets/images/Catch_the_falling_object_2.png
Labels: Pending ⏱️, level2, Ready to merge 🥳, gssoc

#4560 Added Cross the river game
  Games/Cross_The_River_Game/README.md
  Games/Cross_The_River_Game/css/main.css
  Games/Cross_The_River_Game/favicon.png
  Games/Cross_The_River_Game/img/boat.png
  Games/Cross_The_River_Game/img/cabbage.png
  Games/Cross_The_River_Game/img/farmer.png
  Games/Cross_The_River_Game/img/goat.png
  Games/Cross_The_River_Game/img/wolf.png
  Games/Cross_The_River_Game/index.html
  Games/Cross_The_River_Game/js/Boat.js
  Games/Cross_The_River_Game/js/Passenger.js
  Games/Cross_The_River_Game/js/aux.js
  Games/Cross_The_River_Game/js/main.js
  Games/Cross_The_River_Game/screenshot.png
  Games/Cross_The_River_Game/sw.js
  README.md
  assets/images/Cross_The_River.png
  assets/images/Cross_The_River.webp
Labels: Ready to merge 🥳, level3, gssoc

#4573 Drawing App Game
  Games/Drawing_app/Drawing_app.png
  Games/Drawing_app/Readme.md
  Games/Drawing_app/icons/brush.svg
  Games/Drawing_app/icons/circle.svg
  Games/Drawing_app/icons/eraser.svg
  Games/Drawing_app/icons/rectangle.svg
  Games/Drawing_app/icons/triangle.svg
  Games/Drawing_app/index.html
  Games/Drawing_app/script.js
  Games/Drawing_app/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4586 TownRise game added
  Games/Town_Rise_Game/index.html
  Games/Town_Rise_Game/js/army.js
  Games/Town_Rise_Game/js/buildings.js
  Games/Town_Rise_Game/js/events.js
  Games/Town_Rise_Game/js/game.js
  Games/Town_Rise_Game/js/gameTime.js
  Games/Town_Rise_Game/js/handleInput.js
  Games/Town_Rise_Game/js/jobs.js
  Games/Town_Rise_Game/js/load-save.js
  Games/Town_Rise_Game/js/resources.js
  Games/Town_Rise_Game/style.css
  README.md
  assets/images/TownRise-game.png
Labels: Ready to merge 🥳, level3, gssoc

#4624 Added responsive NavBar in the Homepage. issue #3577
  assets/css/navbar.css
  index.html
Labels: level1, Ready to merge 🥳, gssoc

#4558 [New game]: Dot dash
  Games/Dot_Dash/README.md
  Games/Dot_Dash/assets/images/Dot_Dash.png
  Games/Dot_Dash/assets/images/README.md
  Games/Dot_Dash/index.html
  Games/Dot_Dash/script.js
  Games/Dot_Dash/styles.css
  README.md
  assets/images/Dot_Dash.png
Labels: Ready to merge 🥳, level3, gssoc

#4477 added new game Whack a mole
  Games/whack a mole/README.md
  Games/whack a mole/index.html
  Games/whack a mole/script.js
  Games/whack a mole/styles.css
  README.md
  assets/images/whack a mole.png
  assets/whack a mole.png
Labels: level2, Ready to merge 🥳, gssoc

#4501 Added KeySymphony Game
  Games/keySymphony/index1.html
  Games/keySymphony/index1.js
  Games/keySymphony/style1.css
  Games/keySymphony/tunes/;.wav
  Games/keySymphony/tunes/a.wav
  Games/keySymphony/tunes/d.wav
  Games/keySymphony/tunes/e.wav
  Games/keySymphony/tunes/f.wav
  Games/keySymphony/tunes/g.wav
  Games/keySymphony/tunes/h.wav
  Games/keySymphony/tunes/j.wav
  Games/keySymphony/tunes/k.wav
  Games/keySymphony/tunes/l.wav
  Games/keySymphony/tunes/o.wav
  Games/keySymphony/tunes/p.wav
  Games/keySymphony/tunes/s.wav
  Games/keySymphony/tunes/t.wav
  Games/keySymphony/tunes/u.wav
  Games/keySymphony/tunes/w.wav
  Games/keySymphony/tunes/y.wav
  README.md
  assets/images/KeySymphony.png
  assets/images/KeySymphony2.png
Labels: level2, Ready to merge 🥳, gssoc

#4142 Fidget spinner #4119
  Games/Fidget_Spinner_Game/README.md
  Games/Fidget_Spinner_Game/assets/images/Fidget.png
  Games/Fidget_Spinner_Game/index.html
  Games/Fidget_Spinner_Game/index.js
  Games/Fidget_Spinner_Game/styles.css
  README.md
  assets/images/Fidget.png
  assets/js/gamesData.json
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4579 Spell Bee
  Games/Spell_Bee/README.md
  Games/Spell_Bee/Spell Bee.png
  Games/Spell_Bee/assets/spell_bee_screenshot.png
  Games/Spell_Bee/index.html
  README.md
  assets/images/spell_bee.png
Labels: Ready to merge 🥳, level3, gssoc

#4590 Alien invasion
  Games/Alien_Invasion/.DS_Store
  Games/Alien_Invasion/README..md
  Games/Alien_Invasion/index.html
  Games/Alien_Invasion/script.js
  Games/Alien_Invasion/style.css
  README.md
  assets/images/Alien_Invasion.png
Labels: Ready to merge 🥳, level3, gssoc

#4645 Added sliding game
  Games/Sliding_puzzle/Readme.md
  Games/Sliding_puzzle/index.html
  Games/Sliding_puzzle/main.js
  Games/Sliding_puzzle/style.css
  README.md
  assets/images/Sliding_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4531 Added Car Racing Game to GameZone
  Games/Car_Racing_Game/README.md
  Games/Car_Racing_Game/__pycache__/utils.cpython-312.pyc
  Games/Car_Racing_Game/git
  Games/Car_Racing_Game/imgs/finish.png
  Games/Car_Racing_Game/imgs/grass.png
  Games/Car_Racing_Game/imgs/green-car.png
  Games/Car_Racing_Game/imgs/red-car.png
  Games/Car_Racing_Game/imgs/track-border.png
  Games/Car_Racing_Game/imgs/track.png
  Games/Car_Racing_Game/main.py
  Games/Car_Racing_Game/utils.py
  README.md
  assets/images/Car_Racing_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4567 Added Mario Matching Game
  Games/Mario Matching Game/01.jpg
  Games/Mario Matching Game/02.jpg
  Games/Mario Matching Game/03.jpg
  Games/Mario Matching Game/Readme.md
  Games/Mario Matching Game/index.html
  Games/Mario Matching Game/script.js
  Games/Mario Matching Game/style.css
  README.md
  assets/images/Mario Matching Game (1).jpg
  assets/images/Mario Matching Game (2).jpg
  assets/images/Mario Matching Game (3).jpg
Labels: Ready to merge 🥳, level3, gssoc

#4105 Pop the bubbles
  Games/Pop_the_Bubbles/Bubbles.jpg
  Games/Pop_the_Bubbles/README.md
  Games/Pop_the_Bubbles/index.html
  Games/Pop_the_Bubbles/script.js
  Games/Pop_the_Bubbles/style.css
  README.md
  assets/images/Bubbles.jpg
Labels: Pending ⏱️, Changes Requested ⚒️, Ready to merge 🥳, level3, gssoc

#4658 [New game]: Color swap
  Games/Color_Swap/README.md
  Games/Color_Swap/index.html
  Games/Color_Swap/script.js
  Games/Color_Swap/styles.css
  README.md
  assets/images/Color_Swap.png
Labels: Ready to merge 🥳, level3, gssoc

#4667 Tic_Tac_Toe_Neon added this game
  Games/Tic_Tac_Toe_Neon/index.html
  Games/Tic_Tac_Toe_Neon/readme.md
  Games/Tic_Tac_Toe_Neon/script.js
  Games/Tic_Tac_Toe_Neon/style.css
  README.md
  assets/images/Tic_Tac_Toe_Neon.JPG
Labels: level2, Ready to merge 🥳, gssoc

#4185 Changed font-size to 9.5vw from 5.5vw in heading class for GameZone
  assets/css/style.css
Labels: Ready to merge 🥳, gssoc
