Repository kunjgit/GameZone, pull requests merged in 2024-07, with the labels that each got.

#4565 Pac-Man Game
  Games/Pac_Man_Game/Img/Screenshot.png
  Games/Pac_Man_Game/README.md
  Games/Pac_Man_Game/index.html
  Games/Pac_Man_Game/script.js
  Games/Pac_Man_Game/style.css
  assets/images/Pac_Man_Thumbnail.png
Labels: level3, gssoc

#4639 Add 8_Puzzle Game
  Games/8_Puzzle/README.md
  Games/8_Puzzle/index.html
  Games/8_Puzzle/script.js
  Games/8_Puzzle/style.css
  README.md
  assets/images/8_Puzzle.png
Labels: level2, Ready to merge 🥳, gssoc

#4646 Added About us page for aqua sort and aero combat game
  Games/Aero_Acrobat/about.html
  Games/Aero_Acrobat/index.html
  Games/AquaSort_Game/aboutus.html
  Games/AquaSort_Game/index.html
  Games/AquaSort_Game/style.css
Labels: level1, Ready to merge 🥳, gssoc

#4655 [Enhancement]: Town_Rise_Game Redesign and Responsive fixed
  Games/Town_Rise_Game/asset/Desktop.png
  Games/Town_Rise_Game/asset/Mobile-preview.png
  Games/Town_Rise_Game/asset/Tab.png
  Games/Town_Rise_Game/asset/mobile.png
  Games/Town_Rise_Game/index.html
  Games/Town_Rise_Game/style.css
Labels: level1, Ready to merge 🥳, gssoc

#4136 enhancement of escaperoom game
  Games/escaperoom/script.js
Labels: Ready to merge 🥳, gssoc

#4240 Added Game
  Games/FruitCatcher/README.md
  Games/FruitCatcher/index.html
  Games/FruitCatcher/script.js
  Games/FruitCatcher/style.css
  README.md
  assets/images/FruitCatcher.png
Labels: Pending ⏱️, level2, Ready to merge 🥳, gssoc

#4671 Enhanced City_builder_game to a new level
  Games/City_Builder_Game/README.md
  Games/City_Builder_Game/index.html
  Games/City_Builder_Game/script.js
  Games/City_Builder_Game/styles.css
  assets/images/City_Builder_Game.png
Labels: level2, Ready to merge 🥳, gssoc

#4653 added new game: catch the falling stars
  Games/Catch the falling Stars/README.md
  Games/Catch the falling Stars/index.html
  Games/Catch the falling Stars/script.js
  Games/Catch the falling Stars/styles.css
  README.md
  assets/Catch the Falling Stars.png
Labels: level2, Ready to merge 🥳, gssoc

#4708 [New Game]Zombie_Shooter game added
  Games/Zombie_Shooter/README.md
  Games/Zombie_Shooter/Zombie_Shooter.png
  Games/Zombie_Shooter/Zombie_Shooter_canvas-1.png
  Games/Zombie_Shooter/Zombie_Shooter_canvas.png
  Games/Zombie_Shooter/index.html
  Games/Zombie_Shooter/script.js
  Games/Zombie_Shooter/styles.css
  README.md
  assets/images/Zombie_Shooter.png
  assets/images/Zombie_Shooter_canvas.png
Labels: Ready to merge 🥳, level3, gssoc

#4554 Ant Smasher game
  Games/Ant_Smasher/Readme.md
  Games/Ant_Smasher/index.html
  Games/Ant_Smasher/script.js
  Games/Ant_Smasher/style.css
  README.md
  assets/images/Ant_Smasher.png
  assets/images/Ant_Smasher_Demo.png
  assets/images/Ant_Smasher_dirt.svg
Labels: Ready to merge 🥳, level3, gssoc

#4640 Added Samurai Fighting Game
  Games/Samurai_Fighting_Game/README.md
  Games/Samurai_Fighting_Game/img/background.png
  Games/Samurai_Fighting_Game/img/kenji/Attack1.png
  Games/Samurai_Fighting_Game/img/kenji/Attack2.png
  Games/Samurai_Fighting_Game/img/kenji/Death.png
  Games/Samurai_Fighting_Game/img/kenji/Fall.png
  Games/Samurai_Fighting_Game/img/kenji/Idle.png
  Games/Samurai_Fighting_Game/img/kenji/Jump.png
  Games/Samurai_Fighting_Game/img/kenji/Run.png
  Games/Samurai_Fighting_Game/img/kenji/Take hit.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Attack1.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Attack2.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Death.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Fall.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Idle.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Jump.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Run.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Take Hit - white silhouette.png
  Games/Samurai_Fighting_Game/img/samuraiMack/Take Hit.png
  Games/Samurai_Fighting_Game/img/shop.png
  Games/Samurai_Fighting_Game/index.html
  Games/Samurai_Fighting_Game/index.js
  Games/Samurai_Fighting_Game/js/classes.js
  Games/Samurai_Fighting_Game/js/utils.js
  README.md
  assets/images/Samurai Fighting Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4677 Feat: Added Jigsaw Puzzle Game
  Games/Jigsaw_Puzzle/Readme.md
  Games/Jigsaw_Puzzle/index.html
  Games/Jigsaw_Puzzle/script.js
  Games/Jigsaw_Puzzle/style.css
  README.md
  assets/images/JigsawPuzzle.jpg
  assets/images/Jigsaw_Puzzle_SS.png
Labels: level2, Ready to merge 🥳, gssoc

#4615 added Makeover Game
  Games/Makeover_Game/README.md
  Games/Makeover_Game/img/base/base_1.png
  Games/Makeover_Game/img/base/base_10.png
  Games/Makeover_Game/img/base/base_2.png
  Games/Makeover_Game/img/base/base_3.png
  Games/Makeover_Game/img/base/base_4.png
  Games/Makeover_Game/img/base/base_5.png
  Games/Makeover_Game/img/base/base_6.png
  Games/Makeover_Game/img/base/base_7.png
  Games/Makeover_Game/img/base/base_8.png
  Games/Makeover_Game/img/base/base_9.png
  Games/Makeover_Game/img/bg.png
  Games/Makeover_Game/img/bottom/bottom_1.png
  Games/Makeover_Game/img/bottom/bottom_10.png
  Games/Makeover_Game/img/bottom/bottom_2.png
  Games/Makeover_Game/img/bottom/bottom_3.png
  Games/Makeover_Game/img/bottom/bottom_4.png
  Games/Makeover_Game/img/bottom/bottom_5.png
  Games/Makeover_Game/img/bottom/bottom_6.png
  Games/Makeover_Game/img/bottom/bottom_7.png
  Games/Makeover_Game/img/bottom/bottom_8.png
  Games/Makeover_Game/img/bottom/bottom_9.png
  Games/Makeover_Game/img/camera-icon.png
  Games/Makeover_Game/img/hair/hair_1.png
  Games/Makeover_Game/img/hair/hair_10.png
  Games/Makeover_Game/img/hair/hair_2.png
  Games/Makeover_Game/img/hair/hair_3.png
  Games/Makeover_Game/img/hair/hair_4.png
  Games/Makeover_Game/img/hair/hair_5.png
  Games/Makeover_Game/img/hair/hair_6.png
  Games/Makeover_Game/img/hair/hair_7.png
  Games/Makeover_Game/img/hair/hair_8.png
  Games/Makeover_Game/img/hair/hair_9.png
  Games/Makeover_Game/img/shoes/shoes_1.png
  Games/Makeover_Game/img/shoes/shoes_2.png
  Games/Makeover_Game/img/shoes/shoes_3.png
  Games/Makeover_Game/img/shoes/shoes_4.png
  Games/Makeover_Game/img/shoes/shoes_5.png
  Games/Makeover_Game/img/test/next-btn.png
  Games/Makeover_Game/img/test/next-btn.psd
  Games/Makeover_Game/img/test/prev-btn.png
  Games/Makeover_Game/img/test/test-layout-bg.png
  Games/Makeover_Game/img/test/test-layout.psd
  Games/Makeover_Game/img/top/top_1.png
  Games/Makeover_Game/img/top/top_10.png
  Games/Makeover_Game/img/top/top_2.png
  Games/Makeover_Game/img/top/top_3.png
  Games/Makeover_Game/img/top/top_4.png
  Games/Makeover_Game/img/top/top_5.png
  Games/Makeover_Game/img/top/top_6.png
  Games/Makeover_Game/img/top/top_7.png
  Games/Makeover_Game/img/top/top_8.png
  Games/Makeover_Game/img/top/top_9.png
  Games/Makeover_Game/index.html
  Games/Makeover_Game/script.js
  Games/Makeover_Game/styles.css
  README.md
  assets/images/Makeover_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4695 Added Pattern Creation Game
  Games/Pattern_Creation_Game/Readme.md
  Games/Pattern_Creation_Game/index.html
  Games/Pattern_Creation_Game/script.js
  Games/Pattern_Creation_Game/styles.css
  README.md
  assets/images/Pattern_Creation_Game.PNG
Labels: Ready to merge 🥳, level3, gssoc

#4716 Cooking Challenge game is added
  Games/Cooking_Challenge_Game/README.md
  Games/Cooking_Challenge_Game/index.html
  Games/Cooking_Challenge_Game/script.js
  Games/Cooking_Challenge_Game/styles.css
  README.md
  assets/images/Cooking_Challenge_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4723 Added Brain Card Game
  Games/Brain_card_game/assets/braincard.png
  Games/Brain_card_game/index.html
  Games/Brain_card_game/index.js
  Games/Brain_card_game/readme.md
  Games/Brain_card_game/style.css
  README.md
  assets/images/braincard.png
Labels: level2, Ready to merge 🥳, gssoc

#4762 [New game]: Rock Paper Scissors Neon Theme
  Games/Rock_Paper_Scissors_Neon/README.md
  Games/Rock_Paper_Scissors_Neon/index.html
  Games/Rock_Paper_Scissors_Neon/script.js
  Games/Rock_Paper_Scissors_Neon/style.css
  README.md
  assets/images/Rock_Paper_Scissors_Neon.png
Labels: level2, Ready to merge 🥳, gssoc

#4621 added index.html,styles.css,script.js ,README.md,Maze_Runner.ong in a…
  Games/Maze_Runner/README.md
  Games/Maze_Runner/index.html
  Games/Maze_Runner/script.js
  Games/Maze_Runner/styles.css
  README.md
  assets/images/Maze_Runner.png
Labels: level2, Ready to merge 🥳, gssoc

#4643 added Bubble Shooter game
  Games/Bubble_Shooter/Bubble Shooter.png
  Games/Bubble_Shooter/README.md
  Games/Bubble_Shooter/index.html
  Games/Bubble_Shooter/script.js
  Games/Bubble_Shooter/style.css
  README.md
  assets/images/Bubble Shooter.png
Labels: Ready to merge 🥳, level3, gssoc

#4674 New Game: 2048_win
  Games/2048_win/script.js
Labels: Ready to merge 🥳, gssoc

#4735 [Enhancement]: Alien_Invasion game doesn't work mismatch logic
  Games/Alien_Invasion/asset/Macbook-Air.png
  Games/Alien_Invasion/asset/Mobile.png
  Games/Alien_Invasion/asset/iPad-PRO-11.png
  Games/Alien_Invasion/index.html
  Games/Alien_Invasion/script.js
  Games/Alien_Invasion/style.css
Labels: Ready to merge 🥳, level3, gssoc

#4739 Added Align 4 Game
  Games/Align_4_Game/Readme.md
  Games/Align_4_Game/index.html
  Games/Align_4_Game/scripts/index.js
  Games/Align_4_Game/scripts/worker.js
  Games/Align_4_Game/styles/index.processed.css
  Games/Align_4_Game/styles/index.scss
  README.md
  assets/images/Align_4.webp
  assets/images/Align_4_Game.png
Labels: Ready to merge 🥳, level3, gssoc

#4741 [New game]: Want to Add Space Dominator Game #4686
  Games/Space_Dominators/app.js
  Games/Space_Dominators/appCharacters.js
  Games/Space_Dominators/appEffects.js
  Games/Space_Dominators/appLevel.js
  Games/Space_Dominators/appObjects.js
  Games/Space_Dominators/engine/build/build.bat
  Games/Space_Dominators/engine/build/build.html
  Games/Space_Dominators/engine/build/engineBuild.js
  Games/Space_Dominators/engine/build/index.html
  Games/Space_Dominators/engine/build/setupBuild.bat
  Games/Space_Dominators/engine/engine.js
  Games/Space_Dominators/engine/engineAudio.js
  Games/Space_Dominators/engine/engineDebug.js
  Games/Space_Dominators/engine/engineDraw.js
  Games/Space_Dominators/engine/engineInput.js
  Games/Space_Dominators/engine/engineObject.js
  Games/Space_Dominators/engine/engineParticle.js
  Games/Space_Dominators/engine/engineTileLayer.js
  Games/Space_Dominators/engine/engineUtil.js
  Games/Space_Dominators/engine/engineWebGL.js
  Games/Space_Dominators/favicon.ico
  Games/Space_Dominators/index.html
  Games/Space_Dominators/package.json
  Games/Space_Dominators/tiles.png
  README.md
  assets/images/Space_Dominators.png
Labels: Ready to merge 🥳, level3, gssoc

#4752 adding a new game dodge teh blocks
  Games/Dodge the Blocks/README.md
  Games/Dodge the Blocks/index.html
  Games/Dodge the Blocks/script.js
  Games/Dodge the Blocks/style.css
  README.md
  assets/images/dodge_the_blocks.png.png
Labels: Ready to merge 🥳, level3, gssoc

#4761 fixed the bugs of Main website
  Games/Puzzle_Game/index.html
  assets/Forest_guardian.png
  assets/Ping_Pong_Singleplayer.png
  assets/css/style.css
  assets/images/Catch the Falling Stars.png
  assets/images/Path_finder.png
  assets/images/Star_trek_img.png
  assets/images/StonePaper.png
  assets/images/Tic_Tac_Toe.png
  assets/images/Typing_Game.png
  assets/images/spidermango.png
  assets/images/t-rex.png
  assets/js/gamesData.json
  assets/js/index.js
  assets/js/script.js
  assets/whack a mole.png
  index.html
Labels: level1, Ready to merge 🥳, gssoc

#4759 New Game:-Dice_Rolling_simulator
  Games/Dice_rolling_simulator/README.md
  Games/Dice_rolling_simulator/dice_1.png
  Games/Dice_rolling_simulator/dice_2.png
  Games/Dice_rolling_simulator/dice_3.png
  Games/Dice_rolling_simulator/dice_4.png
  Games/Dice_rolling_simulator/dice_5.png
  Games/Dice_rolling_simulator/dice_6.png
  Games/Dice_rolling_simulator/main3.py
  README.md
  assets/images/Dice_Rolling_simulator_Game.png
Labels: level2, Ready to merge 🥳, gssoc

#4767 feat: Adding a new game Single_Player_Solitaire
  Games/Single_Player_Solitaire/README.md
  Games/Single_Player_Solitaire/index.html
  Games/Single_Player_Solitaire/script.js
  Games/Single_Player_Solitaire/styles.css
  README.md
  assets/images/Single_Player_Solitaire.png
Labels: Ready to merge 🥳, level3, gssoc

#4769 Added Hexsweep Game
  Games/Hexsweep-Game/README.md
  Games/Hexsweep-Game/index.html
  Games/Hexsweep-Game/script.js
  Games/Hexsweep-Game/styles.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4618 Hide and Seek Game
  Games/Hide_And_Seek/README.md
  Games/Hide_And_Seek/assets/image1.png
  Games/Hide_And_Seek/assets/image2.png
  Games/Hide_And_Seek/assets/image3.png
  Games/Hide_And_Seek/index.html
  Games/Hide_And_Seek/script.js
  Games/Hide_And_Seek/style.css
  README.md
  assets/images/Hide_and_Seek.png
Labels: level2, Ready to merge 🥳, gssoc

#4670 Enhancement of UI of Click the Circle game and adding some new features such as increasing time, button position .
  Games/click_circle/README.md
  Games/click_circle/index.html
  Games/click_circle/script.js
  Games/click_circle/style.css
Labels: Ready to merge 🥳, gssoc

#4800 added Catch Him
  Games/Catch Him/README.md
  Games/Catch Him/audios/hit.m4a
  Games/Catch Him/images/Catch_him.png
  Games/Catch Him/images/favicon.jpg
  Games/Catch Him/images/player.png
  Games/Catch Him/images/ralph.png
  Games/Catch Him/images/wall.png
  Games/Catch Him/index.html
  Games/Catch Him/scripts/engine.js
  Games/Catch Him/styles/main.css
  Games/Catch Him/styles/reset.css
  README.md
  assets/images/Catch_him.png
  assets/images/Catch_him.webp
Labels: Ready to merge 🥳, level3, gssoc

#4764 Added Uno game with computer
  Games/UNO_game_with_Computer/Assets/UNO_Cards.png
  Games/UNO_game_with_Computer/Assets/UNO_Interface.png
  Games/UNO_game_with_Computer/Assets/UNO_Rules.png
  Games/UNO_game_with_Computer/README.md
  Games/UNO_game_with_Computer/index.html
  Games/UNO_game_with_Computer/script.js
  Games/UNO_game_with_Computer/style.css
  README.md
  assets/images/UNO_Game_With_Computer.png
Labels: Ready to merge 🥳, level3, gssoc

#4781 Beyblade Game Enhanced : Added many features, Nav Bar, a note on How to Play, Stadium and many more!!
  Games/Beyblade/3D Stadium.glb
  Games/Beyblade/BB-LOGO.png
  Games/Beyblade/README.md
  Games/Beyblade/assets/Webpage.png
  Games/Beyblade/assets/b1.jpg
  Games/Beyblade/assets/b2.png
  Games/Beyblade/assets/bey1.png
  Games/Beyblade/assets/bey2.jpg
  Games/Beyblade/index.html
  Games/Beyblade/script.js
  Games/Beyblade/style.css
Labels: level2, Ready to merge 🥳, gssoc

#4797 Added Word Sprint Game
  Games/WordSprint/README.md
  Games/WordSprint/game.png
  Games/WordSprint/home.png
  Games/WordSprint/index.html
  Games/WordSprint/script.js
  Games/WordSprint/style.css
  README.md
  assets/images/wordsprint.png
Labels: Ready to merge 🥳, level3, gssoc

#4802 Navbar Enhanced to be responsive and new working links
  assets/css/navbar.css
  assets/css/style.css
  assets/js/gamesData.json
  index.html
Labels: level2, Ready to merge 🥳, gssoc

#4823 added Guess_The_Murder Game
  Games/Guess_The_Murderer/README.md
  Games/Guess_The_Murderer/images/Eliminated-Suspect.png
  Games/Guess_The_Murderer/images/Suspect1.png
  Games/Guess_The_Murderer/images/Suspect2.png
  Games/Guess_The_Murderer/images/Suspect3.png
  Games/Guess_The_Murderer/images/Suspect4.png
  Games/Guess_The_Murderer/images/Suspect5.png
  Games/Guess_The_Murderer/images/Suspect6.png
  Games/Guess_The_Murderer/images/clue1.jpg
  Games/Guess_The_Murderer/images/clue2.jpg
  Games/Guess_The_Murderer/images/clue3.jpg
  Games/Guess_The_Murderer/images/clue4.jpg
  Games/Guess_The_Murderer/images/clue5.jpg
  Games/Guess_The_Murderer/images/clue6.jpg
  Games/Guess_The_Murderer/index.html
  Games/Guess_The_Murderer/script.js
  Games/Guess_The_Murderer/style.css
  README.md
  assets/images/Guess_The_Murderer.png
Labels: Ready to merge 🥳, level3, gssoc

#4786 added a game memory flip
  Games/Memory Flip/README.md
  Games/Memory Flip/index.html
  Games/Memory Flip/script.js
  Games/Memory Flip/styles.css
  README.md
  assets/images/Memory_Flip.png
Labels: Ready to merge 🥳, level3, gssoc

#4825 Contributors Link fixed and Games Link added
  index.html
Labels: Ready to merge 🥳, gssoc

#4829 added king of pirates game
  Games/King_Of_Pirates_Quiz/README.md
  Games/King_Of_Pirates_Quiz/background.jpg
  Games/King_Of_Pirates_Quiz/index.html
  Games/King_Of_Pirates_Quiz/script.js
  Games/King_Of_Pirates_Quiz/styles.css
  README.md
  assets/images/King_Of_Pirates.jpg
Labels: Ready to merge 🥳, level3, gssoc

#4811 Added Simon Says game
  Games/Simon_Says/README.md
  Games/Simon_Says/game.png
  Games/Simon_Says/index.html
  Games/Simon_Says/index.js
  Games/Simon_Says/sounds/blue.mp3
  Games/Simon_Says/sounds/green.mp3
  Games/Simon_Says/sounds/red.mp3
  Games/Simon_Says/sounds/wrong.mp3
  Games/Simon_Says/sounds/yellow.mp3
  Games/Simon_Says/styles.css
  README.md
  assets/images/Simon_Says.png
Labels: Ready to merge 🥳, level3, gssoc

#4204 Fixing theme toggle
  assets/js/gamesData.json
  assets/js/index.js
  assets/js/script.js
Labels: Ready to merge 🥳, gssoc

#4772 [New game]: Blink Beat #4770
  Games/Blink_Beat/README.md
  Games/Blink_Beat/Script.js
  Games/Blink_Beat/assets/images/Blibk_Beat_1.jpg
  Games/Blink_Beat/assets/images/Blink_Beat.png
  Games/Blink_Beat/assets/images/Blink_Beat_2.jpg
  Games/Blink_Beat/assets/images/Blink_Beat_3.jpg
  Games/Blink_Beat/assets/sounds/blue.mp3
  Games/Blink_Beat/assets/sounds/green.mp3
  Games/Blink_Beat/assets/sounds/red.mp3
  Games/Blink_Beat/assets/sounds/wrong.mp3
  Games/Blink_Beat/assets/sounds/yellow.mp3
  Games/Blink_Beat/index.html
  Games/Blink_Beat/landing_style.css
  Games/Blink_Beat/page.html
  Games/Blink_Beat/styles.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4816 Added Fruity_Fortune
  Games/Fruity_Fortune/README.md
  Games/Fruity_Fortune/index.html
  Games/Fruity_Fortune/script.js
  Games/Fruity_Fortune/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4862 New Game: Tinker_jump_master
  Games/Tinker_jump_master/README.md
  Games/Tinker_jump_master/assets/Tinker_jump_master.png
  Games/Tinker_jump_master/assets/doodlejumpbg.png
  Games/Tinker_jump_master/assets/doodler-left.png
  Games/Tinker_jump_master/assets/doodler-right.png
  Games/Tinker_jump_master/assets/platform-broken.png
  Games/Tinker_jump_master/assets/platform.png
  Games/Tinker_jump_master/assets/start_bg.png
  Games/Tinker_jump_master/game.html
  Games/Tinker_jump_master/index.html
  Games/Tinker_jump_master/start.css
  Games/Tinker_jump_master/tinkerjump.css
  Games/Tinker_jump_master/tjump.js
  README.md
  assets/images/Tinker_jump_master.png
Labels: Ready to merge 🥳, level3, gssoc

#4873 modified for correct rendering
  assets/images/Brick_Buster.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, gssoc

#4843 [Enhancement]: Avoider Game Responsive Issue
  Games/Avoider_Game/app.js
  Games/Avoider_Game/assets/Desktop.png
  Games/Avoider_Game/assets/iPad.png
  Games/Avoider_Game/assets/mobile.png
  Games/Avoider_Game/style.css
Labels: level1, Ready to merge 🥳, gssoc

#4857 feat: Added a new game Gita_Shloka_Generator
  Games/Gita_Shloka_Generator/README.md
  Games/Gita_Shloka_Generator/app.js
  Games/Gita_Shloka_Generator/image.jpg
  Games/Gita_Shloka_Generator/images/krishna.jpg
  Games/Gita_Shloka_Generator/index.html
  Games/Gita_Shloka_Generator/shloks.json
  Games/Gita_Shloka_Generator/styles.css
  README.md
  assets/images/GIta_Shloka_Generator.png
Labels: Ready to merge 🥳, level3, gssoc

#4878 adding Bulls_And_Cows_New
  Games/Bulls_And_Cows_New/README.MD
  Games/Bulls_And_Cows_New/assets/Bulls_And_Cows_New.png
  Games/Bulls_And_Cows_New/assets/arcade_game.jpg
  Games/Bulls_And_Cows_New/index.html
  Games/Bulls_And_Cows_New/script.js
  Games/Bulls_And_Cows_New/style.css
  README.md
  assets/images/Bulls_And_Cows_New.png
Labels: level2, Ready to merge 🥳, gssoc

#4880 Added Virtual Piano Game
  Games/Virtual_Piano/README.MD
  Games/Virtual_Piano/index.html
  Games/Virtual_Piano/src/scripts/engine.js
  Games/Virtual_Piano/src/styles/main.css
  Games/Virtual_Piano/src/styles/reset.css
  Games/Virtual_Piano/src/tunes/;.wav
  Games/Virtual_Piano/src/tunes/a.wav
  Games/Virtual_Piano/src/tunes/d.wav
  Games/Virtual_Piano/src/tunes/e.wav
  Games/Virtual_Piano/src/tunes/f.wav
  Games/Virtual_Piano/src/tunes/g.wav
  Games/Virtual_Piano/src/tunes/h.wav
  Games/Virtual_Piano/src/tunes/j.wav
  Games/Virtual_Piano/src/tunes/k.wav
  Games/Virtual_Piano/src/tunes/l.wav
  Games/Virtual_Piano/src/tunes/o.wav
  Games/Virtual_Piano/src/tunes/p.wav
  Games/Virtual_Piano/src/tunes/s.wav
  Games/Virtual_Piano/src/tunes/t.wav
  Games/Virtual_Piano/src/tunes/u.wav
  Games/Virtual_Piano/src/tunes/w.wav
  Games/Virtual_Piano/src/tunes/y.wav
  Games/Virtual_Piano/virtual-piano-game.png
  Games/Virtual_Piano/virtual-piano.png
  README.md
  assets/images/virtual-piano.png
Labels: level2, Ready to merge 🥳, gssoc

#4817 Added Rocket_Shooter Game
  Games/Rocket_Shooter/Readme.md
  Games/Rocket_Shooter/assets/Rocket_Shooter.png
  Games/Rocket_Shooter/assets/blast.gif
  Games/Rocket_Shooter/assets/bullet.png
  Games/Rocket_Shooter/assets/enemy-2.png
  Games/Rocket_Shooter/assets/enemy.png
  Games/Rocket_Shooter/assets/galaxy.png
  Games/Rocket_Shooter/assets/images/Rocket_Shooter.png
  Games/Rocket_Shooter/assets/shooter.png
  Games/Rocket_Shooter/favicon.png
  Games/Rocket_Shooter/game.html
  Games/Rocket_Shooter/index.html
  Games/Rocket_Shooter/script.js
  Games/Rocket_Shooter/sounds/shooting.mp3
  Games/Rocket_Shooter/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4840 Fead/add snake gun water game
  Games/Snake_Gun_Water/README.md
  Games/Snake_Gun_Water/composer.json
  Games/Snake_Gun_Water/index.html
  Games/Snake_Gun_Water/index.php
  Games/Snake_Gun_Water/static/css/swg.css
  Games/Snake_Gun_Water/static/images/cong1.jpg
  Games/Snake_Gun_Water/static/images/copy.png
  Games/Snake_Gun_Water/static/images/draw.jpg
  Games/Snake_Gun_Water/static/images/email.png
  Games/Snake_Gun_Water/static/images/facebook.png
  Games/Snake_Gun_Water/static/images/gun.jpg
  Games/Snake_Gun_Water/static/images/instagram.jpg
  Games/Snake_Gun_Water/static/images/linkedin.jpg
  Games/Snake_Gun_Water/static/images/snake.jpg
  Games/Snake_Gun_Water/static/images/water.jpg
  Games/Snake_Gun_Water/static/images/whatsapp.jpg
  Games/Snake_Gun_Water/static/js/swg.js
  README.md
  assets/images/Snake_Gun_Water.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#4851 Fixed readme contribution game table
  README.md
Labels: level1, Ready to merge 🥳, gssoc

#4854 Added ANGRY BIRD game...
  Games/Angry_Bird/README.md
  Games/Angry_Bird/index.html
  Games/Angry_Bird/manifest.json
  Games/Angry_Bird/script.js
  Games/Angry_Bird/styles.css
  README.md
  assets/images/Angry_Bird.png
Labels: Ready to merge 🥳, level3, gssoc

#4842 Added Ninja Hattori game
  .DS_Store
  Games/.DS_Store
  Games/Ninja_Hattori_Game/.DS_Store
  Games/Ninja_Hattori_Game/README.md
  Games/Ninja_Hattori_Game/game.png
  Games/Ninja_Hattori_Game/hattory.png
  Games/Ninja_Hattori_Game/index.html
  Games/Ninja_Hattori_Game/kiyo.png
  Games/Ninja_Hattori_Game/manifest.json
  Games/Ninja_Hattori_Game/nhome.jpg
  Games/Ninja_Hattori_Game/ninja.mp3
  Games/Ninja_Hattori_Game/script.js
  Games/Ninja_Hattori_Game/style.css
  README.md
  assets/.DS_Store
  assets/css/style.css
  assets/images/.DS_Store
  assets/images/Ninja_Hattori_Game.png
  index.html
Labels: Ready to merge 🥳, level3, gssoc

#4871 New Game: Matching_Pair_Game
  Games/Matching_pair/Contact-us.html
  Games/Matching_pair/Contact.css
  Games/Matching_pair/README.md
  Games/Matching_pair/about.css
  Games/Matching_pair/about.html
  Games/Matching_pair/contact.js
  Games/Matching_pair/favicon_io (2)/android-chrome-192x192.png
  Games/Matching_pair/favicon_io (2)/android-chrome-512x512.png
  Games/Matching_pair/favicon_io (2)/apple-touch-icon.png
  Games/Matching_pair/favicon_io (2)/favicon-16x16.png
  Games/Matching_pair/favicon_io (2)/favicon-32x32.png
  Games/Matching_pair/favicon_io (2)/favicon.ico
  Games/Matching_pair/favicon_io (2)/site.webmanifest
  Games/Matching_pair/index.html
  Games/Matching_pair/script.js
  Games/Matching_pair/styles.css
  README.md
  assets/images/Matching_Pair_Game.png
  assets/js/gamesData.json
Labels: level2, Ready to merge 🥳, gssoc

#4902 Main page link is corrected and solved the error
  Games/Master_Typing/index.html
Labels: Ready to merge 🥳, gssoc

#4839 Added Otherworldly Odyssey game
  Games/Otherworldly_Odyssey/README.md
  Games/Otherworldly_Odyssey/img/23.png
  Games/Otherworldly_Odyssey/img/Screenshot (2).png
  Games/Otherworldly_Odyssey/img/Screenshot (3).png
  Games/Otherworldly_Odyssey/img/Screenshot (4).png
  Games/Otherworldly_Odyssey/index.html
  Games/Otherworldly_Odyssey/script.js
  Games/Otherworldly_Odyssey/style.css
  README.md
  assets/images/Otherworldy_Odyssey.png
Labels: Ready to merge 🥳, level3, gssoc

#4899 penalty shoot out game
  Games/Penalty_Shootout_Game/README.md
  Games/Penalty_Shootout_Game/css/main.css
  Games/Penalty_Shootout_Game/css/normalize.css
  Games/Penalty_Shootout_Game/css/normalize.min.css
  Games/Penalty_Shootout_Game/img/background.jpg
  Games/Penalty_Shootout_Game/img/direction-horizontal.png
  Games/Penalty_Shootout_Game/img/direction-vertical.png
  Games/Penalty_Shootout_Game/img/favicons/zee-ball-16x16.png
  Games/Penalty_Shootout_Game/img/favicons/zee-ball-43x43.png
  Games/Penalty_Shootout_Game/img/form.jpg
  Games/Penalty_Shootout_Game/img/instructions.jpg
  Games/Penalty_Shootout_Game/img/keeper-left-jump.png
  Games/Penalty_Shootout_Game/img/keeper-right-jump.png
  Games/Penalty_Shootout_Game/img/keeper-standing.png
  Games/Penalty_Shootout_Game/img/like-gate.jpg
  Games/Penalty_Shootout_Game/img/power.png
  Games/Penalty_Shootout_Game/img/slow-kick-right.png
  Games/Penalty_Shootout_Game/img/small-ball.png
  Games/Penalty_Shootout_Game/img/splash-screen.jpg
  Games/Penalty_Shootout_Game/img/zee-ball.png
  Games/Penalty_Shootout_Game/index.html
  Games/Penalty_Shootout_Game/js/.main.js.swp
  Games/Penalty_Shootout_Game/js/main.js
  Games/Penalty_Shootout_Game/js/plugins.js
  Games/Penalty_Shootout_Game/js/vendor/jquery-1.11.0.min.js
  Games/Penalty_Shootout_Game/js/vendor/modernizr-2.6.2.min.js
  Games/Penalty_Shootout_Game/js/vendor/pathAnimator.js
  README.md
  assets/images/Penalty_Shootout_Game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#4907 [New game]: Pixel Smash
  Games/Pixel_Smash/README.md
  Games/Pixel_Smash/game.js
  Games/Pixel_Smash/index.html
  Games/Pixel_Smash/styles.css
  README.md
  assets/images/Pixel_Smash.png
Labels: level2, Ready to merge 🥳, gssoc

#4940 Added new game Boom Blast
  Games/Boom_Blast/asset/images/Boom_Blast_gameplay.png
  Games/Boom_Blast/asset/images/Boom_Blast_option.png
  Games/Boom_Blast/asset/images/Boom_Blast_scoring.png
  Games/Boom_Blast/asset/images/Boom_Blast_start.png
  Games/Boom_Blast/asset/images/desktop.ini
  Games/Boom_Blast/index.html
  Games/Boom_Blast/readme.md
  Games/Boom_Blast/script.js
  Games/Boom_Blast/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#4872 Added Four_In_Row
  Games/Four_In_Row/README.md
  Games/Four_In_Row/index.html
  Games/Four_In_Row/script.js
  Games/Four_In_Row/style.css
  README.md
  assets/images/Four_In_Row.png
  assets/images/Four_In_Row.webp
Labels: Ready to merge 🥳, level3, gssoc

#4889 adding Guess That Pokemon
  Games/Guess_That_Pokemon/README.md
  Games/Guess_That_Pokemon/allPokemons.js
  Games/Guess_That_Pokemon/assests/pokemon.jpg
  Games/Guess_That_Pokemon/assests/pokemon1.png
  Games/Guess_That_Pokemon/assests/pokemon2.png
  Games/Guess_That_Pokemon/assests/pokemon3.png
  Games/Guess_That_Pokemon/index.html
  Games/Guess_That_Pokemon/script.js
  Games/Guess_That_Pokemon/style.css
  README.md
  assets/images/Guess_That_Pokemon.png
Labels: Ready to merge 🥳, level3, gssoc

#4909 Added Rocket_Ride
  Games/Rocket_Ride/README.md
  Games/Rocket_Ride/index.html
  Games/Rocket_Ride/script.js
  Games/Rocket_Ride/style.css
Labels: Ready to merge 🥳, level3, gssoc

#4923 Added Quick math
  Games/Quick_Math/README.md
  Games/Quick_Math/index.html
  Games/Quick_Math/script.js
  Games/Quick_Math/style.css
  README.md
  assets/images/Quick_Math.png
Labels: Ready to merge 🥳, level3, gssoc

#4896 [New Game] Drum kit added
  Games/Drum_kit/Readme.md
  Games/Drum_kit/images/asset.png
  Games/Drum_kit/images/crash.png
  Games/Drum_kit/images/kick.png
  Games/Drum_kit/images/snare.png
  Games/Drum_kit/images/tom1.png
  Games/Drum_kit/images/tom2.png
  Games/Drum_kit/images/tom3.png
  Games/Drum_kit/images/tom4.png
  Games/Drum_kit/index.html
  Games/Drum_kit/index.js
  Games/Drum_kit/sounds/crash.mp3
  Games/Drum_kit/sounds/kick-bass.mp3
  Games/Drum_kit/sounds/snare.mp3
  Games/Drum_kit/sounds/tom-1.mp3
  Games/Drum_kit/sounds/tom-2.mp3
  Games/Drum_kit/sounds/tom-3.mp3
  Games/Drum_kit/sounds/tom-4.mp3
  Games/Drum_kit/styles.css
  README.md
  assets/images/Drum_kit.png
Labels: Ready to merge 🥳, level3, gssoc

#4926 Updated PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md and CONTRIBUTING_GUIDELINE.md
  .github/CONTRIBUTING_GUIDELINE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: level1, Ready to merge 🥳, gssoc

#4930 [Enhancement]: World Chain Game mismatch logic
  Games/WordChain/assets/Screencast from 2024-07-22 16-29-11.webm
  Games/WordChain/assets/Screenshot from 2024-07-22 16-29-53.png
  Games/WordChain/index.html
  Games/WordChain/script.js
  Games/WordChain/style.css
Labels: level1, Ready to merge 🥳, gssoc

#4931 added Simon logo
  Games/Simon_Game_Challenge/index.html
Labels: level1, Ready to merge 🥳, gssoc

#4939 Added Rock Paper Scissors Lizard Spock Game
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/README.md
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/img/RPSLS-Title.png
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/img/ss1.PNG
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/img/ss2.PNG
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/img/ss3.PNG
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/img/ss4.PNG
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/img/video.mp4
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/index.html
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/script.js
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/styles.css
  Games/Rock_Paper_Scissors_Lizard_Spock_Game/tailwind.config.js
  README.md
  assets/images/Rock_Paper_Scissors_Lizard_Spock_Game.PNG
Labels: Ready to merge 🥳, level3, gssoc

#4937 Added Subway Surfers game
  Games/Subway_Surfers/README.md
  Games/Subway_Surfers/index.html
  Games/Subway_Surfers/manifest.json
  Games/Subway_Surfers/script.js
  Games/Subway_Surfers/styles.css
  README.md
  assets/images/Subway_Surfers.png
Labels: Ready to merge 🥳, level3, gssoc

#4947 Added Hangman Game
  Games/Hangman_Game/README.md
  Games/Hangman_Game/index.html
  Games/Hangman_Game/script.js
  Games/Hangman_Game/style.css
  README.md
  assets/images/Hangman_Game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#4219 CREATED THE GAME ELEPHANT ANT MAN
  Games/Elephant_ant_man/README.md
  Games/Elephant_ant_man/ant.jpg
  Games/Elephant_ant_man/boyy.jpg
  Games/Elephant_ant_man/elephant.jpg
  Games/Elephant_ant_man/index.html
  Games/Elephant_ant_man/screenshot.png
  Games/Elephant_ant_man/script.js
  Games/Elephant_ant_man/style.css
  README.md
  assets/images/screenshot.png
Labels: Pending ⏱️, Ready to merge 🥳, level3, gssoc

#4789 Number Guessing Game is added
  Games/Number Guessing Game/README.md
  Games/Number Guessing Game/index.html
  Games/Number Guessing Game/script.js
  Games/Number Guessing Game/style.css
  README.md
  assets/images/Number Guessing Game.png
  assets/js/gamesData.json
Labels: level2, Ready to merge 🥳, gssoc

#4905 Added DNA Sequencer game
  Games/DNA_Sequencer/README.md
  Games/DNA_Sequencer/index.html
  Games/DNA_Sequencer/script.js
  Games/DNA_Sequencer/style.css
  README.md
  assets/images/DNA_Sequencer.png
Labels: Ready to merge 🥳, level3, gssoc

#4935 add balloon popup game
  Games/Balloon_Popup/Balloon_Popup.png
  Games/Balloon_Popup/Readme.md
  Games/Balloon_Popup/app.js
  Games/Balloon_Popup/index.html
  Games/Balloon_Popup/style.css
  README.md
  assets/images/Balloon_Popup.png
Labels: Ready to merge 🥳, level3, gssoc

#4918 add the typing-test game
  Games/Typing_Test/README.md
  Games/Typing_Test/index.html
  Games/Typing_Test/js/paragraph.js
  Games/Typing_Test/js/script.js
  Games/Typing_Test/styles.css
  README.md
  assets/images/Screenshot from 2024-07-21 20-00-06.png
Labels: Ready to merge 🥳, level3, gssoc

#4938 Add: themes to piano game
  Games/Piano/index.html
  Games/Piano/script.js
  Games/Piano/style.css
  Games/Piano/theme/music1.png
  Games/Piano/theme/music2.png
  Games/Piano/theme/music3.png
  Games/Piano/theme/music4.png
  Games/Piano/theme/music5.png
  Games/Piano/theme/music6.png
Labels: level1, Ready to merge 🥳, gssoc

#4949 [New game]: Circuit Craze
  Games/Circuit_Craze/README.md
  Games/Circuit_Craze/index.html
  Games/Circuit_Craze/script.js
  Games/Circuit_Craze/styles.css
  README.md
  assets/images/Circuit_Craze.png
Labels: Ready to merge 🥳, level3, gssoc

#4950 [New game]: Maze explorer game
  Games/Maze_Explorer/README.md
  Games/Maze_Explorer/image.png
  Games/Maze_Explorer/index.html
  Games/Maze_Explorer/script.js
  Games/Maze_Explorer/style.css
  README.md
  assets/images/Maze_Explorer.png
Labels: Ready to merge 🥳, level3, gssoc

#4953 About us page For anagram checker game
  Games/Anagram_Checker_Game/about.html
  Games/Anagram_Checker_Game/index.html
Labels: level1, Ready to merge 🥳, gssoc

#4975 Comprehensive Website Enhancements: Fix Game Loading, Pagination, Layout Issues, JSON Errors, Cursor Size, and Remove Redundant File
  .github/CONTRIBUTING_GUIDELINE.md
  CONTRIBUTING.md
  assets/css/cursor_transition.css
  assets/css/style.css
  assets/index_old.html
  assets/js/gamesData.json
  assets/js/index.js
  assets/js/script.js
Labels: level2, Ready to merge 🥳, gssoc

#4990 Brain game
  Games/Brain_Game/README.md
  Games/Brain_Game/index.html
  Games/Brain_Game/script.js
  Games/Brain_Game/style.css
  README.md
  assets/images/Brain_Game.png
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#4995 Added new game Eco Warrior
  Games/Eco_Warrior/README.md
  Games/Eco_Warrior/assets/litter.png
  Games/Eco_Warrior/assets/tree.png
  Games/Eco_Warrior/game.js
  Games/Eco_Warrior/index.html
  Games/Eco_Warrior/style.css
  README.md
  assets/images/Eco_Warrior.png
Labels: Ready to merge 🥳, level3, gssoc

#4997 Call Of Duty added
  Games/Call_Of_Duty/README.md
  Games/Call_Of_Duty/index.html
  Games/Call_Of_Duty/manifest.json
  Games/Call_Of_Duty/script.js
  Games/Call_Of_Duty/styles.css
  README.md
  assets/images/Call_Of_Duty.png
Labels: Ready to merge 🥳, level3, gssoc

#5001 added dragon ball game
  Games/Dragon_Ball_Game/Readme.MD
  Games/Dragon_Ball_Game/background.jpg
  Games/Dragon_Ball_Game/index.html
  Games/Dragon_Ball_Game/script.js
  Games/Dragon_Ball_Game/style.css
  README.md
  assets/images/Dragon_Ball_Game.jpg
Labels: Ready to merge 🥳, level3, gssoc

#4934 Issue no. #4730
  Games/Dragon_Slayer/Readme.md
  Games/Dragon_Slayer/Screenshot 2024-07-22 213957.png
  Games/Dragon_Slayer/Screenshot 2024-07-22 214024.png
  Games/Dragon_Slayer/Screenshot 2024-07-22 214121.png
  Games/Dragon_Slayer/Screenshot 2024-07-22 214139.png
  Games/Dragon_Slayer/index.html
  Games/Dragon_Slayer/script.js
  Games/Dragon_Slayer/styles.css
  README.md
  assets/images/image-1.png
  assets/images/image-2.png
  assets/images/image.png
Labels: Ready to merge 🥳, level3, gssoc

#4998 Word Search Game
  Games/Word_Search_Game/Assets/Word_Search_Game(1).jpeg
  Games/Word_Search_Game/Assets/Word_Search_Game(2).jpeg
  Games/Word_Search_Game/README.md
  Games/Word_Search_Game/index.html
  Games/Word_Search_Game/script.js
  Games/Word_Search_Game/styles.css
  README.md
  assets/images/Word_Search_Game.jpeg
  assets/js/gamesData.json
Labels: Ready to merge 🥳, level3, gssoc

#5004 Added Shadow Runner game
  Games/Shadow_Runner/README.md
  Games/Shadow_Runner/index.html
  Games/Shadow_Runner/script.js
  Games/Shadow_Runner/style.css
  README.md
  assets/images/Shadow_Runner.png
Labels: Ready to merge 🥳, level3, gssoc

#5010 Added Minecraft Game
  Games/Minecraft/ manifest.json
  Games/Minecraft/README.md
  Games/Minecraft/index.html
  Games/Minecraft/script.js
  Games/Minecraft/styles.css
  README.md
  assets/images/Minecraft.png
Labels: Ready to merge 🥳, level3, gssoc

#4964 Added Conqueror_Quest
  Games/Conqueror_Quest/README.md
  Games/Conqueror_Quest/index.html
  Games/Conqueror_Quest/script.js
  Games/Conqueror_Quest/style.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#5008 New Game:Endless runner
  Games/EndlessRunner/ReadMe.md
  Games/EndlessRunner/images/images.jpeg
  Games/EndlessRunner/images/one-piece-desktop-kids-running-b5b3kgp79e5rebgg.jpg
  Games/EndlessRunner/images/png-clipart-chicken-pou-pro-chicken-pou-pro-soccer-bird-chicken-liver-game-white.png
  Games/EndlessRunner/images/pngtree-game-pixel-scene-with-stone-png-image_2952040.jpg
  Games/EndlessRunner/images/sky.jpg
  Games/EndlessRunner/images/sky2.jpg
  Games/EndlessRunner/index.html
  Games/EndlessRunner/script.js
  Games/EndlessRunner/style.css
  README.md
  assets/images/Endless_Runner.png
Labels: Ready to merge 🥳, level3, gssoc

#4323 adding a rock paper scissor game
  Games/Rock-Paper/README.md
  Games/Rock-Paper/app.js
  Games/Rock-Paper/images/paper.webp
  Games/Rock-Paper/images/rock.webp
  Games/Rock-Paper/images/scissors.webp
  Games/Rock-Paper/index.html
  Games/Rock-Paper/style.css
  README.md
  assets/images/rock-2004.png
Labels: Pending ⏱️, Changes Requested ⚒️, level2, Ready to merge 🥳, gssoc

#4503 Airhockey game
  Games/Airhocky_game/README.md
  Games/Airhocky_game/airhockey_game.png
  Games/Airhocky_game/game.js
  Games/Airhocky_game/index.html
  README.md
  assets/images/Airhockey_Game.png
Labels: level2, Ready to merge 🥳, gssoc

#4992 Added games to datajson file
  assets/js/gamesData.json
Labels: level1, Ready to merge 🥳, gssoc

#5005 Added Super tetris game
  Games/Super_tetris/Readme.md
  Games/Super_tetris/index.html
  Games/Super_tetris/pieces.js
  Games/Super_tetris/script.js
  Games/Super_tetris/styles.css
  README.md
Labels: Ready to merge 🥳, level3, gssoc

#5027 [New game]: Box Merge
  Games/Box_Merge/README.md
  Games/Box_Merge/index.html
  Games/Box_Merge/script.js
  Games/Box_Merge/style.css
  README.md
  assets/images/Box_Merge.png
Labels: Ready to merge 🥳, level3, gssoc

#5031 Remove non-functional dark/light theme toggle button and update relat…
  assets/css/navbar.css
  assets/js/script.js
  index.html
  package-lock.json
Labels: level1, Ready to merge 🥳, gssoc
